### ISSUE TITLE
Too many open files - getcwd (Errno::EMFILE) while running calabash for a extended period of time

### ISSUE THREAD

**Issue by ryuichiji** [calabash/calabash-ios#1085]
Calabash tests encounters an error while running the tests for a extended amount of time (around 30 minute mark and above) with the following stack trace...
```
Too many open files - getcwd (Errno::EMFILE)
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-2.3.3/lib/cucumber/formatter/backtrace_filter.rb:21:in `pwd'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-2.3.3/lib/cucumber/formatter/backtrace_filter.rb:21:in `exception'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-2.3.3/lib/cucumber/formatter/legacy_api/adapter.rb:1003:in `filtered_exception'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-2.3.3/lib/cucumber/formatter/legacy_api/adapter.rb:1007:in `filtered_step_exception'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-2.3.3/lib/cucumber/formatter/legacy_api/adapter.rb:995:in `step_exception'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-2.3.3/lib/cucumber/formatter/legacy_api/adapter.rb:977:in `step_invocation'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-2.3.3/lib/cucumber/formatter/legacy_api/adapter.rb:191:in `build_step_invocation'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-2.3.3/lib/cucumber/formatter/legacy_api/adapter.rb:373:in `print_step'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-2.3.3/lib/cucumber/formatter/legacy_api/adapter.rb:239:in `after_test_step'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-2.3.3/lib/cucumber/formatter/legacy_api/adapter.rb:95:in `after_test_step'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-2.3.3/lib/cucumber/formatter/legacy_api/adapter.rb:37:in `after_test_step'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-2.3.3/lib/cucumber/formatter/fanout.rb:16:in `block in method_missing'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-2.3.3/lib/cucumber/formatter/fanout.rb:15:in `each'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-2.3.3/lib/cucumber/formatter/fanout.rb:15:in `method_missing'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-core-1.4.0/lib/cucumber/core/test/runner.rb:34:in `around_hook'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-core-1.4.0/lib/cucumber/core/test/around_hook.rb:11:in `describe_to'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:106:in `block (2 levels) in compose_around_hooks'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:107:in `call'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:107:in `compose_around_hooks'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:24:in `block in describe_to'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-core-1.4.0/lib/cucumber/core/test/runner.rb:18:in `call'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-core-1.4.0/lib/cucumber/core/test/runner.rb:18:in `test_case'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-2.3.3/lib/cucumber/filters/prepare_world.rb:11:in `test_case'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-2.3.3/lib/cucumber/filters/apply_around_hooks.rb:8:in `test_case'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-2.3.3/lib/cucumber/filters/apply_after_hooks.rb:5:in `test_case'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-2.3.3/lib/cucumber/filters/apply_before_hooks.rb:5:in `test_case'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-2.3.3/lib/cucumber/filters/apply_after_step_hooks.rb:8:in `test_case'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-2.3.3/lib/cucumber/filters/activate_steps.rb:11:in `test_case'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-2.3.3/lib/cucumber/filters/quit.rb:11:in `test_case'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-core-1.4.0/lib/cucumber/core/test/filters/locations_filter.rb:17:in `block in done'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-core-1.4.0/lib/cucumber/core/test/filters/locations_filter.rb:16:in `each'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-core-1.4.0/lib/cucumber/core/test/filters/locations_filter.rb:16:in `done'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-core-1.4.0/lib/cucumber/core/filter.rb:61:in `done'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-core-1.4.0/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-core-1.4.0/lib/cucumber/core/compiler.rb:23:in `done'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-core-1.4.0/lib/cucumber/core/gherkin/parser.rb:39:in `done'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-core-1.4.0/lib/cucumber/core.rb:29:in `parse'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-core-1.4.0/lib/cucumber/core.rb:18:in `compile'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-2.3.3/lib/cucumber/runtime.rb:68:in `run!'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-2.3.3/lib/cucumber/cli/main.rb:32:in `execute!'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/gems/cucumber-2.3.3/bin/cucumber:8:in `<top (required)>'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/bin/cucumber:23:in `load'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/bin/cucumber:23:in `<main>'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/bin/ruby_executable_hooks:15:in `eval'
/Users/TestMachine/.rvm/gems/ruby-2.2.3@current_gemset/bin/ruby_executable_hooks:15:in `<main>'
```
using `calabash-cucumber (0.19.0)`

**Comment by rKrums** [comment]
Do you have any updates regarding this? I'm facing the exact same stacktrace, and can not find the reason.

**Comment by jmoody** [comment]
The entire stack trace is from cucumber.  Have you checked  for issues in the cucumber GitHub repo?

**Comment by agileseph** [comment]
2 @jmoody and @ryuichiji: 
I believe, it is known case with not configured properly local machine. Sometimes, I get this Exception even when I am running one simulator and few other programs like Ruby Mine IDE and xCode IDE. I believe the original answer can give Apple here on this issue: 

> When running several simulators simultaneously you may exceed the maximum number of processes or maximum open file limits. If this happens attempts to start new processes or open more files will fail. You can recover by shutting down some simulators or closing open programs. MacOS 10.13 automatically scales these limits based on available system memory. On earlier releases these limits are fixed values.
Link: https://www.scribd.com/document/356254929/Release-Notes-for-Xcode-9-Beta-2
