### ISSUE TITLE
Can't touch UIButton on iPhone 5c

### ISSUE THREAD

**Issue by NarKasH** [calabash/calabash-ios#1090]
Can't touch on any of UIButton elements with calabash-cucumber 0.19.0 version only on iPhone 5c. With calabash-cucumber 0.18.2 version it is working.

log output:
```
calabash-ios 0.19.0> touch("UIButton")
RuntimeError: uia action failed because: Timed out running command uia.tapOffset('{:x 160, :y 235}')

	from /Users/dainis/.rvm/gems/ruby-2.2.2/gems/calabash-cucumber-0.19.0/lib/calabash-cucumber/uia.rb:34:in `uia'
	from /Users/dainis/.rvm/gems/ruby-2.2.2/gems/calabash-cucumber-0.19.0/lib/calabash-cucumber/uia.rb:408:in `uia_handle_command'
	from /Users/dainis/.rvm/gems/ruby-2.2.2/gems/calabash-cucumber-0.19.0/lib/calabash-cucumber/uia.rb:155:in `uia_tap_offset'
	from /Users/dainis/.rvm/gems/ruby-2.2.2/gems/calabash-cucumber-0.19.0/lib/calabash-cucumber/actions/instruments_actions.rb:88:in `query_action'
	from /Users/dainis/.rvm/gems/ruby-2.2.2/gems/calabash-cucumber-0.19.0/lib/calabash-cucumber/actions/instruments_actions.rb:15:in `touch'
	from /Users/dainis/.rvm/gems/ruby-2.2.2/gems/calabash-cucumber-0.19.0/lib/calabash-cucumber/core.rb:1219:in `query_action_with_options'
	from /Users/dainis/.rvm/gems/ruby-2.2.2/gems/calabash-cucumber-0.19.0/lib/calabash-cucumber/core.rb:201:in `touch'
	from (irb):2
	from /Users/dainis/.rvm/rubies/ruby-2.2.2/bin/irb:11:in `<main>'
```

**Comment by jmoody** [comment]
@NarKasH 

It very unlikely that the problem is the change from 0.18.2 to 0.19.0, especially if the problem device is iPhone 5c.

https://github.com/calabash/calabash-ios-server/issues?q=milestone%3A0.19.0

Is it possible for you to share your app or reproduce in a public repo?

**Comment by jmoody** [comment]
I think is probably because the :uia_strategy is incorrect because of bug in run-loop.

Can you try:

```
options => {
  :uia_strategy => :host
}

launcher.relaunch(options)
```

**Comment by jmoody** [comment]
Please update to run-loop 2.1.2
