### ISSUE TITLE
Calabash-Android: no implicit conversion of nil into String (TypeError) on app_installation_hooks.rb

### ISSUE THREAD

**Issue by noved210** [calabash/calabash-ios#1095]
Having an issue running my tests using the cucumber command and I get this error:

[tbd@calabash-sandbox]$ cucumber 
Feature: Login feature

  Scenario: As a valid user I can log into my app, thanks # features/my_first.feature:3
  no implicit conversion of nil into String (TypeError)
  ./features/support/app_installation_hooks.rb:18:in `Before'
  no implicit conversion of nil into String (TypeError)
  ./features/support/app_life_cycle_hooks.rb:5:in `Before'
    Given The app has loaded                              # features/step_definitions/calabash_steps.rb:3

Failing Scenarios:
cucumber features/my_first.feature:3 # Scenario: As a valid user I can log into my app, thanks

1 scenario (1 failed)
1 step (1 skipped)
0m0.674s

I've tried specifying the App path using a command like this: APP_PATH=/Users/tbd/Desktop/master/platforms/android/build/outputs/apk/swept.apk

I'm not really sure what's going on but I can tell that it's because the application path isn't being set. I'm just not sure where to go from here :/

**Comment by noved210** [comment]
My apologies I've posted in the wrong category I will close this issue and open a new one under android
