### ISSUE TITLE
Calabash query returning JSON:ParserError: unexpected token when UINavigationController is launched as modal view

### ISSUE THREAD

**Issue by deepthit** [calabash/calabash-ios#1103]
Getting JSON::ParserError while performing query('*') on a modal view in iOS application. This parsing issue is only happening when I launch UINavigationController with UIViewController as modal view. If I directly launch UIViewController as modal view everything is fine.

    **Environment**
    
    calabash-cucumber => 0.17.1
    json_pure => 1.8.3
    run_loop => 2.0.9
    Xcode => Version 7.3 (7D175)
    iOS Simulator => iPhone 6 (9.3)

```
    irb(main):005:0> query('*')
    JSON::ParserError: 419: unexpected token at '{"alpha":1,"enabled":true,"id":"Modal","visible":1,"frame":{"y":20,"x":0,"width":375,"height":44},"accessibilityElement":false,"class":"UINavigationBar","label":null,"description":"<UINavigationBar: 0x7fff4bd82fc0; frame = (0 20; 375 44); opaque = NO; autoresize = W; gestureRecognizers = <NSArray: 0x7fff4bd822c0>; layer = <CALayer: 0x7fff4bd5c5a0>>","value":null,"rect":{"y":20,"center_x":187.5,"center_y":42,"x":0,"width":375,"height":44}},{"alpha":1,"enabled":false,"id":null,"visible":1,"frame":{"y":-20,"x":0,"width":375,"height":64},"accessibilityElement":false,"class":"_UINavigationBarBackground","label":null,"description":"<_UINavigationBarBackground: 0x7fff4bd5b5c0; frame = (0 -20; 375 64); opaque = NO; autoresize = W; userInteractionEnabled = NO; layer = <CALayer: 0x7fff4bd24e70>> - (null)","value":null,"rect":{"y":0,"center_x":187.5,"center_y":32,"x":0,"width":375,"height":64}},{"alpha":1,"enabled":false,"id":null,"visible":1,"frame":{"y":0,"x":0,"width":375,"height":64},"accessibilityElement":false,"class":"_UIBackdropView","label":null,"description":"<_UIBackdropView: 0x7fff4daca550; frame = (0 0; 375 64); opaque = NO; autoresize = W+H; userInteractionEnabled = NO; layer = <_UIBackdropViewLayer: 0x7fff4daeb5a0>>","value":null,"rect":{"y":0,"center_x":187.5,"center_y":32,"x":0,"width":375,"height":64}},{"alpha":1,"enabled":false,"id":null,"visible":1,"frame":{"y":0,"x":0,"width":375,"height":64},"accessibilityElement":false,"class":"_UIBackdropEffectView","label":null,"description":"<_UIBackdropEffectView: 0x7fff4dae94e0; frame = (0 0; 375 64); clipsToBounds = YES; opaque = NO; autoresize = W+H; userInteractionEnabled = NO; layer = <CABackdropLayer: 0x7fff4dae9290>>","value":null,"rect":{"y":0,"center_x":187.5,"center_y":32,"x":0,"width":375,"height":64}},{"alpha":1,"enabled":false,"id":null,"visible":1,"frame":{"y":0,"x":0,"width":375,"height":64},"accessibilityElement":false,"class":"UIView","label":null,"description":"<UIView: 0x7fff4dade4a0; frame = (0 0; 375 64); opaque = NO; autoresize = W+H; userInteractionEnabled = NO; layer = <CALayer: 0x7fff4dad0f80>>","value":null,"rect":{"y":0,"center_x":187.5,"center_y":32,"x":0,"width":375,"height":64}},{"alpha":0.8500000238418579,"enabled":false,"id":null,"visible":1,"frame":{"y":0,"x":0,"width":375,"height":64},"accessibilityElement":false,"class":"UIView","label":null,"description":"<UIView: 0x7fff4dade610; frame = (0 0; 375 64); alpha = 0.85; opaque = NO; autoresize = W+H; userInteractionEnabled = NO; layer = <CALayer: 0x7fff4dade780>>","value":null,"rect":{"y":0,"center_x":187.5,"center_y":32,"x":0,"width":375,"height":64}},{"alpha":1,"enabled":false,"id":null,"visible":1,"frame":{"y":64,"x":0,"width":375,"height":0.5},"accessibilityElement":false,"class":"UIImageView","label":null,"description":"<UIImageView: 0x7fff4bd5ed70; frame = (0 64; 375 0.5); userInteractionEnabled = NO; layer = <CALayer: 0x7fff4bd51d20>> - (null)","value":null,"rect":{"y":64,"center_x":187.5,"center_y":64.25,"x":0,"width":375,"height":0.5}},{"id":null,"description":"<UINavigationButton: 0x7fff4bd82490; frame = (8 7; 53 30); opaque = NO; tintColor = UIDeviceRGBColorSpace 1 1 1 1; layer = <CALayer: 0x7fff4bd61520>>","label":"Cancel","frame":{"y":7,"x":8,"width":53,"height":30},"accessibilityElement":true,"value":null,"alpha":1,"enabled":true,"visible":1,"selected":false,"class":"UINavigationButton","rect":{"y":27,"center_x":34.5,"center_y":42,"x":8,"width":53,"height":30}},{"id":null,"description":"<UIButtonLabel: 0x7fff4bd56cc0; frame = (0 5; 53 20.5); text = 'Cancel'; opaque = NO; userInteractionEnabled = NO; layer = <_UILabelLayer: 0x7fff4bd7d480>>","label":"Cancel","frame":{"y":5,"x":0,"width":53,"height":20.5},"accessibilityElement":true,"value":"Cancel","alpha":1,"enabled":true,"visible":1,"text":"Cancel","class":"UIButtonLabel","rect":{"y":32,"center_x":34.5,"center_y":42.25,"x":8,"width":53,"height":20.5}},{"alpha":1,"enabled":false,"id":null,"visible":1,"frame":{"y":8,"x":163,"width":49.5,"height":27},"accessibilityElement":true,"class":"UINavigationItemView","label":"Modal","description":"<UINavigationItemView: 0x7fff4dadd140; frame = (163 8; 49.5 27); opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0x7fff4daf63c0>>","value":null,"rect":{"y":28,"center_x":187.75,"center_y":41.5,"x":163,"width":49.5,"height":27}},{"id":null,"description":"<UILabel: 0x7fff4dae6980; frame = (0 3.5; 49.5 21.5); text = 'Modal'; opaque = NO; userInteractionEnabled = NO; layer = <_UILabelLayer: 0x7fff4dadfc40>>","label":"Modal","frame":{"y":3.5,"x":0,"width":49.5,"height":21.5},"accessibilityElement":true,"value":"Modal","alpha":1,"enabled":true,"visible":1,"text":"Modal","class":"UILabel","rect":{"y":31.5,"center_x":187.75,"center_y":42.25,"x":163,"width":49.5,"height":21.5}}],"outcome":"SUCCESS"}'
    	from /Users/tayid/.rvm/gems/ruby-2.3.0/gems/json_pure-1.8.3/lib/json/common.rb:155:in `parse'
    	from /Users/tayid/.rvm/gems/ruby-2.3.0/gems/json_pure-1.8.3/lib/json/common.rb:155:in `parse'
    	from /Users/tayid/.rvm/gems/ruby-2.3.0/gems/calabash-cucumber-0.17.1/lib/calabash-cucumber/map.rb:81:in `raw_map'
    	from /Users/tayid/.rvm/gems/ruby-2.3.0/gems/calabash-cucumber-0.17.1/lib/calabash-cucumber/map.rb:53:in `map'
    	from /Users/tayid/.rvm/gems/ruby-2.3.0/gems/calabash-cucumber-0.17.1/lib/calabash-cucumber/core.rb:112:in `query'
    	from (rib):5
    	from /Users/tayid/.rvm/rubies/ruby-2.3.0/bin/irb:11:in `<main>'

```
Public project for reference: https://github.com/deepthit/calabash-ios-modalview/

**Comment by jmoody** [comment]
Please update to 0.19.0.

Why are you using json_pure?  Can you reproduce without using this gem?

Please don't cross post.  I saw your forum issue was in the middle of responding when I saw this issue.  The same people monitor both channels.

**Comment by deepthit** [comment]
Thanks moody. I don't know that same people monitor both channels. I will remove the other post and remember to use one channel from next time.

I removed json_pure gem and updated **calabash to 0.19.0**. I can still reproduce this issue.

I committed latest changes to github repo.

```
calabash-ios 0.19.0> query('*')
JSON::ParserError: 419: unexpected token at '{"alpha":1,"enabled":true,"id":"Modal","visible":1,"frame":{"y":20,"x":0,"width":375,"height":44},"accessibilityElement":false,"class":"UINavigationBar","label":null,"description":"<UINavigationBar: 0x7f918a220ef0; frame = (0 20; 375 44); opaque = NO; autoresize = W; gestureRecognizers = <NSArray: 0x7f9189f20b90>; layer = <CALayer: 0x7f918a239c80>>","value":null,"rect":{"y":20,"center_x":187.5,"center_y":42,"x":0,"width":375,"height":44}},{"alpha":1,"enabled":false,"id":null,"visible":1,"frame":{"y":-20,"x":0,"width":375,"height":64},"accessibilityElement":false,"class":"_UINavigationBarBackground","label":null,"description":"<_UINavigationBarBackground: 0x7f9189e6bd90; frame = (0 -20; 375 64); opaque = NO; autoresize = W; userInteractionEnabled = NO; layer = <CALayer: 0x7f9189e6bd70>> - (null)","value":null,"rect":{"y":0,"center_x":187.5,"center_y":32,"x":0,"width":375,"height":64}},{"alpha":1,"enabled":false,"id":null,"visible":1,"frame":{"y":0,"x":0,"width":375,"height":64},"accessibilityElement":false,"class":"_UIBackdropView","label":null,"description":"<_UIBackdropView: 0x7f918a270db0; frame = (0 0; 375 64); opaque = NO; autoresize = W+H; userInteractionEnabled = NO; layer = <_UIBackdropViewLayer: 0x7f918a2704f0>>","value":null,"rect":{"y":0,"center_x":187.5,"center_y":32,"x":0,"width":375,"height":64}},{"alpha":1,"enabled":false,"id":null,"visible":1,"frame":{"y":0,"x":0,"width":375,"height":64},"accessibilityElement":false,"class":"_UIBackdropEffectView","label":null,"description":"<_UIBackdropEffectView: 0x7f918a275e50; frame = (0 0; 375 64); clipsToBounds = YES; opaque = NO; autoresize = W+H; userInteractionEnabled = NO; layer = <CABackdropLayer: 0x7f918a276340>>","value":null,"rect":{"y":0,"center_x":187.5,"center_y":32,"x":0,"width":375,"height":64}},{"alpha":1,"enabled":false,"id":null,"visible":1,"frame":{"y":0,"x":0,"width":375,"height":64},"accessibilityElement":false,"class":"UIView","label":null,"description":"<UIView: 0x7f918a277270; frame = (0 0; 375 64); opaque = NO; autoresize = W+H; userInteractionEnabled = NO; layer = <CALayer: 0x7f918a2773e0>>","value":null,"rect":{"y":0,"center_x":187.5,"center_y":32,"x":0,"width":375,"height":64}},{"alpha":0.8500000238418579,"enabled":false,"id":null,"visible":1,"frame":{"y":0,"x":0,"width":375,"height":64},"accessibilityElement":false,"class":"UIView","label":null,"description":"<UIView: 0x7f918a277400; frame = (0 0; 375 64); alpha = 0.85; opaque = NO; autoresize = W+H; userInteractionEnabled = NO; layer = <CALayer: 0x7f918a277570>>","value":null,"rect":{"y":0,"center_x":187.5,"center_y":32,"x":0,"width":375,"height":64}},{"alpha":1,"enabled":false,"id":null,"visible":1,"frame":{"y":64,"x":0,"width":375,"height":0.5},"accessibilityElement":false,"class":"UIImageView","label":null,"description":"<UIImageView: 0x7f9189e6c520; frame = (0 64; 375 0.5); userInteractionEnabled = NO; layer = <CALayer: 0x7f9189e4ac70>> - (null)","value":null,"rect":{"y":64,"center_x":187.5,"center_y":64.25,"x":0,"width":375,"height":0.5}},{"id":null,"description":"<UINavigationButton: 0x7f9189e692c0; frame = (8 7; 53 30); opaque = NO; tintColor = UIDeviceRGBColorSpace 1 1 1 1; layer = <CALayer: 0x7f9189e5fd70>>","label":"Cancel","frame":{"y":7,"x":8,"width":53,"height":30},"accessibilityElement":true,"value":null,"alpha":1,"enabled":true,"visible":1,"selected":false,"class":"UINavigationButton","rect":{"y":27,"center_x":34.5,"center_y":42,"x":8,"width":53,"height":30}},{"id":null,"description":"<UIButtonLabel: 0x7f9189e69610; frame = (0 5; 53 20.5); text = 'Cancel'; opaque = NO; userInteractionEnabled = NO; layer = <_UILabelLayer: 0x7f9189e69ad0>>","label":"Cancel","frame":{"y":5,"x":0,"width":53,"height":20.5},"accessibilityElement":true,"value":"Cancel","alpha":1,"enabled":true,"visible":1,"text":"Cancel","class":"UIButtonLabel","rect":{"y":32,"center_x":34.5,"center_y":42.25,"x":8,"width":53,"height":20.5}},{"alpha":1,"enabled":false,"id":null,"visible":1,"frame":{"y":8,"x":163,"width":49.5,"height":27},"accessibilityElement":true,"class":"UINavigationItemView","label":"Modal","description":"<UINavigationItemView: 0x7f918a2165e0; frame = (163 8; 49.5 27); opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0x7f918a216790>>","value":null,"rect":{"y":28,"center_x":187.75,"center_y":41.5,"x":163,"width":49.5,"height":27}},{"id":null,"description":"<UILabel: 0x7f918a22eeb0; frame = (0 3.5; 49.5 21.5); text = 'Modal'; opaque = NO; userInteractionEnabled = NO; layer = <_UILabelLayer: 0x7f918a22c7e0>>","label":"Modal","frame":{"y":3.5,"x":0,"width":49.5,"height":21.5},"accessibilityElement":true,"value":"Modal","alpha":1,"enabled":true,"visible":1,"text":"Modal","class":"UILabel","rect":{"y":31.5,"center_x":187.75,"center_y":42.25,"x":163,"width":49.5,"height":21.5}}],"outcome":"SUCCESS"}'
	from /Users/tayid/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/common.rb:156:in `parse'
	from /Users/tayid/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/common.rb:156:in `parse'
	from /Users/tayid/.rvm/gems/ruby-2.3.0/gems/calabash-cucumber-0.19.0/lib/calabash-cucumber/map.rb:87:in `raw_map'
	from /Users/tayid/.rvm/gems/ruby-2.3.0/gems/calabash-cucumber-0.19.0/lib/calabash-cucumber/map.rb:58:in `map'
	from /Users/tayid/.rvm/gems/ruby-2.3.0/gems/calabash-cucumber-0.19.0/lib/calabash-cucumber/core.rb:146:in `query'
	from (irb):3
	from /Users/tayid/.rvm/rubies/ruby-2.3.0/bin/irb:11:in `<main>'
```

**Comment by jmoody** [comment]
Thank you for the project to reproduce.

In [TestModalViewController.m:41](https://github.com/deepthit/calabash-ios-modalview/blob/master/Calabash-Modal/TestModalViewController.m#L41) there is one or more non-UTF8 characters at the end of "Modal".

---

![image](https://cloud.githubusercontent.com/assets/466104/15461140/796f3210-20b8-11e6-88a8-0185d03976ff.png)

```
 40     // any defaults to set
 41     self.title = @"Modal^S";
```

After removing the characters, `query("*")` succeeds.
