### ISSUE TITLE
Crashed when launch ios app

### ISSUE THREAD

**Issue by Joyce-Qu** [calabash/calabash-ios#1178]
XCode: Version 8.1 beta (8T29o)
IOS Version: 10.0.1
calabash-cucumber: 0.20.0
calabash-ios-server: 0.20.1
cucumber: 2.4.0
run_loop: 2.2.0

Calabash crashed several times when launch IOS test app.

 ```
     2016-09-27 17:28:16.413 iOSDeviceManager[58302:5784427] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[203]'
      *** First throw call stack:
      (
      	0   CoreFoundation                      0x00007fff89f044f2 __exceptionPreprocess + 178
      	1   libobjc.A.dylib                     0x00007fff9505af7e objc_exception_throw + 48
      	2   CoreFoundation                      0x00007fff89df6372 -[__NSPlaceholderArray initWithObjects:count:] + 290
      	3   CoreFoundation                      0x00007fff89e33a33 -[NSArray initWithArray:range:copyItems:] + 451
      	4   CoreFoundation                      0x00007fff89e51de6 +[NSArray arrayWithArray:] + 70
      	5   iOSDeviceManager                    0x0000000103229fc4 +[MobileProfile nonExpiredIOSProfiles] + 237
      	6   iOSDeviceManager                    0x000000010323a550 -[BundleResignerFactory mobileProfiles] + 46
      	7   iOSDeviceManager                    0x000000010323a115 -[BundleResignerFactory resignerWithBundlePath:deviceUDID:identity:] + 77
      	8   iOSDeviceManager                    0x000000010323a3e9 -[BundleResignerFactory resignerWithBundlePath:deviceUDID:signingIdentityString:] + 186
      	9   iOSDeviceManager                    0x000000010322f8de -[Codesigner signBundleAtPath:error:] + 173
      	10  XCTestBootstrap                     0x00000001033ff8d7 -[FBProductBundleBuilder buildWithError:] + 1199
      	11  iOSDeviceManager                    0x000000010322d8a1 +[PhysicalDevice installApp:deviceID:updateApp:codesignID:] + 371
      	12  iOSDeviceManager                    0x0000000103230725 +[Device installApp:deviceID:updateApp:codesignID:] + 146
      	13  iOSDeviceManager                    0x000000010322e2e0 +[InstallAppCommand execute:] + 419
      	14  iOSDeviceManager                    0x0000000103233a56 +[CLI process:] + 1171
      	15  iOSDeviceManager                    0x00000001032288d9 main + 104
      	16  libdyld.dylib                       0x00007fff909a65ad start + 1
      	17  ???                                 0x0000000000000008 0x0 + 8
      )
      libc++abi.dylib: terminating with uncaught exception of type NSException
       (RunLoop::Shell::Error)
      ./ta_features/support/devices.rb:325:in `launch'
      ./ta_features/step_definitions/check_device.rb:30:in `block in check_device'
      ./ta_features/step_definitions/check_device.rb:25:in `times'
      ./ta_features/step_definitions/check_device.rb:25:in `check_device'
      ./ta_features/step_definitions/check_device.rb:113:in `/^I have (\d+) (.*) (?:devices|device)$/'
      ta_features/filecapture.feature:5:in `Given I have 1 ios device'


```
there is full output
[test-output.txt](https://github.com/calabash/calabash-ios/files/495126/test-output.txt)

**Comment by jmoody** [comment]
Will be fixed in the next run-loop release.

Thank you for your patience.
