### ISSUE TITLE
Connection refused - connect(2) for "10.**.***.**" port 37265.

### ISSUE THREAD

**Issue by gkrinord** [calabash/calabash-ios#1180]
The app launches the first time, first scenario is executed but it starts giving connection time out and not able to code sign in after first scenario. 

There was an error executing:
  
```
  /Users/pair/.rbenv/versions/2.2.3/gemsets/calabash-ios/bundler/gems/run_loop-d9a23c70264d/lib/run_loop/device_agent/bin/iOSDeviceManager install --device-id 3bd195e8e5388407b6a38560c88a9a144ee0724f --app-bundle /Users/pair/.rbenv/versions/2.2.3/gemsets/calabash-ios/bundler/gems/run_loop-d9a23c70264d/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app --codesign-identity iPhone Developer: Customer Apps (4**********F)



 2016-09-27 10:18:28.689 iOSDeviceManager[62329:3625497] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]'
  *** First throw call stack:
  (
  	0   CoreFoundation                      0x00007fff964a14f2 __exceptionPreprocess + 178
  	1   libobjc.A.dylib                     0x00007fff98d2cf7e objc_exception_throw + 48
  	2   CoreFoundation                      0x00007fff96393372 -[__NSPlaceholderArray initWithObjects:count:] + 290
  	3   CoreFoundation                      0x00007fff963d0a33 -[NSArray initWithArray:range:copyItems:] + 451
  	4   CoreFoundation                      0x00007fff963eede6 +[NSArray arrayWithArray:] + 70
  	5   iOSDeviceManager                    0x00000001065e628c +[MobileProfile rankedProfiles:withIdentity:deviceUDID:appBundlePath:] + 406
  	6   iOSDeviceManager                    0x00000001065f6600 -[BundleResignerFactory rankedProfilesWithDeviceUDID:signingIdentity:appBundlePath:] + 132
  	7   iOSDeviceManager                    0x00000001065f61c0 -[BundleResignerFactory resignerWithBundlePath:deviceUDID:identity:] + 248
  	8   iOSDeviceManager                    0x00000001065f490d -[BundleResigner resignPlugInAtPath:] + 148
  	9   iOSDeviceManager                    0x00000001065f47e4 -[BundleResigner resignAppPlugIns] + 282
  	10  iOSDeviceManager                    0x00000001065f41d9 -[BundleResigner resign] + 62
  	11  iOSDeviceManager                    0x00000001065eb92b -[Codesigner signBundleAtPath:error:] + 250
  	12  XCTestBootstrap                     0x00000001067be8d7 -[FBProductBundleBuilder buildWithError:] + 1199
  	13  iOSDeviceManager                    0x00000001065e98a1 +[PhysicalDevice installApp:deviceID:updateApp:codesignID:] + 371
  	14  iOSDeviceManager                    0x00000001065ec725 +[Device installApp:deviceID:updateApp:codesignID:] + 146
  	15  iOSDeviceManager                    0x00000001065ea2e0 +[InstallAppCommand execute:] + 419
  	16  iOSDeviceManager                    0x00000001065efa56 +[CLI process:] + 1171
  	17  iOSDeviceManager                    0x00000001065e48d9 main + 104
  	18  libdyld.dylib                       0x00007fff8c54f5ad start + 1
  )
  libc++abi.dylib: terminating with uncaught exception of type NSException
   (RunLoop::Shell::Error)
  /Users/pair/.rbenv/versions/2.2.3/gemsets/calabash-ios/bundler/gems/run_loop-d9a23c70264d/lib/run_loop/shell.rb:113:in `run_shell_command'
  /Users/pair/.rbenv/versions/2.2.3/gemsets/calabash-ios/bundler/gems/run_loop-d9a23c70264d/lib/run_loop/device_agent/ios_device_manager.rb:124:in `launch'
  /Users/pair/.rbenv/versions/2.2.3/gemsets/calabash-ios/bundler/gems/run_loop-d9a23c70264d/lib/run_loop/device_agent/client.rb:1171:in `launch_cbx_runner'
  /Users/pair/.rbenv/versions/2.2.3/gemsets/calabash-ios/bundler/gems/run_loop-d9a23c70264d/lib/run_loop/device_agent/client.rb:259:in `launch'
  /Users/pair/.rbenv/versions/2.2.3/gemsets/calabash-ios/bundler/gems/run_loop-d9a23c70264d/lib/run_loop/device_agent/client.rb:135:in `run'
  /Users/pair/.rbenv/versions/2.2.3/gemsets/calabash-ios/bundler/gems/run_loop-d9a23c70264d/lib/run_loop.rb:113:in `run'
  /Users/pair/.rbenv/versions/2.2.3/gemsets/calabash-ios/bundler/gems/calabash-ios-2412d55b81e5/calabash-cucumber/lib/calabash-cucumber/launcher.rb:413:in `block in new_run_loop'
  /Users/pair/.rbenv/versions/2.2.3/gemsets/calabash-ios/bundler/gems/calabash-ios-2412d55b81e5/calabash-cucumber/lib/calabash-cucumber/launcher.rb:411:in `times'
  /Users/pair/.rbenv/versions/2.2.3/gemsets/calabash-ios/bundler/gems/calabash-ios-2412d55b81e5/calabash-cucumber/lib/calabash-cucumber/launcher.rb:411:in `new_run_loop'
  /Users/pair/.rbenv/versions/2.2.3/gemsets/calabash-ios/bundler/gems/calabash-ios-2412d55b81e5/calabash-cucumber/lib/calabash-cucumber/launcher.rb:370:in `relaunch'
  /Users/pair/jenkins/workspace/CMA_iOS_RC_Device/***********-iPhone/Calabash/tests/helpers/common/01_launch.rb:30:in `Before'
Retrying.. Errno::ECONNREFUSED: (Connection refused - connect(2) for "10.**.***.**" port 37265 (10.**.***.**:37265))

Failing... Errno::ECONNREFUSED
    Given I am on Home screen # tests/helpers/common/common_steps.rb:35
      
      ./tests/screens/base_screen/base_screen.rb:518:in `dismiss_all_notify_me_popups'

```

**Comment by jmoody** [comment]
Please use markdown formatting when reporting issues.  Specifically use "```" to format stack traces.

This will be fixed in the next run-loop release.

Thank you for your patience.
