### ISSUE TITLE
touch_transition fails for None_Animating condition on XCode 8

### ISSUE THREAD

**Issue by xiannicolae** [calabash/calabash-ios#1193]
Hi,

After I installed the XCode 8 and the calabash version 0.20.0, I am seeing quite often the following error:

```
Calabash::Cucumber::WaitHelpers::WaitError: Timeout waiting () for condition (NONE_ANIMATING)
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/calabash-cucumber-0.20.0/lib/calabash-cucumber/wait_helpers.rb:437:in `screenshot_and_retry'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/calabash-cucumber-0.20.0/lib/calabash-cucumber/wait_helpers.rb:315:in `rescue in wait_for_condition'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/calabash-cucumber-0.20.0/lib/calabash-cucumber/wait_helpers.rb:301:in `wait_for_condition'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/calabash-cucumber-0.20.0/lib/calabash-cucumber/wait_helpers.rb:336:in `wait_for_none_animating'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/calabash-cucumber-0.20.0/lib/calabash-cucumber/wait_helpers.rb:356:in `wait_for_transition'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/calabash-cucumber-0.20.0/lib/calabash-cucumber/wait_helpers.rb:367:in `touch_transition'
    from (irb):766
    from /usr/local/var/rbenv/versions/2.3.1/bin/irb:11:in `<main>'
```

However sometimes it works, but in general it fails. Is it a known issue or am I doing something wrong?

Thank you!

**Comment by jmoody** [comment]
More information please.  What is the view you are transitioning to and are there animations on the view?

**Comment by xiannicolae** [comment]
Hi @jmoody ,

I am going for example from UITransitionView (a popup) to a tableView (in this case, the animation means that the popup is dismissed), but I noticed it even between 2 tableViews (the animation is a sliding from right to the left).

I can give you the example for each case:
```
touch_transition("* id: 'idname1'", "* id: 'idname2'")
touch_transition(“* marked: #{name}”, 'NameRowViewCell')
```

Please let me know if I can provide you more info.

**NOTE:** If I am splitting the touch_transition in `touch` or `tap_mark` and `wait_for_element_exists`, this issue is not reproducible at all.

**Comment by jmoody** [comment]
> touch_transition(“* marked: #{name}”, 'NameRowViewCell')

There is typo there ^

Should be:

```
# Incorrect
touch_transition(“* marked: #{name}”, 'NameRowViewCell')

# Correct
# 1. Replace smart quotes (could be a copy and paste artifact)
# 2. Add single quotes to marked value
touch_transition("* marked: '#{name}'", 'NameRowViewCell')
```

**Comment by xiannicolae** [comment]
Sorry, I missed to add the single quotes to the marked value. I was typing the command, but in my code was exactly as you wrote.

**Comment by jmoody** [comment]
Moving to the Backlog.  I think we may never fix this in Calabash 0.x.
