### ISSUE TITLE
Error in run_loop on server start

### ISSUE THREAD

**Issue by redjames** [calabash/calabash-ios#1225]
I'm getting this error when I run my scripts:
```
NoMethodError: undefined method `[]' for #<RunLoop::DeviceAgent::Client:0x007fd2fb0c5078>
       	from /Users/james/.rvm/gems/ruby-2.3.0/gems/calabash-cucumber-0.19.2/lib/calabash-cucumber/launcher.rb:81:in `to_s'
       	from /Users/james/.rvm/gems/ruby-2.3.0/gems/calabash-cucumber-0.19.2/lib/calabash-cucumber/launcher.rb:92:in `inspect'
       	from /Users/james/.rvm/gems/ruby-2.3.0/gems/run_loop-2.2.1/lib/run_loop/patches/awesome_print.rb:13:in `awesome_self'
       	from /Users/james/.rvm/gems/ruby-2.3.0/gems/awesome_print-1.7.0/lib/awesome_print/formatter.rb:36:in `format'
       	from /Users/james/.rvm/gems/ruby-2.3.0/gems/awesome_print-1.7.0/lib/awesome_print/inspector.rb:148:in `unnested'
       	from /Users/james/.rvm/gems/ruby-2.3.0/gems/awesome_print-1.7.0/lib/awesome_print/inspector.rb:115:in `awesome'
       	from /Users/james/.rvm/gems/ruby-2.3.0/gems/awesome_print-1.7.0/lib/awesome_print/core_ext/kernel.rb:10:in `ai'
       	from /Users/james/.rvm/gems/ruby-2.3.0/gems/awesome_print-1.7.0/lib/awesome_print/core_ext/kernel.rb:20:in `ap'
       	from /Users/james/.rvm/gems/ruby-2.3.0/gems/awesome_print-1.7.0/lib/awesome_print/inspector.rb:33:in `output_value'
       	from /Users/james/.rvm/rubies/ruby-2.3.0/bin/irb:11:in `<main>'
```

Despite the error, the application itself is launched. I'm getting the IPA from the dev team with calabash_framework 0.19...

Versions:
```
calabash-cucumber: 0.19.2
run_loop: 2.2.2
MacOSX: 10.11.6
iOS device: 10.1.1
XCode: 8.1
```

Variables:
```
export DEVICE_TARGET="UDID of device"
export DEVICE_ENDPOINT=http://x.x.x.154:37265
export LC_ALL="en_US.UTF-8"
export RESET_BETWEEN_SCENARIOS=1
export CODE_SIGN_IDENTITY="iPhone Developer: XxxXxx (8W82G439V2)" \
```

I don't know if I'm doing something wrong with the configuration or the variables.

Thanks in advance

**Comment by jmoody** [comment]
You must use Calabash iOS >= 0.20 when using Xcode 8.
