### ISSUE TITLE
calabash-ios setup pod install

### ISSUE THREAD

**Issue by cicerohellmann** [calabash/calabash-ios#1261]
Before anybody raise a rock, I believe that cocoapods should be independent of anything I install in my gems, saving the ones that interfere in it directly.
As this: https://rubygems.org/gems/calabash-cucumber/versions/0.13.0
And this: https://rubygems.org/gems/cocoapods/versions/0.39.0
Shows us, there is nothing that can interfere in each other. So I believe that I'm digging in the wrong way. So I will explain what I'm doing:
I'm having an issue right after I run calabash-ios setup.
I can't run pod install anymore.
It is a fresh installation of MAC OS X Sierra.
This is the output after I run pod install right after I run callabash-ios setup:

`Jenkinss-Mac-mini:Build and Run jenkins$ pod install`

Analyzing dependencies

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/jenkins/.rvm/gems/ruby-2.1.6/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-darwin16.0]
    RubyGems : 2.6.8
        Host : Mac OS X 10.12.2 (16C68)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /Users/jenkins/.rvm/rubies/ruby-2.1.6/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 18fcb35bb822863ad5403b841400bd2936e77ab6
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MAPP' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
 
  # Pods for MAPP
  pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :tag => '3.5.0'
  pod 'SnapKit', '0.22.0'
#  pod 'FSCalendar', '2.3.3'
  pod 'XLPagerTabStrip', '~> 5.0'
  pod 'SwiftyJSON', '2.3.2'
  pod 'Wrap', '1.1.1'
  pod 'AlamofireObjectMapper', '3.0'
  pod 'FCAlertView'
  pod 'DLRadioButton', '1.4.9'
  pod 'DropDown', '1.0.1'
  pod 'RealmSwift'
  pod 'MercadoPagoSDK', '2.0.3.7'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :tag => '4.0.0'
  pod 'VMaskTextField'
  pod 'Adjust', '~> 4.10.2'

    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '2.3'
            end
        end
    end

  target 'MAPPTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :tag => '3.5.0'
    pod 'SnapKit', '0.22.0'
    pod 'XLPagerTabStrip', '~> 5.0'
    pod 'SwiftyJSON', '2.3.2'
    pod 'Wrap', '1.1.1'
    pod 'AlamofireObjectMapper', '3.0'
    pod 'DropDown', '1.0.1'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'VMaskTextField'
   
  end

  target 'MAPPUITests' do
    inherit! :search_paths
    # Pods for testing
  end



end
```

### Error

```
LoadError - cannot load such file -- cfpropertylist
/Users/jenkins/.rvm/gems/ruby-2.1.6/gems/xcodeproj-1.4.2/lib/xcodeproj/plist.rb:25:in `read_from_path'
/Users/jenkins/.rvm/gems/ruby-2.1.6/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:200:in `initialize_from_file'
/Users/jenkins/.rvm/gems/ruby-2.1.6/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:102:in `open'
/Users/jenkins/.rvm/gems/ruby-2.1.6/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:855:in `block (2 levels) in inspect_targets_to_integrate'
/Users/jenkins/.rvm/gems/ruby-2.1.6/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:854:in `each'
/Users/jenkins/.rvm/gems/ruby-2.1.6/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:854:in `block in inspect_targets_to_integrate'
/Users/jenkins/.rvm/gems/ruby-2.1.6/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/jenkins/.rvm/gems/ruby-2.1.6/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:849:in `inspect_targets_to_integrate'
/Users/jenkins/.rvm/gems/ruby-2.1.6/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:66:in `analyze'
/Users/jenkins/.rvm/gems/ruby-2.1.6/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:236:in `analyze'
/Users/jenkins/.rvm/gems/ruby-2.1.6/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/Users/jenkins/.rvm/gems/ruby-2.1.6/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/jenkins/.rvm/gems/ruby-2.1.6/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/Users/jenkins/.rvm/gems/ruby-2.1.6/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:110:in `install!'
/Users/jenkins/.rvm/gems/ruby-2.1.6/gems/cocoapods-1.1.1/lib/cocoapods/command/install.rb:37:in `run'
/Users/jenkins/.rvm/gems/ruby-2.1.6/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/jenkins/.rvm/gems/ruby-2.1.6/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Users/jenkins/.rvm/gems/ruby-2.1.6/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/Users/jenkins/.rvm/gems/ruby-2.1.6/bin/pod:22:in `load'
/Users/jenkins/.rvm/gems/ruby-2.1.6/bin/pod:22:in `<main>'
/Users/jenkins/.rvm/gems/ruby-2.1.6/bin/ruby_executable_hooks:15:in `eval'
/Users/jenkins/.rvm/gems/ruby-2.1.6/bin/ruby_executable_hooks:15:in `<main>'

`

**Comment by jmoody** [comment]
```
$ calabash-ios setup
```

is known to be broken; don't use it.

Use one of the methods described [here](https://github.com/calabash/calabash-ios/wiki/Tutorial%3A-How-to-add-Calabash-to-Xcode) to link Calabash.

> calabash-cucumber 0.13.0

That version is not compatible with Xcode 8.  Use calabash-cucumber >= 0.20.4.

> cocoapods 0.39.0

You have cocoapods 1.1.1 installed.

> ruby 2.1.6

We recommend ruby 2.3.1.

**Comment by cicerohellmann** [comment]
So, just to know, calabash-ios is turning into a abandonware?

**Comment by jmoody** [comment]
No. 

You need to update your environment.

**Comment by cicerohellmann** [comment]
I updated as you told me, and I don't know if this issue belongs here anymore. But I did follow the tutorials, that are outdated, inside the repo. There is anything solid about using calabash ios in the latest version of ios and xcode? 
Xcode 8.2 and iOS 10.2

**Comment by jmoody** [comment]
> tutorials

Which tutorials?    And as far as I know, they are not outdated.

**Comment by cicerohellmann** [comment]
I followed this one: https://github.com/calabash/calabash-ios/wiki/Tutorial%3A--Creating-a-cal-Target

**Comment by jmoody** [comment]
That tutorial is not out of date.

**Comment by cicerohellmann** [comment]
I'm gonna give it a try again, create a sample project and test on it.
