### ISSUE TITLE
calabash iOS console queries working only for localhost server

### ISSUE THREAD

**Issue by bansalvarsha** [calabash/calabash-ios#1266]
Hi Folks,

I am facing an issue is that when I try to view queries from calabash ios console, it shows me an error 

> calabash-ios 0.20.4> query("view")
Retrying.. Errno::ECONNREFUSED: (Connection refused - connect(2) for "127.0.0.1" port 37265 (127.0.0.1:37265))
Retrying.. Errno::ECONNREFUSED: (Connection refused - connect(2) for "127.0.0.1" port 37265 (127.0.0.1:37265))
Failing... Errno::ECONNREFUSED
Errno::ECONNREFUSED: Connection refused - connect(2) for "127.0.0.1" port 37265 (127.0.0.1:37265)
	from /Users/admin/.calabash/sandbox/Gems/gems/httpclient-2.8.2.3/lib/httpclient/session.rb:604:in `initialize'
	from /Users/admin/.calabash/sandbox/Gems/gems/httpclient-2.8.2.3/lib/httpclient/session.rb:604:in `new'
	from /Users/admin/.calabash/sandbox/Gems/gems/httpclient-2.8.2.3/lib/httpclient/session.rb:604:in `create_socket'
	from /Users/admin/.calabash/sandbox/Gems/gems/httpclient-2.8.2.3/lib/httpclient/session.rb:749:in `block in connect'
	from /Users/admin/.calabash/sandbox/Rubies/2.1.6-p336/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
	from /Users/admin/.calabash/sandbox/Rubies/2.1.6-p336/lib/ruby/2.1.0/timeout.rb:101:in `call'
	from /Users/admin/.calabash/sandbox/Rubies/2.1.6-p336/lib/ruby/2.1.0/timeout.rb:101:in `timeout'
	from /Users/admin/.calabash/sandbox/Gems/gems/httpclient-2.8.2.3/lib/httpclient/session.rb:742:in `connect'
	from /Users/admin/.calabash/sandbox/Gems/gems/httpclient-2.8.2.3/lib/httpclient/session.rb:504:in `query'
	from /Users/admin/.calabash/sandbox/Gems/gems/httpclient-2.8.2.3/lib/httpclient/session.rb:174:in `query'
	from /Users/admin/.calabash/sandbox/Gems/gems/httpclient-2.8.2.3/lib/httpclient.rb:1240:in `do_get_block'
	from /Users/admin/.calabash/sandbox/Gems/gems/httpclient-2.8.2.3/lib/httpclient.rb:1017:in `block in do_request'
	from /Users/admin/.calabash/sandbox/Gems/gems/httpclient-2.8.2.3/lib/httpclient.rb:1131:in `protect_keep_alive_disconnected'
	from /Users/admin/.calabash/sandbox/Gems/gems/httpclient-2.8.2.3/lib/httpclient.rb:1012:in `do_request'
	from /Users/admin/.calabash/sandbox/Gems/gems/httpclient-2.8.2.3/lib/httpclient.rb:854:in `request'
	from /Users/admin/.calabash/sandbox/Gems/gems/httpclient-2.8.2.3/lib/httpclient.rb:763:in `post'
	from /Users/admin/.calabash/sandbox/Gems/gems/calabash-cucumber-0.20.4/lib/calabash-cucumber/http_helpers.rb:64:in `block in make_http_request'
	from /Users/admin/.calabash/sandbox/Gems/gems/calabash-cucumber-0.20.4/lib/calabash-cucumber/http_helpers.rb:57:in `times'
	from /Users/admin/.calabash/sandbox/Gems/gems/calabash-cucumber-0.20.4/lib/calabash-cucumber/http_helpers.rb:57:in `make_http_request'
	from /Users/admin/.calabash/sandbox/Gems/gems/calabash-cucumber-0.20.4/lib/calabash-cucumber/http_helpers.rb:33:in `http'
	from /Users/admin/.calabash/sandbox/Gems/gems/calabash-cucumber-0.20.4/lib/calabash-cucumber/map.rb:88:in `raw_map'
	from /Users/admin/.calabash/sandbox/Gems/gems/calabash-cucumber-0.20.4/lib/calabash-cucumber/map.rb:58:in `map'
	from /Users/admin/.calabash/sandbox/Gems/gems/calabash-cucumber-0.20.4/lib/calabash-cucumber/core.rb:149:in `query'
	from (irb):3
calabash-ios 0.20.4> 

My project is connected with a iphone device. Is it possible to queries from a device. it is working while project is running with a simulator but not with a real device. 

Can anyone solve my query? 

Thanks in advance

**Comment by bansalvarsha** [comment]
@jmoody, @jonasmaturana  can you please look into this

**Comment by bansalvarsha** [comment]
got the solution to use calabash console as $DEVICE_TARGET=<UDID> DEVICE_ENDPOINT=http://<device ip>:37265 BUNDLE_ID=<ID> calabash-iso console
