### ISSUE TITLE
RuntimeError: Could not get arch info from file

### ISSUE THREAD

**Issue by jjbash** [calabash/calabash-ios#1268]
When i try to launch the test, the calabash ios console retunr this error. 

```
calabash-ios 0.19.1> start_test_server_in_background
DEBUG: Searching for run-loop results with glob: /Users/neoris/.run-loop/results/*
DEBUG: Found 3 previous run-loop results
DEBUG: Will delete 0 previous run-loop results
DEBUG: Deleted 0 previous results in 0.004627 seconds
EXEC: xcrun simctl list devices --json
RuntimeError: Could not get arch info from file:

/Users/neoris/Library/Developer/Xcode/DerivedData/BBVANetCash-bdznkmexoviwphbdzzpyntvzpffq/Build/Products/AppStore-iphonesimulator/BBVA net cash.app/BBVANetCashAppStore.xcconfig

otool -hv -arch all /Users/neoris/Library/Developer/Xcode/DerivedData/BBVANetCash-bdznkmexoviwphbdzzpyntvzpffq/Build/Products/AppStore-iphonesimulator/BBVA net cash.app/BBVANetCashAppStore.xcconfig

exited 1 with the following output:

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: '/Users/neoris/Library/Developer/Xcode/DerivedData/BBVANetCash-bdznkmexoviwphbdzzpyntvzpffq/Build/Products/AppStore-iphonesimulator/BBVA net cash.app/BBVANetCashAppStore.xcconfig': The file was not recognized as a valid object file.
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: internal objdump command failed

	from /Users/neoris/.rvm/gems/ruby-2.3.1/gems/run_loop-2.1.2/lib/run_loop/otool.rb:50:in `arch_info'
	from /Users/neoris/.rvm/gems/ruby-2.3.1/gems/run_loop-2.1.2/lib/run_loop/otool.rb:37:in `executable?'
	from /Users/neoris/.rvm/gems/ruby-2.3.1/gems/run_loop-2.1.2/lib/run_loop/app.rb:221:in `block in executables'
	from /Users/neoris/.rvm/gems/ruby-2.3.1/gems/run_loop-2.1.2/lib/run_loop/app.rb:219:in `glob'
	from /Users/neoris/.rvm/gems/ruby-2.3.1/gems/run_loop-2.1.2/lib/run_loop/app.rb:219:in `executables'
	from /Users/neoris/.rvm/gems/ruby-2.3.1/gems/run_loop-2.1.2/lib/run_loop/app.rb:124:in `calabash_server_version'
	from /Users/neoris/.rvm/gems/ruby-2.3.1/gems/run_loop-2.1.2/lib/run_loop/detect_aut/detect.rb:102:in `app_or_nil'
	from /Users/neoris/.rvm/gems/ruby-2.3.1/gems/run_loop-2.1.2/lib/run_loop/detect_aut/detect.rb:90:in `block in candidate_apps'
	from /Users/neoris/.rvm/gems/ruby-2.3.1/gems/run_loop-2.1.2/lib/run_loop/detect_aut/detect.rb:86:in `each'
	from /Users/neoris/.rvm/gems/ruby-2.3.1/gems/run_loop-2.1.2/lib/run_loop/detect_aut/detect.rb:86:in `candidate_apps'
	from /Users/neoris/.rvm/gems/ruby-2.3.1/gems/run_loop-2.1.2/lib/run_loop/detect_aut/xcode.rb:65:in `block in detect_xcode_apps'
	from /Users/neoris/.rvm/gems/ruby-2.3.1/gems/run_loop-2.1.2/lib/run_loop/detect_aut/xcode.rb:63:in `each'
	from /Users/neoris/.rvm/gems/ruby-2.3.1/gems/run_loop-2.1.2/lib/run_loop/detect_aut/xcode.rb:63:in `detect_xcode_apps'
	from /Users/neoris/.rvm/gems/ruby-2.3.1/gems/run_loop-2.1.2/lib/run_loop/detect_aut/detect.rb:41:in `app_for_simulator'
	from /Users/neoris/.rvm/gems/ruby-2.3.1/gems/run_loop-2.1.2/lib/run_loop/detect_aut/detect.rb:165:in `detect_app'
	from /Users/neoris/.rvm/gems/ruby-2.3.1/gems/run_loop-2.1.2/lib/run_loop/detect_aut/detect.rb:8:in `detect_app_under_test'
	from /Users/neoris/.rvm/gems/ruby-2.3.1/gems/run_loop-2.1.2/lib/run_loop/core.rb:70:in `run_with_options'
	from /Users/neoris/.rvm/gems/ruby-2.3.1/gems/run_loop-2.1.2/lib/run_loop.rb:99:in `run'
	from /Users/neoris/.rvm/gems/ruby-2.3.1/gems/calabash-cucumber-0.19.1/lib/calabash-cucumber/launcher.rb:365:in `block in new_run_loop'
	from /Users/neoris/.rvm/gems/ruby-2.3.1/gems/calabash-cucumber-0.19.1/lib/calabash-cucumber/launcher.rb:363:in `times'
	from /Users/neoris/.rvm/gems/ruby-2.3.1/gems/calabash-cucumber-0.19.1/lib/calabash-cucumber/launcher.rb:363:in `new_run_loop'
	from /Users/neoris/.rvm/gems/ruby-2.3.1/gems/calabash-cucumber-0.19.1/lib/calabash-cucumber/launcher.rb:341:in `relaunch'
	from /Users/neoris/.rvm/gems/ruby-2.3.1/gems/calabash-cucumber-0.19.1/lib/calabash-cucumber/core.rb:952:in `start_test_server_in_background'
	from (irb):1
	from /Users/neoris/.rvm/rubies/ruby-2.3.1/bin/irb:11:in `<main>'
```

More info: 
calabash.framework/Resources/version : 0.20.4
server_version['version'] : 0.20.4
Calabash::Cucumber::MIN_SERVER_VERSION: 0.19.1

I dont know how can i solve this issue...  thanks for the help.

**Comment by jmoody** [comment]
You need to update your calabash-ios version.

* https://github.com/calabash/calabash-ios/wiki/Updating-your-Calabash-iOS-version

You should also update your run-loop version.

* https://github.com/calabash/calabash-ios/wiki/Updating-your-run-loop-version

**Comment by jmoody** [comment]
> .xcconfig

I think it is probably an error to include that file in your application bundle.

I will skip the arch check for `.xcconfig` files in the next release of run-loop, but you should double check that it is correct to include this file in the .app bundle.
