### ISSUE TITLE
Expected 'i386' but found ["x86_64"]

### ISSUE THREAD

**Issue by JoeSSS** [calabash/calabash-ios#1291]
We have started to get this error (~3-10 times per day) after implementing random simulator change on the test start:

```
/Users/jenkins/.rvm/gems/ruby-2.3.1/gems/run_loop-2.4.0/lib/run_loop/lipo.rb:81:in `expect_compatible_arch': Binary at: (RunLoop::IncompatibleArchitecture)
/Users/jenkins/Jenkins/workspace/ios-calabash-calabot-tests/tooling/calabash_ios_tests/build/Calabash.app/XING
does not contain a compatible architecture for target device.
Expected 'i386' but found ["x86_64"].
	from /Users/jenkins/.rvm/gems/ruby-2.3.1/gems/run_loop-2.4.0/lib/run_loop/core.rb:849:in `expect_simulator_compatible_arch'
	from /Users/jenkins/.rvm/gems/ruby-2.3.1/gems/run_loop-2.4.0/lib/run_loop/device_agent/client.rb:102:in `run'
	from /Users/jenkins/.rvm/gems/ruby-2.3.1/gems/run_loop-2.4.0/lib/run_loop.rb:113:in `run'
	from /Users/jenkins/.rvm/gems/ruby-2.3.1/gems/calabash-cucumber-0.20.4/lib/calabash-cucumber/launcher.rb:408:in `block in new_run_loop'
	from /Users/jenkins/.rvm/gems/ruby-2.3.1/gems/calabash-cucumber-0.20.4/lib/calabash-cucumber/launcher.rb:406:in `times'
	from /Users/jenkins/.rvm/gems/ruby-2.3.1/gems/calabash-cucumber-0.20.4/lib/calabash-cucumber/launcher.rb:406:in `new_run_loop'
	from /Users/jenkins/.rvm/gems/ruby-2.3.1/gems/calabash-cucumber-0.20.4/lib/calabash-cucumber/launcher.rb:365:in `relaunch'
	from calabot.rb:24:in `rescue in relaunch'
	from calabot.rb:22:in `relaunch'
	from calabot.rb:18:in `initialize'
	from calabot.rb:364:in `new'
	from calabot.rb:364:in `<main>'
```

Looks like the error doesn't make sense, as it successfully uses the same build in next run.

p.s. We're getting the same error when running tests on run-loop 2.3.0.
p.p.s We're running tests by launch.relaunch() and not by using cucumber.

**Comment by jmoody** [comment]
This is a sanity check.  Your .app is built for x86_64 simulators and you are trying to launch the app on an i386 simulator.

You need to exclude i386 devices from your simulator selection _or_ you need to build your app for all arches.

![image](https://cloud.githubusercontent.com/assets/466104/24871290/687dcee4-1e19-11e7-9eb2-2bd99750801a.png)

```
xcrun xcodebuild  \
  -SYMROOT="${XC_BUILD_DIR}" \
  BUILT_PRODUCTS_DIR="${BUILD_PRODUCTS_DIR}" \
  TARGET_BUILD_DIR="${BUILD_PRODUCTS_DIR}" \
  DWARF_DSYM_FOLDER_PATH="${BUILD_PRODUCTS_DIR}" \
  -project "${XC_PROJECT}" \
  -target "${XC_TARGET}" \
  -configuration "${XC_CONFIG}" \
  -sdk iphonesimulator \
  ARCHS="i386 x86_64" \
  VALID_ARCHS="i386 x86_64" \
  ONLY_ACTIVE_ARCH=NO \
  build
```
