### ISSUE TITLE
keyboard_enter_text error "Timed out waiting for key event to complete" 

### ISSUE THREAD

**Issue by suchikaashyap** [calabash/calabash-ios#1297]
We have upgraded to calabash-cucumber v0.20.5 and run_loop 2.4.1 as suggested in issue #1249. We run against 9.3 simulator version.
We are still experiencing this problem after the upgrade hence opening a new issues?
Any suggestions as to how to circumvent the issue?

**Comment by jmoody** [comment]
@suchikaashyap More details please.

What simulator?  What Xcode version?  What kind of view are you interacting with (UITextView, UITextField, other)? 

Please provide steps to reproduce.

**Comment by suchikaashyap** [comment]
Thanks for the prompt response @jmoody. We are using 9.3 simulator version and xcode 8.2.1.
This issue happens when we are entering text in a UITextField. I am not at work at the moment but can get more details in the next day if you need.

**Comment by suchikaashyap** [comment]
I have had a look at the setup at our end and it looks like we are getting the failures on UITextViews at the moment.
We are also running against a 9.3 version of the simulator. Do you reckon that could have a bearing on the issue still happening.
Also I can't reliably reproduce it when I run a single scenario locally, rather can see it happening when a suite of tests are run. Do you have any steps to reliably reproduce this problem for a single scenario?

**Comment by jmoody** [comment]
> iOS 9.3

The iOS version is not important.  It is the architecture of the simulator that seems to make the difference.

These are the i386 (32 bit) simulators:

* iPhone 5
* iPad 2

**Comment by suchikaashyap** [comment]
We are running against iPhone 6s 9.3 simulator.

**Comment by umara123** [comment]
I'm also getting this issue, though not as frequently as I was when I was on run_loop 2.3.0.

It seems as though the Simulator sometimes gets into a state where this issue occurs repeatedly until the machine is rebooted.

As my app requires user login to use, so the first step of every scenario involves attempting to login.
Calabash gets as far as entering the first character of the username string in the field before throwing the error. Every subsequent scenario fails with the same error.

The app has some react native components - the username field where the tests fail is a `RCTTextField`

```
calabash-cucumber 0.20.4
run_loop 2.4.1

iPhone 6s Simulator, 9.1
Xcode 8.2.1

macOS Sierra 10.12.4
```

**Comment by ivan-fedorov** [comment]
I'm also getting this issue.

calabash-cucumber 0.20.5
run_loop 2.4.1
iPhone 5S Simulator, 9.3
UITextField view
In my case issue is floating. The same scenario can fail in first time and fail in second time and vice versa

**Comment by suchikaashyap** [comment]
@jmoody do you need any more details regarding this issue. The version numbers that we are on are:-
calabash-cucumber 0.20.5
run_loop 2.4.1
iPhone 6S Simulator, 9.3
UITextView view

We are getting this quite periodically when running as a suite of tests. However I am unable to reproduce it whilst running a scenario at a time.
 @umara123 @ivan-fedorov do you have any steps to consistently replicate it whist running a single scenario?

**Comment by suchikaashyap** [comment]
@jmoody just another point worth mentioning really this issue. We are using the enter_text method from the core.rb with the use_keyboard option set to false.
Is there perhaps a different method or any other options we need to be passing to this method?
Also I tried handling this error within the step but as you suggested it looks like since the device agent is in a bad statethe retries don't seem to make a difference.
In our case not all the subsequent scenarios fail when 1 scenario in the suite fails with this error.

**Comment by jmoody** [comment]
> enter_text `:use_keyboard => false`

```
      # ### DeviceAgent
      #
      # This method calls #keyboard_enter_text regardless of the options passed.
```

This key is ignored when using DeviceAgent.

**Comment by jmoody** [comment]
I have reproduced on an iPad 2 iOS 9.3 simulator (32 bit).  I am still trying to reproduce on a 64 bit device.

**Comment by jmoody** [comment]
Are you all using Xcode 8.2.1?  If so, can you try upgrading to Xcode 8.3.2?

**Comment by ivan-fedorov** [comment]
Hi @jmoody,
I'm using Xcode 8.3.2 and the problem still is actual for me. What I've noted, that issue is being reproduced quite often after resetting of simulator. I have run the same set of scenarios multiple times and find out that if this issue has not happened in the first scenario the rest scenarios also most likely worked fine until simulator reset. And if this issue has happened right after reset of simulator then it will be reproduced on other scenarios until next reset of simulator. Hope this will help you somehow.

**Comment by jmoody** [comment]
In a nutshell, I cannot reproduce despite trying very hard. Can someone provide me an app that I can reproduce on?

**Comment by puneetimpinge** [comment]
I am facing "Keyboard didn't open" issue.

iOS 10.2.1
iphone 7

Check logs:

    Given I am in login screen                            # features/steps/sample_steps.rb:1
    When I enter "Test" into textbox 1                # features/steps/base_steps.rb:44
      Keyboard did not appear (Calabash::Cucumber::WaitHelpers::WaitError)
      ./features/steps/base_steps.rb:61:in `/^I enter "(.*?)" into textbox (\d+)$/'
      features/gallery.feature:6:in `When I enter "Test" into textbox 1'

Failing Scenarios:
cucumber features/gallery.feature:4 # Scenario: Capture image for anatomy parts and verify it

1 scenario (1 failed)
3 steps (1 failed, 1 skipped, 1 passed)
1m22.545s

**Comment by jmoody** [comment]
@puneetimpinge Your issue is not related to this problem.  You should insert a sleep or `wait_for_none_animating` before touching the "textbox 1".

**Comment by jmoody** [comment]
Reproduced in SafariWebController TextField. 

![image](https://user-images.githubusercontent.com/466104/27082955-267ce290-5047-11e7-8698-5c18e8901ea3.png)


I still cannot reproduce reliably.

**Comment by alalayla** [comment]
Hi @jmoody,
Problem is still actual for me. It occurs periodically. At the time of input only the first character is typed, and then an error occurs.
![screenshot at sep 28 15-59-44](https://user-images.githubusercontent.com/32261315/30968006-8fc8f446-a466-11e7-909c-1cf2533ecac7.png)

Xcode 8.3
run_loop 2.6.1
IOS 10.3

**Comment by jmoody** [comment]
Can you update to Xcode 9?

**Comment by otamas94** [comment]
I'm also facing this issue on my physical phone when using _keyboard_enter_text_. The funny thing is it broke at one random moment, and since then when my tests are running after 2 hours of running this starts to happen. The _keyboard_enter_text_ stops after 1 character, then fails with this error.

Physical iPhone6, iOS10.3.2
calabash-ios 0.21.5
run_loop 2.7.0
DeviceAgent 1.2.5 on the phone

Exact error:
`calabash-ios 0.21.5> keyboard_enter_text 'calabash@example.com'
RunLoop::DeviceAgent::Client::HTTPError: 
Expected JSON response with no error, but found

Timed out waiting for key event to complete


	from /usr/local/lib/ruby/gems/2.0.0/gems/run_loop-2.7.0/lib/run_loop/device_agent/client.rb:1617:in `expect_300_response'
	from /usr/local/lib/ruby/gems/2.0.0/gems/run_loop-2.7.0/lib/run_loop/device_agent/client.rb:433:in `enter_text_without_keyboard_check'
	from /usr/local/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.21.5/lib/calabash-cucumber/automator/device_agent.rb:262:in `enter_text_with_keyboard'
	from /usr/local/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.21.5/lib/calabash-cucumber/core.rb:746:in `keyboard_enter_text'
	from (irb):33
	from /usr/local/opt/ruby@2.0/bin/irb:12:in `<main>'
calabash-ios 0.21.5> enter_text 'calabash@example.com'
ArgumentError: wrong number of arguments (1 for 2..3)
	from /usr/local/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.21.5/lib/calabash-cucumber/core.rb:776:in `enter_text_in'
	from (irb):34
	from /usr/local/opt/ruby@2.0/bin/irb:12:in `<main>'`

DEBUG=1 shows nothing more about it.

Do you have any workaround or fix for this issue? 

Thanks in advance.

**Comment by xamiell** [comment]
From 2017 and I have the same problem on 2022 💀

**Comment by jmoody** [comment]
@xamiell check the attitude.  This a recurring problem that occurs when new Xcode versions are released.
