### ISSUE TITLE
can not  start  -cal app in my iphone  

### ISSUE THREAD

**Issue by wdarlgx** [calabash/calabash-ios#1316]
Environment:
Calabash :0.20.6
run_loop:2.4.1
Xcode:8.2.1
iphone se:10.3.2
macOS Sierra 10.12.3

Steps to reproduce:

1. Build app to iphone se (10.3.2)
2. Launch calabash-ios console
DEBUG=1 DEVICE_TARGET="a5fdc9ab0ffc28892fb6e3b61ab1ea22a19fce35" APP_BUNDLE_PATH="/Users/zman/xx/xx/test/xx-cal.app" DEVICE_ENDPOINT=http://wifi_ip:37265 calabash-ios console
3. Execute: start_test_server_in_background

Console trace:
calabash-ios 0.20.5> start_test_server_in_background
SHELL: xcrun simctl list devices --json
SHELL: xcrun instruments -s devices
DEBUG: HTTP: get http://192.200.36.74:27753/1.0/health {:retries=>1, :timeout=>0.5}
DEBUG: HTTP: get http://192.200.36.74:27753/1.0/health {:retries=>1, :timeout=>0.5}
DEBUG: Waiting for DeviceAgent to launch...
SHELL: /Library/Ruby/Gems/2.0.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/bin/iOSDeviceManager install --device-id a5fdc9ab0ffc28892fb6e3b61ab1ea22a19fce35 -a /Library/Ruby/Gems/2.0.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app
RunLoop::Shell::TimeoutError: 
Timed out after 120.10 seconds executing

/Library/Ruby/Gems/2.0.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/bin/iOSDeviceManager install --device-id a5fdc9ab0ffc28892fb6e3b61ab1ea22a19fce35 -a /Library/Ruby/Gems/2.0.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app

with a timeout of 120

	from /Library/Ruby/Gems/2.0.0/gems/run_loop-2.4.1/lib/run_loop/shell.rb:104:in `run_shell_command'
	from /Library/Ruby/Gems/2.0.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/ios_device_manager.rb:139:in `launch'
	from /Library/Ruby/Gems/2.0.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/client.rb:1354:in `launch_cbx_runner'
	from /Library/Ruby/Gems/2.0.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/client.rb:271:in `launch'
	from /Library/Ruby/Gems/2.0.0/gems/run_loop-2.4.1/lib/run_loop/device_agent/client.rb:147:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/run_loop-2.4.1/lib/run_loop.rb:113:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.20.5/lib/calabash-cucumber/launcher.rb:411:in `block in new_run_loop'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.20.5/lib/calabash-cucumber/launcher.rb:408:in `times'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.20.5/lib/calabash-cucumber/launcher.rb:408:in `new_run_loop'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.20.5/lib/calabash-cucumber/launcher.rb:366:in `relaunch'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.20.5/lib/calabash-cucumber/core.rb:1568:in `start_test_server_in_background'
	from (irb):1
	from /usr/bin/irb:12:in `<main>'

**Comment by jmoody** [comment]
> /Library/Ruby/Gems/2.0.0/gems

You are using the macOS System Ruby which is not supported.

See https://github.com/calabash/calabash-ios/wiki/Ruby-on-MacOS for options.

**Comment by wdarlgx** [comment]
@jmoody thanks! yeah,i have found this and have update my ruby version to 2.3.1;but still have the same problem?is there still something wrong?

**Comment by jmoody** [comment]
What is the output here:

```
$ tail -F -1000 ~/.calabash/iOSDeviceManager/logs/current.log
```

**Comment by wdarlgx** [comment]
work-mac:test zman$ tail -F 1000 ~/.calabash/iOSDeviceManager/logs/current.log 
tail: 1000: No such file or directory

==> /Users/zman/.calabash/iOSDeviceManager/logs/current.log <==
2017-06-28 18:12:33.181 DEBUG FBControlCoreLogger:130 | IDEKit: Successfully loaded
2017-06-28 18:12:33.181 DEBUG FBControlCoreLogger:130 | IDESourceEditor: Loading from /Users/zman/Downloads/Xcode.app/Contents/PlugIns/IDESourceEditor.ideplugin 
2017-06-28 18:12:33.205 DEBUG FBControlCoreLogger:130 | IDESourceEditor: Successfully loaded
2017-06-28 18:12:33.205 DEBUG FBControlCoreLogger:130 | DFRSupportKit: Loading from /Users/zman/Downloads/Xcode.app/Contents/Frameworks/DFRSupportKit.framework 
2017-06-28 18:12:33.220 DEBUG FBControlCoreLogger:130 | DFRSupportKit: Successfully loaded
2017-06-28 18:12:33.220 DEBUG FBControlCoreLogger:130 | DVTKit: Loading from /Users/zman/Downloads/Xcode.app/Contents/SharedFrameworks/DVTKit.framework 
2017-06-28 18:12:33.220 DEBUG FBControlCoreLogger:130 | DVTKit: Successfully loaded
2017-06-28 18:12:33.220 DEBUG FBControlCoreLogger:130 | DVTFoundation: Already loaded, skipping
2017-06-28 18:12:33.220 DEBUG FBControlCoreLogger:130 | DVTFoundation: DVTDevice has correct path of /Users/zman/Downloads/Xcode.app
2017-06-28 18:12:33.221 DEBUG FBControlCoreLogger:130 | Loaded All Private Frameworks [DTXConnectionServices, IDEFoundation, IDEiOSSupportCore, IBAutolayoutFoundation, IDEKit, IDESourceEditor, DFRSupportKit, DVTKit, DVTFoundation]

**Comment by jampanij** [comment]
@jmoody Please help look into this issue

{code}
Calabash::Cucumber::Launcher #calabash_no_launch? and support for the NO_LAUNCH
environment variable has been removed from Calabash.  This always returns
false.  Please remove this method call from your hooks.
[0m
[35mDEBUG: Invalid CoreSimulator service for active Xcode: try 1 of 4[0m
[36mSHELL: xcrun simctl list devices --json[0m
[36mSHELL: xcrun instruments -s devices[0m
[35mDEBUG: HTTP: get http://0.0.0.0:27753/1.0/health {:retries=>1, :timeout=>0.5}[0m
[35mDEBUG: HTTP: get http://0.0.0.0:27753/1.0/health {:retries=>1, :timeout=>0.5}[0m
[35mDEBUG: Waiting for DeviceAgent to launch...[0m
[36mSHELL: cd /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/run_loop-4.5.2/lib/run_loop/device_agent[0m
[36mSHELL: ditto -xk Frameworks.zip .[0m
[36mSHELL: ditto -xk DeviceAgent-Runner.app.zip .[0m
[36mSHELL: /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/run_loop-4.5.2/lib/run_loop/device_agent/bin/iOSDeviceManager install /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/run_loop-4.5.2/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app --device-id a7d1847acb42df68317a5b29688581978cab8fdd[0m
  Scenario: Gmail Info                                                                          # features/gmail_test.feature:4
  
  Timed out after 120.88 seconds executing
  
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/run_loop-4.5.2/lib/run_loop/device_agent/bin/iOSDeviceManager install /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/run_loop-4.5.2/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app --device-id a7d1847acb42df68317a5b29688581978cab8fdd
  
  with a timeout of 120
   (RunLoop::Shell::TimeoutError)
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/run_loop-4.5.2/lib/run_loop/shell.rb:107:in `run_shell_command'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/run_loop-4.5.2/lib/run_loop/device_agent/ios_device_manager.rb:146:in `launch'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/run_loop-4.5.2/lib/run_loop/device_agent/client.rb:1489:in `launch_cbx_runner'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/run_loop-4.5.2/lib/run_loop/device_agent/client.rb:325:in `launch'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/run_loop-4.5.2/lib/run_loop/device_agent/client.rb:191:in `run'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/run_loop-4.5.2/lib/run_loop.rb:113:in `run'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/calabash-cucumber-0.21.10/lib/calabash-cucumber/launcher.rb:414:in `block in new_run_loop'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/calabash-cucumber-0.21.10/lib/calabash-cucumber/launcher.rb:412:in `times'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/calabash-cucumber-0.21.10/lib/calabash-cucumber/launcher.rb:412:in `new_run_loop'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/calabash-cucumber-0.21.10/lib/calabash-cucumber/launcher.rb:365:in `relaunch'
  /private/tmp/scratchrRzdY9.scratch/test-packageDEkX4Y/ios/features/support/01_launch.rb:18:in `block in <top (required)>'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-3.1.2/lib/cucumber/glue/invoke_in_world.rb:39:in `instance_exec'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-3.1.2/lib/cucumber/glue/invoke_in_world.rb:39:in `block in cucumber_instance_exec_in'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-3.1.2/lib/cucumber/glue/invoke_in_world.rb:54:in `cucumber_run_with_backtrace_filtering'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-3.1.2/lib/cucumber/glue/invoke_in_world.rb:27:in `cucumber_instance_exec_in'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-3.1.2/lib/cucumber/glue/hook.rb:21:in `invoke'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-3.1.2/lib/cucumber/runtime/before_hooks.rb:23:in `block (2 levels) in before_hooks'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/action.rb:24:in `execute'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/step.rb:32:in `execute'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/runner.rb:104:in `execute'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/runner.rb:51:in `execute'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/runner.rb:27:in `test_step'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/step.rb:17:in `describe_to'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/case.rb:28:in `block (3 levels) in describe_to'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/case.rb:27:in `each'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/case.rb:27:in `block (2 levels) in describe_to'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-3.1.2/lib/cucumber/filters/prepare_world.rb:22:in `block in test_case'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/around_hook.rb:17:in `execute'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/runner.rb:104:in `execute'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/runner.rb:51:in `execute'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/runner.rb:34:in `around_hook'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/around_hook.rb:12:in `describe_to'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/case.rb:120:in `block (2 levels) in compose_around_hooks'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/case.rb:121:in `compose_around_hooks'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/case.rb:26:in `block in describe_to'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/runner.rb:19:in `test_case'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/case.rb:25:in `describe_to'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-3.1.2/lib/cucumber/filters/prepare_world.rb:11:in `test_case'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/case.rb:25:in `describe_to'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-core-3.2.1/lib/cucumber/core/filter.rb:57:in `test_case'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-3.1.2/lib/cucumber/filters/retry.rb:18:in `test_case'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/case.rb:25:in `describe_to'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-3.1.2/lib/cucumber/filters/quit.rb:12:in `test_case'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/case.rb:25:in `describe_to'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-3.1.2/lib/cucumber/filters/broadcast_test_run_started_event.rb:21:in `block in done'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-3.1.2/lib/cucumber/filters/broadcast_test_run_started_event.rb:20:in `map'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-3.1.2/lib/cucumber/filters/broadcast_test_run_started_event.rb:20:in `done'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-core-3.2.1/lib/cucumber/core/filter.rb:62:in `done'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-core-3.2.1/lib/cucumber/core/filter.rb:62:in `done'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-core-3.2.1/lib/cucumber/core/filter.rb:62:in `done'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-core-3.2.1/lib/cucumber/core/filter.rb:62:in `done'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-core-3.2.1/lib/cucumber/core/filter.rb:62:in `done'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/filters/locations_filter.rb:20:in `done'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-core-3.2.1/lib/cucumber/core/filter.rb:62:in `done'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-core-3.2.1/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-core-3.2.1/lib/cucumber/core/compiler.rb:24:in `done'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-core-3.2.1/lib/cucumber/core/gherkin/parser.rb:39:in `done'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-core-3.2.1/lib/cucumber/core.rb:32:in `parse'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-core-3.2.1/lib/cucumber/core.rb:21:in `compile'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-3.1.2/lib/cucumber/runtime.rb:75:in `run!'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-3.1.2/lib/cucumber/cli/main.rb:34:in `execute!'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-3.1.2/bin/cucumber:9:in `<top (required)>'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/bin/cucumber:23:in `load'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/bin/cucumber:23:in `<main>'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/bin/ruby_executable_hooks:24:in `eval'
  /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/bin/ruby_executable_hooks:24:in `<main>'
[34mWARN: deprecated '0.20.0' - replaced with attached_to_automator?
/Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/calabash-cucumber-0.21.10/lib/calabash-cucumber/launcher.rb:246:in `active?'
/private/tmp/scratchrRzdY9.scratch/test-packageDEkX4Y/ios/features/support/01_launch.rb:26:in `block in <top (required)>'
/Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-3.1.2/lib/cucumber/glue/invoke_in_world.rb:39:in `instance_exec'
/Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-3.1.2/lib/cucumber/glue/invoke_in_world.rb:39:in `block in cucumber_instance_exec_in'
/Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/cucumber-3.1.2/lib/cucumber/glue/invoke_in_world.rb:54:in `cucumber_run_with_backtrace_filtering'[0m
{code}

**Comment by jmoody** [comment]
DeviceAgent cannot be installed on your device.

This command times out after 120 seconds.

```
iOSDeviceManager install /Users/device-farm/.rvm/gems/ruby-2.5.3@default-ruby-gemset-env-version-1/gems/run_loop-4.5.2/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app --device-id a7d1847acb42df68317a5b29688581978cab8fdd
```

My guess is that the matching algorithm cannot find a good certificate/profile pair for resigning.

You can check the progress of the resigning and install here:

```
$ tail -F -1000 ~/.calabash/iOSDeviceManager/logs/current.log
```

**Comment by jmoody** [comment]
@wdarlgx -1  Please do not try to get my attention by double posting in issues.
