### ISSUE TITLE
DeviceAgent launch and uninstallation errors

### ISSUE THREAD

**Issue by sankalpanand** [calabash/calabash-ios#1337]
Hello,

I have been bumping into this error since a while now. The error manifests as **Could not connect  to the DeviceAgent service.** on the console. I have tried uninstalling DeviceAgent but it never happens successfully. I tried removing DeviceAgent from home screen as well as from Settings, but it always shows up in the output of `ideviceinstaller -l`. 

Please help me in understanding the issue.

Calabash: 0.20.5
Xcode: 8.3.3
iOS: 10.3.3
Run_loop: 2.6.0

> Failed at RubyTestClient:10.93.238.17:Alice-iphone
> #<Failed to execute test command start_test: in test iOS>:
> 	/Users/testmaskin//script/lib/tptest/rubytest_functions.rb:652:in `rescue in handle_command'
> 	/Users/testmaskin//script/lib/tptest/rubytest_functions.rb:588:in `handle_command'
> 	/Users/testmaskin//script/lib/tptest/rubytest_functions.rb:92:in `rescue in start_test': start_test failed for iOS_Enterprise_Call.
> 	/Users/testmaskin//script/lib/tptest/rubytest_functions.rb:85:in `start_test'
> 	/Users/testmaskin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/run_loop-2.6.0/lib/run_loop/device_agent/client.rb:1389:in `rescue in launch_cbx_runner': 
> 
> Could not connect to the DeviceAgent service.
> 
> device: #<Device: iPhone (10.3.3) 62fdfd43b9a96f24d09c1f2fe7091b5b30752fe9>
>    url: http://10.128.96.131:27753/

**Comment by sankalpanand** [comment]
Don't see anything in Current.log - https://gist.github.com/sankalpanand/202d727e741ff46673d7f2e413436a48
