### ISSUE TITLE
Calabash-ios Unable to launch DeviceAgent App with iOS 11.1, XCode 9.1 on High Sierra

### ISSUE THREAD

**Issue by sunrayc** [calabash/calabash-ios#1345]
Hi, 

I am unable to run calabash-ios on real device after upgrading to iOS 11.1 on iPad and to High Sierra with XCode 9.1 on the Mac.

I get the following error when i start the calabash-ios console and give start_test_server_in_background

Could not install $HOME/.rvm/gems/ruby-2.4.0/gems/run_loop-2.6.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app.  iOSDeviceManager says:

Error getting device with ID xxxx : Error Domain=com.facebook.FBControlCore Code=0 "Failed to load device console entries" UserInfo={NSLocalizedDescription=Failed to load device console entries}

	install <app-path>
		-d,--device-id	<device-identifier>	iOS Simulator GUID or 40-digit physical device ID
		-u,--update-app	<should-update-app> [OPTIONAL] 	When true, will reinstall the app if the device contains an older version than the bundle specified	DEFAULT=1
		-p,--profile-path	<profile-path> [OPTIONAL] 	Path to provisioning profile
		-c,--codesign-identity	<codesign-identifier> [OPTIONAL] 	Identity used to codesign app bundle [device only]. Deprecated - should use profile path.	DEFAULT=
		-i,--resources-path	<resources-path> [OPTIONAL] 	Path to resources (executables) to inject into app directory. A list of colon separated files may be specified.

	from $HOME/.rvm/gems/ruby-2.4.0/gems/run_loop-2.6.1/lib/run_loop/device_agent/ios_device_manager.rb:149:in `launch'
	from $HOME/.rvm/gems/ruby-2.4.0/gems/run_loop-2.6.1/lib/run_loop/device_agent/client.rb:1378:in `launch_cbx_runner'
	from $HOME/.rvm/gems/ruby-2.4.0/gems/run_loop-2.6.1/lib/run_loop/device_agent/client.rb:292:in `launch'
	from $HOME/.rvm/gems/ruby-2.4.0/gems/run_loop-2.6.1/lib/run_loop/device_agent/client.rb:167:in `run'
	from $HOME/.rvm/gems/ruby-2.4.0/gems/run_loop-2.6.1/lib/run_loop.rb:113:in `run'
	from $HOME/.rvm/gems/ruby-2.4.0/gems/calabash-cucumber-0.21.2/lib/calabash-cucumber/launcher.rb:414:in `block in new_run_loop'
	from $HOME/.rvm/gems/ruby-2.4.0/gems/calabash-cucumber-0.21.2/lib/calabash-cucumber/launcher.rb:412:in `times'
	from $HOME/.rvm/gems/ruby-2.4.0/gems/calabash-cucumber-0.21.2/lib/calabash-cucumber/launcher.rb:412:in `new_run_loop'
	from $HOME/.rvm/gems/ruby-2.4.0/gems/calabash-cucumber-0.21.2/lib/calabash-cucumber/launcher.rb:365:in `relaunch'
	from $HOME/.rvm/gems/ruby-2.4.0/gems/calabash-cucumber-0.21.2/lib/calabash-cucumber/core.rb:1567:in `start_test_server_in_background'
	from (irb):1
	from $HOME/.rvm/rubies/ruby-2.4.0/bin/irb:11:in `<main>'

**Comment by jmoody** [comment]
Thank you for reporting.

This is a known issue.

I am working on fixing this problem.

The work around is to roll back to Xcode 9.0.

**Comment by sunrayc** [comment]
Hi Joshua,

Thanks very much!! I tried with XCode 9.0.1 also, which had the same issue. So, Should I just go back to XCode 9.0. Wanted to confirm.

**Comment by sunrayc** [comment]
Hi @jmoody 

Now, I am getting timeout error when using XCode 9.0 version. 

_Note: I have the Xcode 9.1 version also. I downloaded Xcode 9.0 version and copied it Applications as Xcode_90 and use sudo xcode-select to set the Xcode version._

Calabash-ios version 0.21.1

calabash-ios 0.21.1> start_test_server_in_background
SHELL: xcrun simctl list devices --json
SHELL: xcrun instruments -s devices
DEBUG: HTTP: get http://10.59.220.150:27753/1.0/health {:retries=>1, :timeout=>0.5}
DEBUG: HTTP: get http://10.59.220.150:27753/1.0/health {:retries=>1, :timeout=>0.5}
DEBUG: Waiting for DeviceAgent to launch...
SHELL: $HOME/.rvm/gems/ruby-2.3.4/gems/run_loop-2.6.1/lib/run_loop/device_agent/bin/iOSDeviceManager install $HOME/.rvm/gems/ruby-2.3.4/gems/run_loop-2.6.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app --device-id xxxx --codesign-identity xxxxx
RunLoop::Shell::TimeoutError: 
Timed out after 120.01 seconds executing

$HOME/.rvm/gems/ruby-2.3.4/gems/run_loop-2.6.1/lib/run_loop/device_agent/bin/iOSDeviceManager install $HOME/.rvm/gems/ruby-2.3.4/gems/run_loop-2.6.1/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app --device-id xxxx --codesign-identity xxxxx

with a timeout of 120

	from $HOME/.rvm/gems/ruby-2.3.4/gems/run_loop-2.6.1/lib/run_loop/shell.rb:104:in `run_shell_command'
	from $HOME/.rvm/gems/ruby-2.3.4/gems/run_loop-2.6.1/lib/run_loop/device_agent/ios_device_manager.rb:146:in `launch'
	from $HOME/.rvm/gems/ruby-2.3.4/gems/run_loop-2.6.1/lib/run_loop/device_agent/client.rb:1378:in `launch_cbx_runner'
	from $HOME/.rvm/gems/ruby-2.3.4/gems/run_loop-2.6.1/lib/run_loop/device_agent/client.rb:292:in `launch'
	from $HOME/.rvm/gems/ruby-2.3.4/gems/run_loop-2.6.1/lib/run_loop/device_agent/client.rb:167:in `run'
	from $HOME/.rvm/gems/ruby-2.3.4/gems/run_loop-2.6.1/lib/run_loop.rb:113:in `run'
	from $HOME/.rvm/gems/ruby-2.3.4/gems/calabash-cucumber-0.21.1/lib/calabash-cucumber/launcher.rb:414:in `block in new_run_loop'
	from $HOME/.rvm/gems/ruby-2.3.4/gems/calabash-cucumber-0.21.1/lib/calabash-cucumber/launcher.rb:412:in `times'
	from $HOME/.rvm/gems/ruby-2.3.4/gems/calabash-cucumber-0.21.1/lib/calabash-cucumber/launcher.rb:412:in `new_run_loop'
	from $HOME/.rvm/gems/ruby-2.3.4/gems/calabash-cucumber-0.21.1/lib/calabash-cucumber/launcher.rb:365:in `relaunch'
	from $HOME/.rvm/gems/ruby-2.3.4/gems/calabash-cucumber-0.21.1/lib/calabash-cucumber/core.rb:1567:in `start_test_server_in_background'
	from (irb):1
	from $HOME/.rvm/rubies/ruby-2.3.4/bin/irb:11:in `<main>'

**Comment by paulbreilwork** [comment]
Hi @jmoody
I have the same error than @sunrayc with Xcode 9.1
Thank you, for your answer , I will return to Xcode 9.0

**Comment by sunrayc** [comment]
@jmoody 
Thanks so much!! Its working now. 
I tested with iOS 11.1.1 also. 

Note to other users: I had to restart my mac after installing the run-loop 2.6.2.

**Comment by sunrayc** [comment]
@jmoody 

I am now having issue with calabash-ios after upgrading to iOS 11.2. It's unable to install the DeviceAgent app. I see the below error.

```
Timed out after 120.07 seconds executing

$HOME/.rvm/gems/ruby-2.4.0/gems/run_loop-2.6.2/lib/run_loop/device_agent/bin/iOSDeviceManager install $HOME/.rvm/gems/ruby-2.4.0/gems/run_loop-2.6.2/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app --device-id xxx --codesign-identity xxxx
 
 with a timeout of 120
  (RunLoop::Shell::TimeoutError)
```

Please suggest.

Thanks!!
