### ISSUE TITLE
calabash-ios unable to install DeviceAgent-Runner App on iOS 11.2 with MacOS High Sierra

### ISSUE THREAD

**Issue by sunrayc** [calabash/calabash-ios#1358]
Hi,

I am unable to run calabash-ios on real device after upgrading to iOS 11.2 on iPad and to High Sierra with XCode 9.1 on the Mac.

I get the following error when i start the calabash-ios console and give start_test_server_in_background

```
calabash-ios 0.21.2> start_test_server_in_background
SHELL: xcrun simctl list devices --json
SHELL: xcrun instruments -s devices
DEBUG: HTTP: get http://xxx.xxx.xxx.xxx:27753/1.0/health {:retries=>1, :timeout=>0.5}
DEBUG: HTTP: get http://xxx.xxx.xxx.xxx:27753/1.0/health {:retries=>1, :timeout=>0.5}
DEBUG: Waiting for DeviceAgent to launch...
SHELL: $HOME/.rvm/gems/ruby-2.4.0/gems/run_loop-2.6.2/lib/run_loop/device_agent/bin/iOSDeviceManager install $HOME/.rvm/gems/ruby-2.4.0/gems/run_loop-2.6.2/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app --device-id xxx --codesign-identity xxxx
RunLoop::Shell::TimeoutError: 
Timed out after 120.04 seconds executing

$HOME/.rvm/gems/ruby-2.4.0/gems/run_loop-2.6.2/lib/run_loop/device_agent/bin/iOSDeviceManager install $HOME/.rvm/gems/ruby-2.4.0/gems/run_loop-2.6.2/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app --device-id xxx --codesign-identity xxxx
 
 with a timeout of 120
	from $HOME/.rvm/gems/ruby-2.4.0/gems/run_loop-2.6.2/lib/run_loop/shell.rb:104:in `run_shell_command'
	from $HOME/.rvm/gems/ruby-2.4.0/gems/run_loop-2.6.2/lib/run_loop/device_agent/ios_device_manager.rb:146:in `launch'
	from $HOME/.rvm/gems/ruby-2.4.0/gems/run_loop-2.6.2/lib/run_loop/device_agent/client.rb:1378:in `launch_cbx_runner'
	from $HOME/.rvm/gems/ruby-2.4.0/gems/run_loop-2.6.2/lib/run_loop/device_agent/client.rb:292:in `launch'
	from $HOME/.rvm/gems/ruby-2.4.0/gems/run_loop-2.6.2/lib/run_loop/device_agent/client.rb:167:in `run'
	from $HOME/.rvm/gems/ruby-2.4.0/gems/run_loop-2.6.2/lib/run_loop.rb:113:in `run'
	from $HOME/.rvm/gems/ruby-2.4.0/gems/calabash-cucumber-0.21.2/lib/calabash-cucumber/launcher.rb:414:in `block in new_run_loop'
	from $HOME/.rvm/gems/ruby-2.4.0/gems/calabash-cucumber-0.21.2/lib/calabash-cucumber/launcher.rb:412:in `times'
	from $HOME/.rvm/gems/ruby-2.4.0/gems/calabash-cucumber-0.21.2/lib/calabash-cucumber/launcher.rb:412:in `new_run_loop'
	from $HOME/.rvm/gems/ruby-2.4.0/gems/calabash-cucumber-0.21.2/lib/calabash-cucumber/launcher.rb:365:in `relaunch'
	from $HOME/.rvm/gems/ruby-2.4.0/gems/calabash-cucumber-0.21.2/lib/calabash-cucumber/core.rb:1567:in `start_test_server_in_background'
	from (irb):1
	from $HOME/.rvm/rubies/ruby-2.4.0/bin/irb:11:in `<main>'
```
Please suggest.

Thanks!!

**Comment by jmoody** [comment]
Your device is probably not ready for development.

Open Xcode > Windows > Device and Simulator management window.

Make sure your device appears with no warnings.

It is also possible that you have not updated your active Xcode.

```
$ xcrun xcodebuild -version
```

Your Xcode must be at least 9.2 to support iOS 11.2.

**Comment by sunrayc** [comment]
@jmoody 
It works with Xcode 9.2. Thanks very much!!
