### ISSUE TITLE
Can't run tests on device (0.11.0, iOS 8.0)

### ISSUE THREAD

**Issue by ldiqual** [calabash/calabash-ios#543]
With the app installed on the device (iPhone 5, iOS 8.0), I run the tests and get the following error:

```
- Running calabash tests

    cd /Users/ldiqual/Company/Product/tests &&
    APP_BUNDLE_PATH=/Users/ldiqual/Company/Product/builds/Company-Debug.xcarchive/Products/Applications/Company.app
    DEVICE_ENDPOINT=http://192.168.1.20:37265
    IPA_PATH="/Users/ldiqual/Company/Product/builds/Company-Debug.ipa"
    
    DEVICE_TARGET='device'
    SCREENSHOT_PATH=/Users/ldiqual/Company/Product/tests/screenshots/ios
    RESET_BETWEEN_SCENARIOS=1
        cucumber -v
            --profile ios
            -f pretty
            -f Company::Html -o /Users/ldiqual/Company/Product/builds/logs/ios.calabash.html
            -f Boo::Lean -o /Users/ldiqual/Company/Product/builds/logs/ios.calabash.txt
            features/A01_sign_up.feature                    
Code:
  * features/ios/support/env.rb
  * features/ios/support/01_launch.rb
  * features/ios/support/02_pre_stop_hooks.rb
  * features/ios/support/html_formatter.rb
  * features/ios/support/jenkins_formatter.rb
  * features/ios/step_definitions/steps.rb
  * features/step_definitions/steps.rb

Features:
  * features/A01_sign_up.feature
Parsing feature files took 0m0.005s

Using the ios profile...
@signup
Feature: A01 Sign Up

  Scenario: A01 Sign Up              # features/A01_sign_up.feature:4
  Interrupted system call - /var/folders/6y/lmxm7bmd4_qcbbqqnln21m_80000gn/T/run_loop20141006-69481-piuuaa/repl-cmd.pipe (Errno::EINTR)
  /Users/ldiqual/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/run_loop-1.0.8/lib/run_loop/core.rb:209:in `initialize'
  /Users/ldiqual/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/run_loop-1.0.8/lib/run_loop/core.rb:209:in `open'
  /Users/ldiqual/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/run_loop-1.0.8/lib/run_loop/core.rb:209:in `run_with_options'
  /Users/ldiqual/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/run_loop-1.0.8/lib/run_loop/core.rb:687:in `run'
  /Users/ldiqual/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.11.0/lib/calabash-cucumber/launcher.rb:724:in `block in new_run_loop'
  /Users/ldiqual/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.11.0/lib/calabash-cucumber/launcher.rb:722:in `times'
  /Users/ldiqual/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.11.0/lib/calabash-cucumber/launcher.rb:722:in `new_run_loop'
  /Users/ldiqual/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.11.0/lib/calabash-cucumber/launcher.rb:597:in `relaunch'
  /Users/ldiqual/Expensify/YAPL/tests/features/ios/support/01_launch.rb:45:in `Before'
    Given I am on the intro screen   # features/ios/step_definitions/steps.rb:79
      IPA was installed successfuly
    Then I tap Sign In               # features/ios/step_definitions/steps.rb:1
    Then I Sign Up                   # features/ios/step_definitions/steps.rb:6
    Then I tap button with text "Ok" # features/ios/step_definitions/steps.rb:117
    Given I am on the menu screen    # features/ios/step_definitions/steps.rb:89
```

**Comment by mokagio** [comment]
Hello, I'm experiencing the same issue... :/

@ShuheiOno what is the NO_PROXY option you're referring to? I seem unable to find it in the documentation. 

Thanks :beers:

**Comment by jmoody** [comment]
@ShuheiOno 

There is `NO_PROXY` variable in the current version of Calabash.  There used be such a variable, but it was removed some time ago.

This would explain @mokagio  can not find docs for it.

It is possible another gem that calabash depends on, like httpclient respects a `NO_PROXY` environment variable.   And it is also possible that I have somehow missed this variable in Calabash.

**Comment by mokagio** [comment]
@jmoody ok thanks :+1:

**Comment by izhilenkov** [comment]
I have same problems... I build my app in Xamarin as debug for iPhone and i set package name and use it as bundle_id... So... When I start calabash-ios console (BUNDLE_ID=com.myapp.app DEVICE_TARGET=UIID DEVICE_ENDPOINT=http://192.168.15.30:37:37265 calabash-ios console) and type "start_test_server_in_background" I catch a error
```ruby
irb(main):001:0> start_test_server_in_background
Unable to start. Make sure you've set APP_BUNDLE_PATH to a build supported by this simulator version
Calabash::Cucumber::Launcher::StartError: Calabash::Cucumber::Launcher::StartError: Time out waiting for UIAutomation run-loop execution expired. 
 Logfile /var/folders/86/9sv478ns69b9gjd3h1b7tqh40000gp/T/run_loop20150408-29168-1f0cpcn/run_loop.out 

 2015-04-08 09:39:33.264 instruments[29270:166995] WebKit Threading Violation - initial use of WebKit from a secondary thread.
Instruments Usage Error : Specified target process is invalid: com.efea.app
instruments, version 6.2 (56718)
usage: instruments [-t template] [-D document] [-l timeLimit] [-i #] [-w device] [[-p pid] | [application [-e variable value] [argument ...]]]


	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.13.0/lib/calabash-cucumber/launcher.rb:772:in `new_run_loop'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.13.0/lib/calabash-cucumber/launcher.rb:630:in `relaunch'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.13.0/lib/calabash-cucumber/core.rb:849:in `start_test_server_in_background'
	from (irb):1
	from /usr/bin/irb:12:in `<main>'
```
but query are work fine and find a elements...
I try start test server at iOS7 and iOS8, and I double checked for Enable UI Automation...

**Comment by ShuheiOno** [comment]
@mokagio
I'm so sorry for my late reply.

I meant `NO_PROXY` as a environment variable.
I add the following code to the `.bashrc` file.(I use bash)
`export NO_PROXY=xx.xx.xx.xx` ( xx.xx.xx.xx is iPhone's IP address )

**Comment by mokagio** [comment]
Thanks @ShuheiOne, no worries :)



—
Gio

**Comment by jmoody** [comment]
Outdated; closing.
