### ISSUE TITLE
".GlobalPreferences.plist not readable! (IOError)" error when executing 'calabash-ios sim locale en fi_FI' (0.11.1, Xcode 5.1.1, iOS7.1)

### ISSUE THREAD

**Issue by JaniJegoroff** [calabash/calabash-ios#564]
**Given** `Calabash version 0.11.1` should be backward compatible with Xcode 5.1.1
**Then** it should be possible to use `calabash-ios sim locale` command to set current locale in 7.1 simulator

**Environment:**
- Calabash 0.11.1
- run_loop 1.0.9
- Xcode 5.1.1
- 'iPad - Simulator - iOS 7.1'

**Steps to reproduce:**
1. Build app to `iPad - Simulator - iOS 7.1`
2. Launch `calabash-ios console`
3. Execute: `start_test_server_in_background`
4. Execute: `calabash-ios sim locale en fi_FI`

**Expected result:**
4. Command is executed without errors

**Actual result:**
4. Error is occurred: `calabash-cucumber-0.11.1/scripts/data/.GlobalPreferences.plist not readable! (IOError)`

**Console trace:**
```
janis-mbp:myApp janijegoroff$ DEBUG=1 APP_BUNDLE_PATH=build/Calabash-iphonesimulator/myApp.app DEVICE_TARGET='iPad - Simulator - iOS 7.1' calabash-ios console
Running irb...
irb(main):001:0> start_test_server_in_background

INFO: Using uia strategy: 'preferences'
Preparation took 0.556913 seconds
{
                        :app => "/Users/janijegoroff/myApp/build/Calabash-iphonesimulator/myApp.app",
                       :args => [],
    :bundle_dir_or_bundle_id => "/Users/janijegoroff/myApp/build/Calabash-iphonesimulator/myApp.app",
                  :bundle_id => "myBundleId.myApp",
                     :device => "iphone",
              :device_target => "iPad - Simulator - iOS 7.1",
              :launch_method => :instruments,
             :launch_retries => 5,
                   :log_file => "/var/folders/02/2thphdms7yqcby08qk4vbbf80000gn/T/run_loop20141020-23727-13uc2l3/run_loop.out",
                  :no_launch => false,
                    :no_stop => false,
                      :reset => false,
                :results_dir => "/var/folders/02/2thphdms7yqcby08qk4vbbf80000gn/T/run_loop20141020-23727-13uc2l3",
          :results_dir_trace => "/var/folders/02/2thphdms7yqcby08qk4vbbf80000gn/T/run_loop20141020-23727-13uc2l3/trace",
                     :script => "/var/folders/02/2thphdms7yqcby08qk4vbbf80000gn/T/run_loop20141020-23727-13uc2l3/_run_loop.js",
                :sdk_version => nil,
                       :udid => "iPad - Simulator - iOS 7.1",
               :uia_strategy => :preferences,
                      :xcode => "5.1.1",
                 :xcode_path => "/Applications/Xcode511/Xcode.app/Contents/Developer"
}

### Starting on iPad - Simulator - iOS 7.1 App: /Users/janijegoroff/myApp/build/Calabash-iphonesimulator/myApp.app ###
2014-10-20 14:01:19 +0100 xcrun instruments -w "iPad - Simulator - iOS 7.1" -D "/var/folders/02/2thphdms7yqcby08qk4vbbf80000gn/T/run_loop20141020-23727-13uc2l3/trace" -t "/Applications/Xcode511/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.bundle/Contents/Resources/Automation.tracetemplate" "/Users/janijegoroff/myApp/build/Calabash-iphonesimulator/myApp.app" -e UIARESULTSPATH /var/folders/02/2thphdms7yqcby08qk4vbbf80000gn/T/run_loop20141020-23727-13uc2l3 -e UIASCRIPT /var/folders/02/2thphdms7yqcby08qk4vbbf80000gn/T/run_loop20141020-23727-13uc2l3/_run_loop.js  &> /var/folders/02/2thphdms7yqcby08qk4vbbf80000gn/T/run_loop20141020-23727-13uc2l3/run_loop.out
Launching took 7.255934 seconds
Calabash::Cucumber::Launcher: Launch Method instruments
Log file: /var/folders/02/2thphdms7yqcby08qk4vbbf80000gn/T/run_loop20141020-23727-13uc2l3/run_loop.out
irb(main):002:0> `calabash-ios sim locale en fi_FI`
/Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/CFPropertyList-2.2.8/lib/cfpropertylist/rbCFPropertyList.rb:325:in `load': File /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/calabash-cucumber-0.11.1/scripts/data/.GlobalPreferences.plist not readable! (IOError)
	from /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/CFPropertyList-2.2.8/lib/cfpropertylist/rbCFPropertyList.rb:248:in `initialize'
	from /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/calabash-cucumber-0.11.1/bin/calabash-ios-sim.rb:66:in `new'
	from /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/calabash-cucumber-0.11.1/bin/calabash-ios-sim.rb:66:in `calabash_sim_locale'
	from /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/calabash-cucumber-0.11.1/bin/calabash-ios:73:in `<top (required)>'
	from /Users/janijegoroff/.rbenv/versions/2.1.2/bin/calabash-ios:23:in `load'
	from /Users/janijegoroff/.rbenv/versions/2.1.2/bin/calabash-ios:23:in `<main>'
""
irb(main):003:0>
```

**Comment by yakovsh** [comment]
As a workaround, you can use the options[:args] on hooks with "-AppleLanguges" as per issue #363
