### ISSUE TITLE
run-loop + jruby occasionally throws a bad file descriptor exception in plist_buddy

### ISSUE THREAD

**Issue by chingc** [calabash/calabash-ios#568]
I'm using calabash 0.11.1 and occasionally my tests would fail before they even start with the following error:

```
Bad file descriptor - Bad file descriptor (Errno::EBADF)
org/jruby/RubyIO.java:2063:in `close'
org/jruby/RubyIO.java:4397:in `popen3'
/usr/local/rvm/rubies/jruby-1.7.8/lib/ruby/1.9/open3.rb:74:in `popen3'
/usr/local/rvm/gems/jruby-1.7.8@hyprios/gems/run_loop-1.0.9/lib/run_loop/plist_buddy.rb:95:in `execute_plist_cmd'
/usr/local/rvm/gems/jruby-1.7.8@hyprios/gems/run_loop-1.0.9/lib/run_loop/plist_buddy.rb:21:in `plist_read'
/usr/local/rvm/gems/jruby-1.7.8@hyprios/gems/run_loop-1.0.9/lib/run_loop/plist_buddy.rb:36:in `plist_key_exists?'
/usr/local/rvm/gems/jruby-1.7.8@hyprios/gems/run_loop-1.0.9/lib/run_loop/plist_buddy.rb:61:in `plist_set'
/usr/local/rvm/gems/jruby-1.7.8@hyprios/gems/run_loop-1.0.9/lib/run_loop/sim_control.rb:723:in `enable_accessibility_in_sim_data_dir'
org/jruby/RubyHash.java:1338:in `each'
org/jruby/RubyEnumerable.java:732:in `map'
/usr/local/rvm/gems/jruby-1.7.8@hyprios/gems/run_loop-1.0.9/lib/run_loop/sim_control.rb:722:in `enable_accessibility_in_sim_data_dir'
/usr/local/rvm/gems/jruby-1.7.8@hyprios/gems/run_loop-1.0.9/lib/run_loop/sim_control.rb:292:in `enable_accessibility_on_sims'
org/jruby/RubyArray.java:2413:in `map'
/usr/local/rvm/gems/jruby-1.7.8@hyprios/gems/run_loop-1.0.9/lib/run_loop/sim_control.rb:291:in `enable_accessibility_on_sims'
/usr/local/rvm/gems/jruby-1.7.8@hyprios/gems/run_loop-1.0.9/lib/run_loop/core.rb:95:in `run_with_options'
/usr/local/rvm/gems/jruby-1.7.8@hyprios/gems/run_loop-1.0.9/lib/run_loop/core.rb:679:in `run'
/usr/local/rvm/gems/jruby-1.7.8@hyprios/gems/calabash-cucumber-0.11.1/lib/calabash-cucumber/launcher.rb:724:in `new_run_loop'
org/jruby/RubyFixnum.java:275:in `times'
/usr/local/rvm/gems/jruby-1.7.8@hyprios/gems/calabash-cucumber-0.11.1/lib/calabash-cucumber/launcher.rb:722:in `new_run_loop'
/usr/local/rvm/gems/jruby-1.7.8@hyprios/gems/calabash-cucumber-0.11.1/lib/calabash-cucumber/launcher.rb:597:in `relaunch'
/Users/teamcity/tmp/iOS-Framework/Code/HyprMX-IntegrationTesting/features/support/01_launch.rb:29:in `Before'
```

Sometimes the very same test will pass, other times it will fail with this error.

I've eliminated hardware as a possible issue and my tests run solidly with Xcode 5's simulator on the very same machine.  I've also tried the latest jruby thinking it might be some kind of incompatibility with the version I'm using but it had no effect.

Any insight into what could be causing this would be appreciated.

**Comment by jmoody** [comment]
Jruby is not supported.  It _might_ be supported in Calabash 2.0, but this is not a high priority for us.  If you want jruby support, we'd be more than happy to entertain pull requests.
