### ISSUE TITLE
Intermittent 'Could not parse response '';' error when executing tap_mark command

### ISSUE THREAD

**Issue by JaniJegoroff** [calabash/calabash-ios#600]
This is the new issue for intermitted **RuntimeError: Could not parse response ''; the app has probably crashed** error when executing `tap_mark` command. Issue was first referenced in the discussion: https://github.com/calabash/calabash-ios/issues/566

Based on my experience issue happens more often in the iPhone 6 simulator than in iPad Retina simulator.

**Environment**
Xcode 6.1
Calabash 0.11.3
run_loop 1.0.9
8.1 simulators

**Steps to reproduce:**
1. Build your app to `iPhone 6 (8.1 Simulator)`
2. Launch `DEBUG=1 DEBUG_HTTP=1 DEVICE_TARGET='iPhone 6 (8.1 Simulator)' calabash-ios console`
3. Execute: `start_test_server_in_background`
4. Execute: `tap_mark('<your-text>')`

**curl:**

```
Janis-MacBook-Pro:~ janijegoroff$ curl http://localhost:37265/version
{"app_version":"1.4","outcome":"SUCCESS","app_id":"myBundle","simulator_device":"iPad","version":"0.11.3","app_name":"myApp","iphone_app_emulated_on_ipad":false,"4inch":false,"git":{"remote_origin":"git@github.com:calabash\/calabash-ios-server.git","branch":"master","revision":"40c6245"},"screen_dimensions":{"scale":2,"width":1536,"sample":1,"height":2048},"iOS_version":"8.1","system":"x86_64","simulator":""}
```

**Debug trace:**

```
Janis-MacBook-Pro:myApp janijegoroff$ DEBUG=1 DEBUG_HTTP=1 DEVICE_TARGET='iPhone 6 (8.1 Simulator)' calabash-ios console
Running irb...
irb(main):001:0> start_test_server_in_background

INFO: Using uia strategy: 'preferences'
Preparation took 2.502783 seconds
{
                        :app => "/Users/janijegoroff/Library/Developer/Xcode/DerivedData/myApp-civuqgdjemtasdaqyhpsrgakmnyv/Build/Products/Calabash-iphonesimulator/myApp.app",
                       :args => [],
    :bundle_dir_or_bundle_id => "/Users/janijegoroff/Library/Developer/Xcode/DerivedData/myApp-civuqgdjemtasdaqyhpsrgakmnyv/Build/Products/Calabash-iphonesimulator/myApp.app",
                  :bundle_id => "myBundle",
                     :device => "iphone",
              :device_target => "iPhone 6 (8.1 Simulator)",
              :launch_method => :instruments,
             :launch_retries => 5,
                   :log_file => "/var/folders/02/2thphdms7yqcby08qk4vbbf80000gn/T/run_loop20141106-18284-1avuy9x/run_loop.out",
                  :no_launch => false,
                    :no_stop => false,
                      :reset => false,
                :results_dir => "/var/folders/02/2thphdms7yqcby08qk4vbbf80000gn/T/run_loop20141106-18284-1avuy9x",
          :results_dir_trace => "/var/folders/02/2thphdms7yqcby08qk4vbbf80000gn/T/run_loop20141106-18284-1avuy9x/trace",
                     :script => "/var/folders/02/2thphdms7yqcby08qk4vbbf80000gn/T/run_loop20141106-18284-1avuy9x/_run_loop.js",
                :sdk_version => nil,
                       :udid => "iPhone 6 (8.1 Simulator)",
               :uia_strategy => :preferences,
                      :xcode => "6.1",
                 :xcode_path => "/Applications/Xcode61/Xcode.app/Contents/Developer"
}

### Starting on iPhone 6 (8.1 Simulator) App: /Users/janijegoroff/Library/Developer/Xcode/DerivedData/myApp-civuqgdjemtasdaqyhpsrgakmnyv/Build/Products/Calabash-iphonesimulator/myApp.app ###
2014-11-06 13:51:11 +0000 xcrun instruments -w "iPhone 6 (8.1 Simulator)" -D "/var/folders/02/2thphdms7yqcby08qk4vbbf80000gn/T/run_loop20141106-18284-1avuy9x/trace" -t "Automation" "/Users/janijegoroff/Library/Developer/Xcode/DerivedData/myApp-civuqgdjemtasdaqyhpsrgakmnyv/Build/Products/Calabash-iphonesimulator/myApp.app" -e UIARESULTSPATH /var/folders/02/2thphdms7yqcby08qk4vbbf80000gn/T/run_loop20141106-18284-1avuy9x -e UIASCRIPT /var/folders/02/2thphdms7yqcby08qk4vbbf80000gn/T/run_loop20141106-18284-1avuy9x/_run_loop.js  &> /var/folders/02/2thphdms7yqcby08qk4vbbf80000gn/T/run_loop20141106-18284-1avuy9x/run_loop.out
Launching took 5.528413 seconds
Calabash::Cucumber::Launcher: Launch Method instruments
Log file: /var/folders/02/2thphdms7yqcby08qk4vbbf80000gn/T/run_loop20141106-18284-1avuy9x/run_loop.out
irb(main):002:0> tap_mark 'Notification'
= Request

! CONNECT TO localhost:37265
! CONNECTION ESTABLISHED
POST /map HTTP/1.1
Content-Type: application/x-www-form-urlencoded
User-Agent: HTTPClient/1.0 (2.3.4.1, ruby 2.1.2 (2014-05-08))
Accept: */*
Date: Thu, 06 Nov 2014 13:51:25 GMT
Content-Length: 89
Host: localhost:37265

{"query":"view marked:'Notification'","operation":{"method_name":"query","arguments":[]}}

= Response

HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Max-Age: 3000
Accept-Ranges: bytes
Date: Thu, 06 Nov 2014 13:51:25 GMT
Content-Length: 478
Access-Control-Allow-Origin: *

{"status_bar_orientation":"down","results":[{"alpha":1,"enabled":true,"id":null,"frame":{"y":8,"x":16,"width":351,"height":27.5},"class":"UITableViewLabel","rect":{"y":328,"height":27.5,"center_y":341.75,"x":16,"center_x":191.5,"width":351},"label":"Notification","text":"Notification","description":"<UITableViewLabel: 0x7fdc615e9700; frame = (16 8; 351 27.5); text = 'Notification'; userInteractionEnabled = NO; layer = <_UILabelLayer: 0x7fdc615e8610>>"}],"outcome":"SUCCESS"}Sending UIA command
uia.tapOffset('{:x 191.5, :y 341.75}')
= Request

POST /uia HTTP/1.1
Content-Type: application/x-www-form-urlencoded
User-Agent: HTTPClient/1.0 (2.3.4.1, ruby 2.1.2 (2014-05-08))
Accept: */*
Date: Thu, 06 Nov 2014 13:51:25 GMT
Content-Length: 52
Host: localhost:37265

{"command":"uia.tapOffset('{:x 191.5, :y 341.75}')"}

= Response

HTTP/1.1 200 OK
Date: Thu, 06 Nov 2014 13:51:25 GMT
Accept-Ranges: bytes
Transfer-Encoding: chunked

! CONNECTION CLOSED
RuntimeError: Could not parse response ''; the app has probably crashed
    from /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/calabash-cucumber-0.11.3/lib/calabash-cucumber/uia.rb:33:in `rescue in uia'
    from /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/calabash-cucumber-0.11.3/lib/calabash-cucumber/uia.rb:30:in `uia'
    from /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/calabash-cucumber-0.11.3/lib/calabash-cucumber/uia.rb:344:in `uia_handle_command'
    from /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/calabash-cucumber-0.11.3/lib/calabash-cucumber/uia.rb:144:in `uia_tap_offset'
    from /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/calabash-cucumber-0.11.3/lib/calabash-cucumber/actions/instruments_actions.rb:93:in `query_action'
    from /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/calabash-cucumber-0.11.3/lib/calabash-cucumber/actions/instruments_actions.rb:15:in `touch'
    from /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/calabash-cucumber-0.11.3/lib/calabash-cucumber/core.rb:1095:in `query_action_with_options'
    from /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/calabash-cucumber-0.11.3/lib/calabash-cucumber/core.rb:174:in `touch'
    from /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/calabash-cucumber-0.11.3/lib/calabash-cucumber/core.rb:926:in `tap_mark'
    from (irb):2
    from /Users/janijegoroff/.rbenv/versions/2.1.2/bin/irb:11:in `<main>'
irb(main):003:0>
```

**run_loop.out:**

```
Janis-MacBook-Pro:myApp janijegoroff$ cat /var/folders/02/2thphdms7yqcby08qk4vbbf80000gn/T/run_loop20141106-18284-1avuy9x/run_loop.out
Waiting for device to boot...
2014-11-06 13:51:17 +0000 Default: OUTPUT_JSON:
{"status":"success","value":true,"index":0}
END_OUTPUT
2014-11-06 13:51:17 +0000 Default: ***********************************************************
2014-11-06 13:51:25 +0000 Default: index 0 is command: uia.tapOffset('{:x 191.5, :y 341.75}')
2014-11-06 13:51:25 +0000 Debug: target.tapWithOptions({x:"191.5", y:"341.75"}, )
2014-11-06 13:51:25 +0000 Default: Success: true
2014-11-06 13:51:25 +0000 Default: Write result...
2014-11-06 13:51:25 +0000 Default: Check successful storage...
2014-11-06 13:51:25 +0000 Default: Storage succeeded: 0
2014-11-06 13:51:28 +0000 Fail: The target application appears to have died
Instruments Trace Complete (Duration : 15.833581s; Output : /var/folders/02/2thphdms7yqcby08qk4vbbf80000gn/T/run_loop20141106-18284-1avuy9x/trace.trace)
Janis-MacBook-Pro:myApp janijegoroff$
```

**Comment by praveenraj1987** [comment]
I see this issue on xcode 6.2, ios 8.2.
Could not parse response ''; the app has probably crashed (RuntimeError).

**Comment by fpena** [comment]
This issue still happens using XCode 6.3.2 and iOS 8.3.
