### ISSUE TITLE
Unstable accept of System alerts with 0.11.5.pre3

### ISSUE THREAD

**Issue by nfrydenholm** [calabash/calabash-ios#636]
Disclaimer - I'm not sure if the bug actually has to do with system alerts, or if it's just how the symptom shows up when I run the test.

I use reset-between-scenarios, so for each scenario, I get the dialog to accept the location each time, and it's like flipping a coin whether it is closed/accepted (and the scenario can continue) or not :-)

It has not been an issue with 0.11.4.pre1, which is I used prior to the upgrade.

It doesn't matter which uia_strategy I use.

Here is the output when I run with both DEBUG and DEBUG_HTTP

Let me know if output from other logfiles can help you, and I'll try to find it.

```
INFO: Using uia strategy: 'host'
Preparation took 0.017372 seconds
Simulator instruction set 'i386' is compatible with ["i386"]
{
                        :app => "/Users/nfrydenholm/Work/dba-app-iOS/Build/Products/Debug-iphonesimulator/dba.app",
                       :args => [],
    :bundle_dir_or_bundle_id => "/Users/nfrydenholm/Work/dba-app-iOS/Build/Products/Debug-iphonesimulator/dba.app",
                  :bundle_id => "ecg.dk.dba.testapp",
                     :device => "iphone",
              :device_target => "simulator",
              :launch_method => :instruments,
             :launch_retries => 5,
                   :log_file => "/var/folders/36/ws5sx46n747c9dwl9x6p06s8390ykh/T/run_loop20141203-18371-1mhw7or/run_loop.out",
                  :no_launch => false,
                    :no_stop => false,
           :privacy_settings => {
        :photos => {
            :allow => true
        }
    },
                      :reset => true,
                :results_dir => "/var/folders/36/ws5sx46n747c9dwl9x6p06s8390ykh/T/run_loop20141203-18371-1mhw7or",
          :results_dir_trace => "/var/folders/36/ws5sx46n747c9dwl9x6p06s8390ykh/T/run_loop20141203-18371-1mhw7or/trace",
                     :script => "/var/folders/36/ws5sx46n747c9dwl9x6p06s8390ykh/T/run_loop20141203-18371-1mhw7or/_run_loop.js",
                :sdk_version => nil,
                       :udid => "iPhone 5 (8.0 Simulator)",
               :uia_strategy => :host,
                      :xcode => "6.0.1",
                 :xcode_path => "/Applications/Xcode.app/Contents/Developer"
}

### Starting on simulator App: /Users/nfrydenholm/Work/dba-app-iOS/Build/Products/Debug-iphonesimulator/dba.app ###
2014-12-03 08:23:46 +0100 xcrun instruments -w "iPhone 5 (8.0 Simulator)" -D "/var/folders/36/ws5sx46n747c9dwl9x6p06s8390ykh/T/run_loop20141203-18371-1mhw7or/trace" -t "Automation" "/Users/nfrydenholm/Work/dba-app-iOS/Build/Products/Debug-iphonesimulator/dba.app" -e UIARESULTSPATH /var/folders/36/ws5sx46n747c9dwl9x6p06s8390ykh/T/run_loop20141203-18371-1mhw7or -e UIASCRIPT /var/folders/36/ws5sx46n747c9dwl9x6p06s8390ykh/T/run_loop20141203-18371-1mhw7or/_run_loop.js  &> /var/folders/36/ws5sx46n747c9dwl9x6p06s8390ykh/T/run_loop20141203-18371-1mhw7or/run_loop.out
 Interrupted system call - /var/folders/36/ws5sx46n747c9dwl9x6p06s8390ykh/T/run_loop20141203-18371-1mhw7or/repl-cmd.pipe (Errno::EINTR)
 /Users/nfrydenholm/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/run_loop-1.1.1.pre8/lib/run_loop/core.rb:254:in `initialize'
 /Users/nfrydenholm/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/run_loop-1.1.1.pre8/lib/run_loop/core.rb:254:in `open'
 /Users/nfrydenholm/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/run_loop-1.1.1.pre8/lib/run_loop/core.rb:254:in `run_with_options'
 /Users/nfrydenholm/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/run_loop-1.1.1.pre8/lib/run_loop/core.rb:764:in `run'
 /Users/nfrydenholm/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.11.5.pre3/lib/calabash-cucumber/launcher.rb:732:in `block in new_run_loop'
 /Users/nfrydenholm/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.11.5.pre3/lib/calabash-cucumber/launcher.rb:730:in `times'
 /Users/nfrydenholm/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.11.5.pre3/lib/calabash-cucumber/launcher.rb:730:in `new_run_loop'
 /Users/nfrydenholm/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.11.5.pre3/lib/calabash-cucumber/launcher.rb:605:in `relaunch'
 /Users/nfrydenholm/Work/dba-app-iOS/Source/features/support/02_pre_stop_hooks.rb:45:in `Before'
    Given I am on Search                                         # features/step_definitions/navigate_steps.rb:11
      Flush result: gcov flushed
    Then a search field is displayed                             # features/step_definitions/search_steps.rb:32
    When I search for "Audi"                                     # features/step_definitions/search_steps.rb:28
    Then I see the SRP for "Audi"                                # features/step_definitions/search_steps.rb:9
    When I extend the search with "A4"                           # features/step_definitions/search_steps.rb:4
    Then I see the SRP for "Audi A4"                             # features/step_definitions/search_steps.rb:9
    When I select listing number 1                               # features/step_definitions/search_steps.rb:40
    Then I see VIP details for the selected listing              # features/step_definitions/vip_steps.rb:151
    Given I go back to previous page                             # features/step_definitions/navigate_steps.rb:179
    When I clear the search field                                # features/step_definitions/search_steps.rb:36
    And I search for "cola"                                      # features/step_definitions/search_steps.rb:28
    Then I see the SRP for "cola"                                # features/step_definitions/search_steps.rb:9
= Request

! CONNECTION CLOSED
! CONNECT TO localhost:37265
Retrying.. Errno::ECONNREFUSED: (Connection refused - connect(2) (http://localhost:37265))
= Request

! CONNECT TO localhost:37265
Retrying.. Errno::ECONNREFUSED: (Connection refused - connect(2) (http://localhost:37265))
= Request
```

**Comment by krukow** [comment]
Closed with 0.12.0. This was caused by timing issues in the script.
