### ISSUE TITLE
Just another Time out waiting for UIAutomation run-loop to Start

### ISSUE THREAD

**Issue by katopz** [calabash/calabash-ios#658]
I'm log this in case someone hit this issue like me, feel free to close this after give me some explanation (yes I found my workaround by luck but don't understand what happen)

step to reproduce just trying this http://www.codingricky.com/calabash-ing-ios-applications/
and at this step 
```shell
$ cucumber
```
i got simulator keep trying to open app (saw zoom in to icon app effect in simulator again and again)
```
mac:todoSwift katopz$ cucumber
Feature: Running a test
  As an iOS developer
  I want to have a sample feature file
  So I can begin testing quickly

  Scenario: Example steps                            # features/my_first.feature:6
Unable to start. Make sure you've set APP_BUNDLE_PATH to a build supported by this simulator version
  Calabash::Cucumber::Launcher::StartError: Time out waiting for UIAutomation run-loop to Start. 
   Logfile /var/folders/m0/6qzn1mcx673d29t3d62mm6tw0000gn/T/run_loop20150107-16182-1cxm21u/run_loop.out 
  
   Waiting for device to boot...
  Instruments Trace Error : Target failed to run: Failed looking up pid of launched process
  
   (Calabash::Cucumber::Launcher::StartError)
  /usr/local/lib/ruby/gems/2.2.0/gems/calabash-cucumber-0.11.4/lib/calabash-cucumber/launcher.rb:743:in `new_run_loop'
  /usr/local/lib/ruby/gems/2.2.0/gems/calabash-cucumber-0.11.4/lib/calabash-cucumber/launcher.rb:605:in `relaunch'
  /Volumes/exFAT/git/todoSwift/features/support/01_launch.rb:27:in `Before'
    Given I am on the Welcome Screen                 # features/step_definitions/my_first_steps.rb:1
    Then I swipe left                                # calabash-cucumber-0.11.4/features/step_definitions/calabash_steps.rb:234
    And I wait until I don't see "Please swipe left" # calabash-cucumber-0.11.4/features/step_definitions/calabash_steps.rb:165
    And take picture                                 # calabash-cucumber-0.11.4/features/step_definitions/calabash_steps.rb:229

Failing Scenarios:
cucumber features/my_first.feature:6 # Scenario: Example steps

1 scenario (1 failed)
4 steps (4 skipped)
2m52.429s
```
work around I found is
```shell
$ DEVICE_TARGET="iPhone 6 (8.1 Simulator)" cucumber
```
and it will working like expect
```
Feature: Running a test
  As an iOS developer
  I want to have a sample feature file
  So I can begin testing quickly

  Scenario: Example steps                            # features/my_first.feature:6
    Given I am on the Welcome Screen                 # features/step_definitions/my_first_steps.rb:1
    Then I swipe left                                # calabash-cucumber-0.11.4/features/step_definitions/calabash_steps.rb:234
    And I wait until I don't see "Please swipe left" # calabash-cucumber-0.11.4/features/step_definitions/calabash_steps.rb:165
    And take picture                                 # calabash-cucumber-0.11.4/features/step_definitions/calabash_steps.rb:229

1 scenario (1 passed)
4 steps (4 passed)
0m55.392s
```
problem is I didn't know what I'm doing and why I have to do this! Please enlighten me.

Thanks

**Comment by krukow** [comment]
@katopz I think you're running into this:

https://github.com/calabash/calabash-ios/wiki/Hot-Topics#1-when-targeting-a-simulator-the-app-launches-then-quits-several-times-in-rapid-succession

Can you confirm?

**Comment by katopz** [comment]
@krukow 
hmm I think I follow all step there and build each step to prove which step is work which none of them work then at final step I realize that I'm not install bundler yet (error from $ bundle exec cucumber) 

so i install bundler
```
Pis-Mac-mini:todoSwift pirsquare$ bundle install
Fetching gem metadata from https://rubygems.org/.........
Using CFPropertyList 2.2.8
Using awesome_print 1.2.0
Using builder 3.2.2
Using diff-lcs 1.2.5
Using multi_json 1.10.1
Using gherkin 2.12.2
Using multi_test 0.1.1
Using cucumber 1.3.18
Installing escape 0.0.4
Using httpclient 2.3.4.1
Using json 1.8.1
Using retriable 1.3.3.1
Installing rubyzip 1.1.6
Using slowhandcuke 0.0.3
Installing calabash-android 0.5.5
Using calabash-common 0.0.1
Using bundler 1.7.11
Using edn 1.0.6
Using geocoder 1.1.9
Using thor 0.19.1
Installing run_loop 1.2.0.pre5
Using rack 1.6.0
Using rack-protection 1.5.3
Using tilt 1.4.1
Using sinatra 1.4.5
Using sim_launcher 0.4.13
Installing calabash-cucumber 0.12.0.pre9
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

then i use $ bundle exec calabash-ios sim reset and then $cucumber again now it work

In short i mess it up already so i still don't know what i'm doing right, but this issue kinda easy to reproduce because i got 2 mac and both got same problem, will try again at home

Thanks

**Comment by krukow** [comment]
Sounds like it was resolved.
