### ISSUE TITLE
Does not contain a compatible architecture for target device - Expected 'i386' but found ["x86_64"]. (RunLoop::IncompatibleArchitecture)

### ISSUE THREAD

**Issue by xingheng** [calabash/calabash-ios#671]
Most iOS projects I created recently are *Standard architectures(armv7, arm64)*, just need a confirm that cucumber didn't support 64bit yet? Thanks!

```
Feature: Running a test
  As an iOS developer
  I want to have a sample feature file
  So I can begin testing quickly

  Scenario: Example steps                            # features/my_first.feature:6
  Binary at:
  /Users/hanwei/Library/Developer/Xcode/DerivedData/ReadingTogether-dcedgdfzouojtgdrvlhxaohzgdte/Build/Products/Debug-iphonesimulator/ReadingTogether-cal.app/ReadingTogether-cal
  ***does not contain a compatible architecture for target device.
  Expected 'i386' but found ["x86_64"]. (RunLoop::IncompatibleArchitecture)***
  /Library/Ruby/Gems/2.0.0/gems/run_loop-1.2.1/lib/run_loop/lipo.rb:71:in `expect_compatible_arch'
  /Library/Ruby/Gems/2.0.0/gems/run_loop-1.2.1/lib/run_loop/core.rb:119:in `expect_compatible_simulator_architecture'
  /Library/Ruby/Gems/2.0.0/gems/run_loop-1.2.1/lib/run_loop/core.rb:214:in `run_with_options'
  /Library/Ruby/Gems/2.0.0/gems/run_loop-1.2.1/lib/run_loop/core.rb:793:in `run'
  /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.12.0/lib/calabash-cucumber/launcher.rb:737:in `block in new_run_loop'
  /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.12.0/lib/calabash-cucumber/launcher.rb:735:in `times'
  /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.12.0/lib/calabash-cucumber/launcher.rb:735:in `new_run_loop'
  /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.12.0/lib/calabash-cucumber/launcher.rb:610:in `relaunch'
  /Users/hanwei/Documents/Projects/gitRepository/ReadingTogether/features/support/01_launch.rb:27:in `Before'
    Given I am on the Welcome Screen                 # features/step_definitions/my_first_steps.rb:1
    Then I swipe left                                # calabash-cucumber-0.12.0/features/step_definitions/calabash_steps.rb:234
    And I wait until I don't see "Please swipe left" # calabash-cucumber-0.12.0/features/step_definitions/calabash_steps.rb:165
    And take picture                                 # calabash-cucumber-0.12.0/features/step_definitions/calabash_steps.rb:229

Failing Scenarios:
cucumber features/my_first.feature:6 # Scenario: Example steps

1 scenario (1 failed)
4 steps (4 skipped)
0m4.668s
```

**Comment by jmoody** [comment]
> Most iOS projects I created recently are Standard architectures(armv7, arm64), just need a confirm that cucumber didn't support 64bit yet?

You are mis-reading the error message.   The binary you are trying to install is x86_64.  The simulator you are targeting is i386.  You need to either build a new FAT binary or run on an x86_64 simulator.

```
# Will vary with Xcode version
$ DEVICE_TARGET="iPhone 5s (8.1 Simulator)" be cucumber
```

#### Links

- [1] https://github.com/calabash/calabash-ios/wiki/Hot-Topics#1-when-targeting-a-simulator-the-app-launches-then-quits-several-times-in-rapid-succession
- [2] https://github.com/calabash/calabash-ios/issues/665

**Comment by jmoody** [comment]
@xingheng  Is this issue resolved?
