### ISSUE TITLE
0.14.1 (8.3 sim) `start_test_server_in_background` times out

### ISSUE THREAD

**Issue by ldiqual** [calabash/calabash-ios#764]
I'm unable to run tests with `calabash-ios` 0.14.1 and the iPhone 5S sim: 

### With `console_attach`

```
[ldiqual@Loiss-MacBook-Air-2 app-ios]$ DEBUG=1 DEBUG_HTTP=1 calabash-ios console
Running irb...
irb(main):001:0> console_attach
Calabash::Cucumber::Launcher: Launch Method 
irb(main):002:0> query("*")[0]
= Request

! CONNECT TO localhost:37265
! CONNECTION ESTABLISHED
POST /map HTTP/1.1
Content-Type: application/x-www-form-urlencoded
User-Agent: HTTPClient/1.0 (2.6.0.1, ruby 2.0.0 (2013-06-27))
Accept: */*
Date: Fri, 08 May 2015 22:15:16 GMT
Content-Length: 64
Host: localhost:37265

{"query":"*","operation":{"method_name":"query","arguments":[]}}

= Response

HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Max-Age: 3000
Accept-Ranges: bytes
Date: Fri, 08 May 2015 22:15:16 GMT
Content-Length: 10283
Access-Control-Allow-Origin: *

{"status_bar_orientation":"down","results":[{"alpha":1,"enabled":true,"id":null,"visible":1,"frame":{"y":0,"x":0,"width":375,"height":667},"accessibilityElement":false,"class":"UIWindow","label":null,"description":"<UIWindow: 0x7fd93aec0330; frame = (0 0; 375 667); gestureRecognizers = <NSArray: 0x7fd93aebf870>; layer = <UIWindowLayer: 0x7fd93ae88380>>","value":null,"rect":{"y":0,"center_x":187.5,"center_y":333.5,"x":0,"width":375,"height":667}},{"alpha":1,"enabled":true,"id":null,"visible":1,"frame":{"y":0,"x":0,"width":375,"height":667},"accessibilityElement":false,"class":"UIView","label":null,"description":"<UIView: 0x7fd93aec92f0; frame = (0 0; 375 667); autoresize = W+H; layer = <CALayer: 0x7fd93aec85f0>>","value":null,"rect":{"y":0,"center_x":187.5,"center_y":333.5,"x":0,"width":375,"height":667}},{"alpha":1,"enabled":true,"id":null,"visible":1,"frame":{"y":0,"x":0,"width":375,"height":667},"accessibilityElement":false,"class":"UILayoutContainerView","label":null,"description":"<UILayoutContainerView: 0x7fd93af37320; frame = (0 0; 375 667); autoresize = W+H; gestureRecognizers = <NSArray: 0x7fd93aee91d0>; layer = <CALayer: 0x7fd93af37a10>>","value":null,"rect":{"y":0,"center_x":187.5,"center_y":333.5,"x":0,"width":375,"height":667}},{"alpha":1,"enabled":true,"id":null,"visible":1,"frame":{"y":0,"x":0,"width":375,"height":667},"accessibilityElement":false,"class":"UITransitionView","label":null,"description":"<UITransitionView: 0x7fd93af26560; frame = (0 0; 375 667); clipsToBounds = YES; autoresize = W+H; layer = <CALayer: 0x7fd93af1c750>>","value":null,"rect":{"y":0,"center_x":187.5,"center_y":333.5,"x":0,"width":375,"height":667}},{"alpha":1,"enabled":true,"id":null,"visible":1,"frame":{"y":0,"x":0,"width":375,"height":667},"accessibilityElement":false,"class":"UIViewControllerWrapperView","label":null,"description":"<UIViewControllerWrapperView: 0x7fd93d10b570; frame = (0 0; 375 667); autoresize = W+H; layer = <CALayer: 0x7fd93d10b690>>","value":null,"rect":{"y":0,"center_x":187.5,"center_y":333.5,"x":0,"width":375,"height":667}},{"alpha":1,"enabled":true,"id":null,"visible":1,"frame":{"y":0,"x":0,"width":375,"height":667},"accessibilityElement":false,"class":"UILayoutContainerView","label":null,"description":"<UILayoutContainerView: 0x7fd93d2058d0; frame = (0 0; 375 667); autoresize = W+H; gestureRecognizers = <NSArray: 0x7fd93d10b110>; layer = <CALayer: 0x7fd93d205a10>>","value":null,"rect":{"y":0,"center_x":187.5,"center_y":333.5,"x":0,"width":375,"height":667}},{"alpha":1,"enabled":true,"id":null,"visible":1,"frame":{"y":0,"x":0,"width":375,"height":667},"accessibilityElement":false,"class":"UINavigationTransitionView","label":null,"description":"<UINavigationTransitionView: 0x7fd93d103c20; frame = (0 0; 375 667); clipsToBounds = YES; autoresize = W+H; layer = <CALayer: 0x7fd93ade1900>>","value":null,"rect":{"y":0,"center_x":187.5,"center_y":333.5,"x":0,"width":375,"height":667}},{"alpha":1,"enabled":true,"id":null,"visible":1,"frame":{"y":0,"x":0,"width":375,"height":667},"accessibilityElement":false,"class":"UIViewControllerWrapperView","label":null,"description":"<UIViewControllerWrapperView: 0x7fd93d216590; frame = (0 0; 375 667); autoresize = W+H; layer = <CALayer: 0x7fd93d216350>>","value":null,"rect":{"y":0,"center_x":187.5,"center_y":333.5,"x":0,"width":375,"height":667}},{"alpha":1,"enabled":true,"id":null,"visible":1,"frame":{"y":0,"x":0,"width":375,"height":667},"accessibilityElement":false,"class":"UIView","label":null,"description":"<UIView: 0x7fd93d211830; frame = (0 0; 375 667); autoresize = W+H; layer = <CALayer: 0x7fd93d211940>>","value":null,"rect":{"y":0,"center_x":187.5,"center_y":333.5,"x":0,"width":375,"height":667}},{"id":null,"description":"<UIButton: 0x7fd93d208dd0; frame = (0 597; 375 70); opaque = NO; autoresize = RM+BM; layer = <CALayer: 0x7fd93d208ff0>>","label":"Schedule","frame":{"y":597,"x":0,"width":375,"height":70},"accessibilityElement":true,"value":null,"alpha":1,"enabled":true,"visible":1,"selected":false,"class":"UIButton","rect":{"y":597,"center_x":187.5,"center_y":632,"x":0,"width":375,"height":70}},{"id":null,"description":"<UIButtonLabel: 0x7fd93d114930; frame = (155.5 26; 64 18); text = 'Schedule'; opaque = NO; userInteractionEnabled = NO; layer = <_UILabelLayer: 0x7fd93d114af0>>","label":"Schedule","frame":{"y":26,"x":155.5,"width":64,"height":18},"accessibilityElement":true,"value":"Schedule","alpha":1,"enabled":true,"visible":1,"text":"Schedule","class":"UIButtonLabel","rect":{"y":623,"center_x":187.5,"center_y":632,"x":155.5,"width":64,"height":18}},{"id":null,"description":"<UILabel: 0x7fd93d209860; frame = (62.5 98; 250 45); text = 'Tuesday morning'; opaque = NO; autoresize = RM+BM; userInteractionEnabled = NO; layer = <_UILabelLayer: 0x7fd93d209a10>>","label":"Tuesday morning","frame":{"y":98,"x":62.5,"width":250,"height":45},"accessibilityElement":true,"value":"Tuesday morning","alpha":1,"enabled":true,"visible":1,"text":"Tuesday morning","class":"UILabel","rect":{"y":98,"center_x":187.5,"center_y":120.5,"x":62.5,"width":250,"height":45}},{"id":null,"description":"<UISegmentedControl: 0x7fd93d201310; frame = (71.5 240; 233 29); opaque = NO; autoresize = RM+BM; layer = <CALayer: 0x7fd93aedacb0>>","label":null,"frame":{"y":240,"x":71.5,"width":233,"height":29},"accessibilityElement":false,"value":null,"alpha":1,"enabled":true,"visible":1,"selected":false,"class":"UISegmentedControl","rect":{"y":240,"center_x":188,"center_y":254.5,"x":71.5,"width":233,"height":29}},{"id":null,"description":"<UISegment: 0x7fd93d2016b0; frame = (0 0; 116 29); opaque = NO; layer = <CALayer: 0x7fd93d207de0>> - Driver","label":"Driver","frame":{"y":0,"x":0,"width":116,"height":29},"accessibilityElement":true,"value":"","alpha":1,"enabled":true,"visible":1,"selected":true,"class":"UISegment","rect":{"y":240,"center_x":129.5,"center_y":254.5,"x":71.5,"width":116,"height":29}},{"id":null,"description":"<UISegmentLabel: 0x7fd93d209d10; frame = (40.5 6.5; 35.5 16); text = 'Driver'; opaque = NO; userInteractionEnabled = NO; layer = <_UILabelLayer: 0x7fd93d207060>>","label":"Driver","frame":{"y":6.5,"x":40.5,"width":35.5,"height":16},"accessibilityElement":true,"value":"Driver","alpha":1,"enabled":true,"visible":1,"text":"Driver","class":"UISegmentLabel","rect":{"y":246.5,"center_x":129.75,"center_y":254.5,"x":112,"width":35.5,"height":16}},{"alpha":1,"enabled":false,"id":null,"visible":1,"frame":{"y":0,"x":116,"width":1,"height":29},"accessibilityElement":false,"class":"UIImageView","label":null,"description":"<UIImageView: 0x7fd93d208370; frame = (116 0; 1 29); opaque = NO; autoresize = LM; userInteractionEnabled = NO; tag = -1030; layer = <CALayer: 0x7fd93d2082d0>> - (null)","value":null,"rect":{"y":240,"center_x":188,"center_y":254.5,"x":187.5,"width":1,"height":29}},{"id":null,"description":"<UISegment: 0x7fd93d2010a0; frame = (117 0; 116 29); opaque = NO; layer = <CALayer: 0x7fd93d2036d0>> - Rider","label":"Rider","frame":{"y":0,"x":117,"width":116,"height":29},"accessibilityElement":true,"value":"","alpha":1,"enabled":true,"visible":1,"selected":false,"class":"UISegment","rect":{"y":240,"center_x":246.5,"center_y":254.5,"x":188.5,"width":116,"height":29}},{"id":null,"description":"<UISegmentLabel: 0x7fd93d2007f0; frame = (42 6.5; 32 16); text = 'Rider'; opaque = NO; userInteractionEnabled = NO; layer = <_UILabelLayer: 0x7fd93d20fee0>>","label":"Rider","frame":{"y":6.5,"x":42,"width":32,"height":16},"accessibilityElement":true,"value":"Rider","alpha":1,"enabled":true,"visible":1,"text":"Rider","class":"UISegmentLabel","rect":{"y":246.5,"center_x":246.5,"center_y":254.5,"x":230.5,"width":32,"height":16}},{"id":null,"description":"<UISegmentedControl: 0x7fd93d20a060; frame = (71.5 326; 233 29); opaque = NO; autoresize = RM+BM; layer = <CALayer: 0x7fd93d20a1e0>>","label":null,"frame":{"y":326,"x":71.5,"width":233,"height":29},"accessibilityElement":false,"value":null,"alpha":1,"enabled":true,"visible":1,"selected":false,"class":"UISegmentedControl","rect":{"y":326,"center_x":188,"center_y":340.5,"x":71.5,"width":233,"height":29}},{"id":null,"description":"<UISegment: 0x7fd93d206700; frame = (0 0; 116 29); opaque = NO; layer = <CALayer: 0x7fd93d204760>> - 00:30","label":"00:30","frame":{"y":0,"x":0,"width":116,"height":29},"accessibilityElement":true,"value":"","alpha":1,"enabled":true,"visible":1,"selected":true,"class":"UISegment","rect":{"y":326,"center_x":129.5,"center_y":340.5,"x":71.5,"width":116,"height":29}},{"id":null,"description":"<UISegmentLabel: 0x7fd93d204850; frame = (41 6.5; 34 16); text = '00:30'; opaque = NO; userInteractionEnabled = NO; layer = <_UILabelLayer: 0x7fd93d201ed0>>","label":"00:30","frame":{"y":6.5,"x":41,"width":34,"height":16},"accessibilityElement":true,"value":"00:30","alpha":1,"enabled":true,"visible":1,"text":"00:30","class":"UISegmentLabel","rect":{"y":332.5,"center_x":129.5,"center_y":340.5,"x":112.5,"width":34,"height":16}},{"alpha":1,"enabled":false,"id":null,"visible":1,"frame":{"y":0,"x":116,"width":1,"height":29},"accessibilityElement":false,"class":"UIImageView","label":null,"description":"<UIImageView: 0x7fd93d20fb60; frame = (116 0; 1 29); opaque = NO; autoresize = LM; userInteractionEnabled = NO; tag = -1030; layer = <CALayer: 0x7fd93d20e4f0>> - (null)","value":null,"rect":{"y":326,"center_x":188,"center_y":340.5,"x":187.5,"width":1,"height":29}},{"id":null,"description":"<UISegment: 0x7fd93d2072d0; frame = (117 0; 116 29); opaque = NO; layer = <CALayer: 0x7fd93d2079d0>> - 01:00","label":"01:00","frame":{"y":0,"x":117,"width":116,"height":29},"accessibilityElement":true,"value":"","alpha":1,"enabled":true,"visible":1,"selected":false,"class":"UISegment","rect":{"y":326,"center_x":246.5,"center_y":340.5,"x":188.5,"width":116,"height":29}},{"id":null,"description":"<UISegmentLabel: 0x7fd93d213220; frame = (41 6.5; 34 16); text = '01:00'; opaque = NO; userInteractionEnabled = NO; layer = <_UILabelLayer: 0x7fd93d20b350>>","label":"01:00","frame":{"y":6.5,"x":41,"width":34,"height":16},"accessibilityElement":true,"value":"01:00","alpha":1,"enabled":true,"visible":1,"text":"01:00","class":"UISegmentLabel","rect":{"y":332.5,"center_x":246.5,"center_y":340.5,"x":229.5,"width":34,"height":16}}],"outcome":"SUCCESS"}{
                   "alpha" => 1,
                 "enabled" => true,
                      "id" => nil,
                 "visible" => 1,
                   "frame" => {
             "y" => 0,
             "x" => 0,
         "width" => 375,
        "height" => 667
    },
    "accessibilityElement" => false,
                   "class" => "UIWindow",
                   "label" => nil,
             "description" => "<UIWindow: 0x7fd93aec0330; frame = (0 0; 375 667); gestureRecognizers = <NSArray: 0x7fd93aebf870>; layer = <UIWindowLayer: 0x7fd93ae88380>>",
                   "value" => nil,
                    "rect" => {
               "y" => 0,
        "center_x" => 187.5,
        "center_y" => 333.5,
               "x" => 0,
           "width" => 375,
          "height" => 667
    }
}
```

### `start_test_server_in_background` (fails)

```
irb(main):003:0> start_test_server_in_background
Sending 'QUIT' to instruments process '48447'
Waiting for instruments '48447' to terminate
Waited for 0.614952 seconds for instruments with '48447' to terminate

INFO: Using uia strategy: 'preferences'
2015-05-08 15:15:25 -0700 [RunLoop:debug]: Simulator instruction set 'x86_64' is compatible with ["x86_64"]
Waited for 0.158698 seconds for 'iOS Simulator' to start.
Waited for 0.529336 seconds for 'SimulatorBridge' to start.
2015-05-08 15:15:29 -0700 [RunLoop:debug]: 
{
                        :app => "/Users/ldiqual/Library/Developer/Xcode/DerivedData/app-alyhrklbiwgisubfitgkzzfamfys/Build/Products/Debug-iphonesimulator/app.app",
                       :args => [],
    :bundle_dir_or_bundle_id => "/Users/ldiqual/Library/Developer/Xcode/DerivedData/app-alyhrklbiwgisubfitgkzzfamfys/Build/Products/Debug-iphonesimulator/app.app",
                  :bundle_id => "com.takeapp.app",
                     :device => "iphone",
              :device_target => "simulator",
              :launch_method => :instruments,
             :launch_retries => 5,
                   :log_file => "/var/folders/6y/lmxm7bmd4_qcbbqqnln21m_80000gn/T/run_loop20150508-49977-1js7xo1/run_loop.out",
                  :no_launch => false,
                    :no_stop => false,
         :relaunch_simulator => true,
                      :reset => false,
                :results_dir => "/var/folders/6y/lmxm7bmd4_qcbbqqnln21m_80000gn/T/run_loop20150508-49977-1js7xo1",
          :results_dir_trace => "/var/folders/6y/lmxm7bmd4_qcbbqqnln21m_80000gn/T/run_loop20150508-49977-1js7xo1/trace",
                     :script => "/var/folders/6y/lmxm7bmd4_qcbbqqnln21m_80000gn/T/run_loop20150508-49977-1js7xo1/_run_loop.js",
                :sdk_version => nil,
                       :udid => "iPhone 5s (8.3 Simulator)",
               :uia_strategy => :preferences,
                      :xcode => "6.3",
                 :xcode_path => "/Applications/Xcode.app/Contents/Developer"
}

### Starting on simulator App: /Users/ldiqual/Library/Developer/Xcode/DerivedData/app-alyhrklbiwgisubfitgkzzfamfys/Build/Products/Debug-iphonesimulator/app.app ###
2015-05-08 15:15:30 -0700 [RunLoop:debug]: xcrun instruments -w iPhone 5s (8.3 Simulator) -D /var/folders/6y/lmxm7bmd4_qcbbqqnln21m_80000gn/T/run_loop20150508-49977-1js7xo1/trace -t Automation /Users/ldiqual/Library/Developer/Xcode/DerivedData/app-alyhrklbiwgisubfitgkzzfamfys/Build/Products/Debug-iphonesimulator/app.app -e UIARESULTSPATH /var/folders/6y/lmxm7bmd4_qcbbqqnln21m_80000gn/T/run_loop20150508-49977-1js7xo1 -e UIASCRIPT /var/folders/6y/lmxm7bmd4_qcbbqqnln21m_80000gn/T/run_loop20150508-49977-1js7xo1/_run_loop.js >& /var/folders/6y/lmxm7bmd4_qcbbqqnln21m_80000gn/T/run_loop20150508-49977-1js7xo1/run_loop.out
2015-05-08 15:15:30 -0700 [RunLoop:debug]: Preparation took 5.12927 seconds
2015-05-08 15:15:36 -0700 [RunLoop:debug]: Launching took 6.471077 seconds
#<RuntimeError: Timed out connecting to Calabash server after 10 retries. Make sure it is linked and App isn't crashing>
RuntimeError: Unable to make connection to Calabash Server at http://localhost:37265/
Make sure you don't have a firewall blocking traffic to http://localhost:37265/.

    from /Users/ldiqual/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.14.1/lib/calabash-cucumber/launcher.rb:809:in `rescue in ensure_connectivity'
    from /Users/ldiqual/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.14.1/lib/calabash-cucumber/launcher.rb:771:in `ensure_connectivity'
    from /Users/ldiqual/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.14.1/lib/calabash-cucumber/launcher.rb:642:in `relaunch'
    from /Users/ldiqual/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.14.1/lib/calabash-cucumber/core.rb:849:in `start_test_server_in_background'
    from (irb):3
    from /Users/ldiqual/.rbenv/versions/2.0.0-p247/bin/irb:12:in `<main>'
```

### Console logs when launched from xcode

```
2015-05-08 15:14:50.448 Scoop[49959:686766] Creating the server: <LPHTTPServer: 0x7fd93ae48ab0>
2015-05-08 15:14:50.449 Scoop[49959:686766] Calabash iOS server version: CALABASH VERSION: 0.14.1
2015-05-08 15:14:50.449 Scoop[49959:686766] App Base SDK: iphonesimulator8.3
2015-05-08 15:14:50.450 Scoop[49959:686766] simroot: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk
2015-05-08 15:14:50.468 Scoop[49959:686766] Started LPHTTP server on port 37265
2015-05-08 15:14:50.544 Scoop[49959:686766] WKWebView is not available
2015-05-08 15:14:50.561 Scoop[49959:686811] Bonjour Service Published: domain(local.) type(_http._tcp.) name(Calabash Server)
```

### Listening ports when launched from Xcode

```
[ldiqual@Loiss-MacBook-Air-2 app-ios]$ sudo lsof -nP -iTCP:37265 -sTCP:LISTEN
COMMAND   PID    USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
app   51817 ldiqual    4u  IPv4 0xb9e79ab55e4a7b25      0t0  TCP *:37265 (LISTEN)
app   51817 ldiqual    5u  IPv6 0xb9e79ab55e0e2055      0t0  TCP *:37265 (LISTEN)
```

### Listening ports when launched from console

```
[ldiqual@Loiss-MacBook-Air-2 app-ios]$ sudo lsof -nP -iTCP:37265 -sTCP:LISTEN
// Nothing
```

What would cause calabash to not initiate the HTTP server when launched from the console? I also made sure that the app ran in Xcode was the same ran by calabash (`/Users/ldiqual/Library/Developer/Xcode/DerivedData/app-alyhrklbiwgisubfitgkzzfamfys/Build/Products/Debug-iphonesimulator/app.app`)

**Comment by ldiqual** [comment]
I got it working by:
 - Forcing `DEVICE_TARGET` to be the simulator that is currently open. I was using iPhone 6 but calabash was launching iPhone 5S
 - Calling `CalabashServer.start()` explicitly, in my app delegate. It required the following patch: https://github.com/calabash/calabash-ios-server/pull/166

**Comment by jmoody** [comment]
@ldiqual Is this Xcode 6.3 and are you using run-loop < 1.3.1? If so, it is possible you have encountered this:

**1. Xcode 6.3 cannot launch my app on iOS 8.3 Simulators [RESOLVED]** https://github.com/calabash/calabash-ios/wiki/Hot-Topics

On the other hand, it looks like the app was launched.  If another Calabash app is running on your simulator, the 37265 port will be blocked.

> Is this last step normal or is there a way to avoid it?

No.  It is not normal and not recommended.

**Comment by jmoody** [comment]
@ldiqual And +100 for _excellent_ formatting in a bug report.

**Comment by ldiqual** [comment]
@jmoody All issues are resolved by adding `RESET_BETWEEN_SCENARIOS=1`, the second step (manual start of the Calabash server) was unnecessary. Closing this.
