### ISSUE TITLE
Unable to get calabash-ios started

### ISSUE THREAD

**Issue by vanditj-optimus** [calabash/calabash-ios#790]
OSX - 10.10.2
Xcode - Version 6.3.1 (6D1002)
Calabash-iOS - 0.14.3

```
When I try running the default script I got this error:-
Feature: Running a test
  As an iOS developer
  I want to have a sample feature file
  So I can begin testing quickly

  Scenario: Example steps                            # features/my_first.feature:6
#<Net::ReadTimeout: Net::ReadTimeout>
  Unable to make connection to Calabash Server at http://localhost:37265/
  Make sure you don't have a firewall blocking traffic to http://localhost:37265/.
   (RuntimeError)
  /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/launcher.rb:806:in `rescue in ensure_connectivity'
  /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/launcher.rb:771:in `ensure_connectivity'
  /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/launcher.rb:642:in `relaunch'
  /Users/Optimus/Documents/Social App/SourceCode/features/support/01_launch.rb:27:in `Before'
    Given I am on the Welcome Screen                 # features/step_definitions/my_first_steps.rb:1
    Then I swipe left                                # calabash-cucumber-0.14.3/features/step_definitions/calabash_steps.rb:222
    And I wait until I don't see "Please swipe left" # calabash-cucumber-0.14.3/features/step_definitions/calabash_steps.rb:158
    And take picture                                 # calabash-cucumber-0.14.3/features/step_definitions/calabash_steps.rb:217
Retrying.. HTTPClient::ReceiveTimeoutError: (execution expired)
```

When running the build through -cal manually, it is working fine

Please help me.

**Comment by jmoody** [comment]
Please ask your question on the Calabash iOS forum.

**Comment by nagaraja490** [comment]
I face the same issue : Net::ReadTimeout (Net::ReadTimeout)
 ./features/support/01_launch.rb:41:in `lp_server_running?'
 ./features/support/01_launch.rb:68:in `running?'
 ./features/support/01_launch.rb:138:in `Before'
