### ISSUE TITLE
XCode 6.3 launching iOS simulator 7.1 UIAutomation run-loop failed

### ISSUE THREAD

**Issue by RichardStoff** [calabash/calabash-ios#794]
**environment:**
* OSX: Yosemite 10.10.3 (14D136)
* Xcode path: /Applications/Xcode.app/Contents/Developer
* Xcode: 6.3.2 (6D2105)
* Calabash: 0.14.3
* Bundler: 1.10.5
* Ruby: 2.1.2p95
* terminal using oh my zsh

List of Simulator
```
instruments -s devices
Known Devices:
Resizable iPad (8.2 Simulator) [10688503-EFB6-4311-986E-FD122745AFB7]
Resizable iPad (8.3 Simulator) [2795C153-22E8-484E-BA83-21D7A156002F]
Resizable iPhone (8.2 Simulator) [E704E2D6-A2FD-4F3B-81DD-4FB799371BAB]
Resizable iPhone (8.3 Simulator) [B4740E9D-6DF4-460A-8D99-4FA5DB07C9CC]
iPad 2 (7.1 Simulator) [26B2B297-4A54-4986-A655-0A1D0446DFF8]
iPad 2 (8.2 Simulator) [F8C40350-8FF7-4C88-994D-8543FC7CF7D9]
iPad 2 (8.3 Simulator) [7EC48BA1-9C18-4258-8773-448643B3EC46]
iPad Air (7.1 Simulator) [C03AA03D-2671-4B30-873D-267ADA64F70A]
iPad Air (8.2 Simulator) [7F3AA8A3-1FE8-4AE3-BEE4-AF41D203E4B2]
iPad Air (8.3 Simulator) [75B8EF68-8FBF-432E-8FF0-7E510ECFB7D0]
iPad Retina (7.1 Simulator) [C58B2390-D265-49BD-991B-64D1345D3D3E]
iPad Retina (8.2 Simulator) [3844894F-18A0-4352-88C6-D65634DAED2C]
iPad Retina (8.3 Simulator) [75B2CDC9-3ED6-42B0-ACE4-C9D6982FAE1A]
iPhone 4s (7.1 Simulator) [66EC20E9-9A0B-400E-A2A8-5D7699780D7B]
iPhone 4s (8.1 Simulator) [A56927ED-9894-46E1-B5B3-60E120666A1E]
iPhone 4s (8.2 Simulator) [A75C4CCC-DE41-40E7-975F-7B9ED6934748]
iPhone 4s (8.3 Simulator) [42E93DCF-08F6-43AE-95EE-8618EF6E5B40]
iPhone 5 (7.1 Simulator) [583DB67A-4E8F-4534-BFDA-E1E88E33786A]
iPhone 5 (8.2 Simulator) [7C93AC44-ACCC-4B29-8C2D-57D7621619C3]
iPhone 5 (8.3 Simulator) [5E0B9F62-3E8F-4915-8E13-1F2CD20CCC80]
iPhone 5s (7.1 Simulator) [FEA958E3-186F-4004-8BF8-26D54006A3E9]
iPhone 5s (8.1 Simulator) [EDB5B381-7228-4059-9EC7-1D714D9575B3]
iPhone 5s (8.2 Simulator) [91B0F04D-D40E-49C5-AEF9-EADE09C95596]
iPhone 5s (8.3 Simulator) [C41F58C6-2C6C-4DD3-8DF0-3CEE33CC4F81]
iPhone 6 (8.1 Simulator) [6DB74E8B-1EF6-4F56-A3F1-8FA3B691C83A]
iPhone 6 (8.2 Simulator) [9D3F6523-0979-46A4-8484-5BFF90FCB8C7]
iPhone 6 (8.3 Simulator) [090EEB73-7733-4D42-A194-981BA314D97B]
iPhone 6 Plus (8.1 Simulator) [963549BE-EF89-47BD-A3B0-1A084B581455]
iPhone 6 Plus (8.2 Simulator) [E6C57526-5540-4695-8F29-DCD9CE0FA95E]
iPhone 6 Plus (8.3 Simulator) [214AAB11-9B0C-44DE-982C-29C0C716CBB7]

xcrun simctl list
== Device Types ==
iPhone 4s (com.apple.CoreSimulator.SimDeviceType.iPhone-4s)
iPhone 5 (com.apple.CoreSimulator.SimDeviceType.iPhone-5)
iPhone 5s (com.apple.CoreSimulator.SimDeviceType.iPhone-5s)
iPhone 6 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus)
iPhone 6 (com.apple.CoreSimulator.SimDeviceType.iPhone-6)
iPad 2 (com.apple.CoreSimulator.SimDeviceType.iPad-2)
iPad Retina (com.apple.CoreSimulator.SimDeviceType.iPad-Retina)
iPad Air (com.apple.CoreSimulator.SimDeviceType.iPad-Air)
Resizable iPhone (com.apple.CoreSimulator.SimDeviceType.Resizable-iPhone)
Resizable iPad (com.apple.CoreSimulator.SimDeviceType.Resizable-iPad)
== Runtimes ==
iOS 7.1 (7.1 - 11D167) (com.apple.CoreSimulator.SimRuntime.iOS-7-1)
iOS 8.1 (8.1 - 12B411) (com.apple.CoreSimulator.SimRuntime.iOS-8-1)
iOS 8.2 (8.2 - 12D508) (com.apple.CoreSimulator.SimRuntime.iOS-8-2)
iOS 8.3 (8.3 - 12F69) (com.apple.CoreSimulator.SimRuntime.iOS-8-3)
== Devices ==
-- iOS 7.1 --
    iPhone 4s (66EC20E9-9A0B-400E-A2A8-5D7699780D7B) (Shutdown)
    iPhone 5 (583DB67A-4E8F-4534-BFDA-E1E88E33786A) (Shutdown)
    iPhone 5s (FEA958E3-186F-4004-8BF8-26D54006A3E9) (Booted)
    iPad 2 (26B2B297-4A54-4986-A655-0A1D0446DFF8) (Shutdown)
    iPad Retina (C58B2390-D265-49BD-991B-64D1345D3D3E) (Shutdown)
    iPad Air (C03AA03D-2671-4B30-873D-267ADA64F70A) (Shutdown)
-- iOS 8.1 --
    iPhone 4s (A56927ED-9894-46E1-B5B3-60E120666A1E) (Shutdown)
    iPhone 5s (EDB5B381-7228-4059-9EC7-1D714D9575B3) (Shutdown)
    iPhone 6 Plus (963549BE-EF89-47BD-A3B0-1A084B581455) (Shutdown)
    iPhone 6 (6DB74E8B-1EF6-4F56-A3F1-8FA3B691C83A) (Shutdown)
-- iOS 8.2 --
    iPhone 4s (A75C4CCC-DE41-40E7-975F-7B9ED6934748) (Shutdown)
    iPhone 5 (7C93AC44-ACCC-4B29-8C2D-57D7621619C3) (Shutdown)
    iPhone 5s (91B0F04D-D40E-49C5-AEF9-EADE09C95596) (Shutdown)
    iPhone 6 Plus (E6C57526-5540-4695-8F29-DCD9CE0FA95E) (Shutdown)
    iPhone 6 (9D3F6523-0979-46A4-8484-5BFF90FCB8C7) (Shutdown)
    iPad 2 (F8C40350-8FF7-4C88-994D-8543FC7CF7D9) (Shutdown)
    iPad Retina (3844894F-18A0-4352-88C6-D65634DAED2C) (Shutdown)
    iPad Air (7F3AA8A3-1FE8-4AE3-BEE4-AF41D203E4B2) (Shutdown)
    Resizable iPhone (E704E2D6-A2FD-4F3B-81DD-4FB799371BAB) (Shutdown)
    Resizable iPad (10688503-EFB6-4311-986E-FD122745AFB7) (Shutdown)
-- iOS 8.3 --
    iPhone 4s (42E93DCF-08F6-43AE-95EE-8618EF6E5B40) (Shutdown)
    iPhone 5 (5E0B9F62-3E8F-4915-8E13-1F2CD20CCC80) (Shutdown)
    iPhone 5s (C41F58C6-2C6C-4DD3-8DF0-3CEE33CC4F81) (Shutdown)
    iPhone 6 Plus (214AAB11-9B0C-44DE-982C-29C0C716CBB7) (Shutdown)
    iPhone 6 (090EEB73-7733-4D42-A194-981BA314D97B) (Shutdown)
    iPad 2 (7EC48BA1-9C18-4258-8773-448643B3EC46) (Shutdown)
    iPad Retina (75B2CDC9-3ED6-42B0-ACE4-C9D6982FAE1A) (Shutdown)
    iPad Air (75B8EF68-8FBF-432E-8FF0-7E510ECFB7D0) (Shutdown)
    Resizable iPhone (B4740E9D-6DF4-460A-8D99-4FA5DB07C9CC) (Shutdown)
    Resizable iPad (2795C153-22E8-484E-BA83-21D7A156002F) (Shutdown)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.iOS-9-0 --
    iPhone 4s (7792D3DD-C61A-4536-B9C0-983AC93FABB8) (Shutdown) (unavailable, runtime profile not found)
    iPhone 5 (CE622C0F-FCFF-4D6F-AFF0-B75DBB3CC7BC) (Shutdown) (unavailable, runtime profile not found)
    iPhone 5s (7922EE0F-1A97-4BB4-A26C-DE618891EAF8) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 Plus (9D9BB7C4-0D94-4B84-95D5-9196AFCB926B) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 (72167AFD-D57E-4B7C-90FD-2E84EA5AFB5E) (Shutdown) (unavailable, runtime profile not found)
    iPad 2 (2023637B-0F87-4DEA-A4D7-7968A3451D82) (Shutdown) (unavailable, runtime profile not found)
    iPad Retina (88CAD392-22E5-4E1D-B4E5-96AC33DEC973) (Shutdown) (unavailable, runtime profile not found)
    iPad Air (966986BD-16F6-42CF-8485-C22AF1496025) (Shutdown) (unavailable, runtime profile not found)
    iPad Air 2 (9CE7799A-8566-42CC-86C0-D22882269D7F) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.watchOS-2-0 --
    Apple Watch - 38mm (D7962065-A1DA-4999-B529-66AC41C0AF02) (Shutdown) (unavailable, runtime profile not found)
    Apple Watch - 42mm (E64109DF-D02A-4924-82F2-9239C67FC226) (Shutdown) (unavailable, runtime profile not found)

```

Gemfile
```
source 'https://rubygems.org'

gem 'faker', '~> 1.4'
gem 'xcpretty', '~> 0.1'
gem 'pry', '~> 0.10'
gem 'briar', '~> 1.1'
gem 'calabash-cucumber', '~> 0.14'

# patch for cucumber and ruby 2.2.0
gem 'minitest'
```
Server Version
```
$DEVICE_TARGET="iPhone 4s (7.1 Simulator)" calabash-ios console
{
                    "app_version" => "##",
                        "outcome" => "SUCCESS",
                            "git" => {
        "remote_origin" => "git@github.com:calabash/calabash-ios-server.git",
               "branch" => "master",
             "revision" => "c2d009b"
    },
                         "app_id" => "########",
               "simulator_device" => "iPhone",
                   "app_base_sdk" => "iphonesimulator8.3",
                        "version" => "0.14.3",
                    "server_port" => 37265,
                       "app_name" => "######",
    "iphone_app_emulated_on_ipad" => false,
                    "form_factor" => "iphone 3.5in",
                          "4inch" => false,
           "short_version_string" => "7.0",
              "screen_dimensions" => {
         "scale" => 2,
         "width" => 640,
        "sample" => 1,
        "height" => 960
    },
                    "iOS_version" => "7.1",
                         "system" => "x86_64",
                      "simulator" => "CoreSimulator 117.15 - Device: iPhone 4s - Runtime: iOS 7.1 (11D167) - DeviceType: iPhone 4s"
}
```

Build Script
```
xcodebuild \
  ARCHS="i386 x86_64" \
  VALID_ARCHS="i386 x86_64" \
  ONLY_ACTIVE_ARCH=NO \
  -workspace ../src/iOS/iPhone/AppName/AppName.xcworkspace \
  -scheme 'AppName-Cal' \
  -sdk iphonesimulator \
  -configuration Calabash \
  clean build CONFIGURATION_BUILD_DIR=$(PWD)/iOS/
```
I also use pod in my workspace, and I check the **Build Active Architecture Only** to NO for calabash scheme.

**The Problem**
Everything works well on iOS8.1 8.2 & 8.3, I installed every iOS SDK Xcode allowed me.

Even if i can launch my iPhone iOS 7 (or iPad, in fact any iOS7 device i want) using the calabash console, I can't use the cucumber automation. My simulator will launch but no application will be installed, and then I will receive an Error message from UIAutomation run-loop like this one.

my cucumber.yml
```
<%
sims = {}
  sims[:iPhone4s_71]    = 'iPhone 4s (7.1 Simulator)'
 .. lots of them
%>
simulators:     SIMULATORS="<%= sims %>"
ios_bundle_id:  BUNDLE_ID=com.AppName
ios_app_bundle: APP_BUNDLE_PATH=build/iOS/AppName.app
ios_requires:   -r features/support -r features/ios/support -r features/ios/helpers -r features/step_definitions -r features/ios/pages

ios: PLATFORM=ios -p ios_bundle_id -p ios_requires -p ios_app_bundle --tags ~@android
wip: --tags @wip
tablette: --tags ~@phone
phone: --tags ~@tablette

iPhone4s_71: -p ios DEVICE_TARGET="<%= sims[:iPhone4s_71] %>" -p phone
```

my error : 
```
bundle exec cucumber -p iPhone4s_71
Using the iPhone4s_71, ios, phone, ios_bundle_id, ios_requires and ios_app_bundle profiles...
# language: fr
@reinstall
Fonctionnalité: blabla in french

  Scénario: my french scenario stuff                                                                                 # features/TestLink/G-01-01-SPFD.feature:6
Unable to start. Make sure you've set APP_BUNDLE_PATH to a build supported by this simulator version
  Calabash::Cucumber::Launcher::StartError: Time out waiting for UIAutomation run-loop execution expired. 
   Logfile /var/folders/45/_g1wmb11507cln1yl562b6r40000gn/T/run_loop20150630-36312-1rwmohv/run_loop.out 
  
   2015-06-30 14:11:53.518 instruments[37020:2056229] [MT] DVTAssertions: ASSERTION FAILURE in /SourceCache/DVTFrameworks/DVTFrameworks-7710/DVTFoundation/FilePaths/DVTFilePath.m:802
  Details:  fsrep is relative ('build/iOS/PagesJaunes.app') parentPath must not be nil but it is.
  Object:   <DVTFilePath>
  Method:   +_filePathForParent:fileSystemRepresentation:length:allowCreation:
  Thread:   <NSThread: 0x7faa41731c70>{number = 1, name = main}
  Hints: None
  Backtrace:
    0  0x000000010b9a4b87 -[DVTAssertionHandler handleFailureInMethod:object:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in DVTFoundation)
    1  0x000000010b9a45df _DVTAssertionHandler (in DVTFoundation)
    2  0x000000010b9a48ce _DVTAssertionFailureHandler (in DVTFoundation)
    3  0x000000010b7dbd09 +[DVTFilePath _filePathForParent:fileSystemRepresentation:length:allowCreation:] (in DVTFoundation)
    4  0x000000010b7db90c +[DVTFilePath _filePathForParent:pathString:] (in DVTFoundation)
    5  0x000000010b7db684 +[DVTFilePath filePathForPathString:] (in DVTFoundation)
    6  0x00000001145bddac __62-[DTiPhoneSimulatorSession _startSessionInSimulatorWithError:]_block_invoke199 (in DVTiPhoneSimulatorRemoteClient)
    7  0x000000010b94f8b4 __38-[DVTFuture(DVTFutureAdditions) then:]_block_invoke_2 (in DVTFoundation)
    8  0x000000010b94b78b -[DVTFuture observeFinish:] (in DVTFoundation)
    9  0x000000010b94f7fa __38-[DVTFuture(DVTFutureAdditions) then:]_block_invoke (in DVTFoundation)
   10  0x000000010b94aa80 -[DVTFuture initWithBlock:] (in DVTFoundation)
   11  0x000000010b94f6ce -[DVTFuture(DVTFutureAdditions) then:] (in DVTFoundation)
   12  0x00000001145bd5d9 -[DTiPhoneSimulatorSession _startSessionInSimulatorWithError:] (in DVTiPhoneSimulatorRemoteClient)
   13  0x00000001145bc668 __65-[DTiPhoneSimulatorSession requestStartWithConfig:timeout:error:]_block_invoke46 (in DVTiPhoneSimulatorRemoteClient)
   14  0x000000010b980d74 -[_DVTNotificationReceiver receiveNotification:] (in DVTFoundation)
   15  0x00007fff9117245c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ (in CoreFoundation)
   16  0x00007fff9112ff8e ____CFXNotificationPostToken_block_invoke (in CoreFoundation)
   17  0x00007fff910d28ec __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ (in CoreFoundation)
   18  0x00007fff910c49f5 __CFRunLoopDoBlocks (in CoreFoundation)
   19  0x00007fff910c4536 __CFRunLoopRun (in CoreFoundation)
   20  0x00007fff910c3bd8 CFRunLoopRunSpecific (in CoreFoundation)
   21  0x00007fff8d44fa59 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] (in Foundation)
   22  0x000000011457ef1f (in XRMobileDeviceDiscoveryPlugIn)
   23  0x000000011457e831 (in XRMobileDeviceDiscoveryPlugIn)
   24  0x0000000109d5bf87 -[PFTProcess runSuspended:error:] (in InstrumentsPlugIn)
   25  0x0000000109d6b157 -[PFTInstrumentPlugin prepareInstruments:forCommand:error:] (in InstrumentsPlugIn)
   26  0x0000000109d7ce98 __42-[PFTInstrumentList prepareCommand:error:]_block_invoke235 (in InstrumentsPlugIn)
   27  0x0000000109d7c0f6 __60-[PFTInstrumentList _enumerateInstrumentsByPluginWithBlock:]_block_invoke (in InstrumentsPlugIn)
   28  0x00007fff910df246 __65-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke (in CoreFoundation)
   29  0x00007fff910df159 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] (in CoreFoundation)
   30  0x0000000109d7c05f -[PFTInstrumentList _enumerateInstrumentsByPluginWithBlock:] (in InstrumentsPlugIn)
   31  0x0000000109d7ca32 -[PFTInstrumentList prepareCommand:error:] (in InstrumentsPlugIn)
   32  0x0000000109cef4b8 -[XRTrace startCommandWithPurpose:] (in InstrumentsPlugIn)
   33  0x0000000109c626d0 (in instruments)
   34  0x0000000109c63d44 (in instruments)
   35  0x00007fff8b4a65c9 start (in libdyld.dylib)
   36  0x000000000000000e
  
   (Calabash::Cucumber::Launcher::StartError)
  /Users/StoFF/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/launcher.rb:766:in `new_run_loop'
  /Users/StoFF/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/launcher.rb:631:in `relaunch'
  /Users/StoFF/Documents/Projects/Rabindranath/features/ios/support/01_launch.rb:25:in `Before'
```

In order to be fully complet this is my 01_launch.rb
```
require 'calabash-cucumber/launcher'


Before do |scenario|
  @calabash_launcher = Calabash::Cucumber::Launcher.new
  scenario_tags = scenario.source_tag_names
  if scenario_tags.include?('@reinstall')
    @calabash_launcher.reset_app_jail
  end
  unless @calabash_launcher.calabash_no_launch?
    @calabash_launcher.relaunch
    @calabash_launcher.calabash_notify(self)
  end
end

After do |scenario|
  unless @calabash_launcher.calabash_no_stop?
    calabash_exit
    if @calabash_launcher.active?
      @calabash_launcher.stop
    end
  end
end

at_exit do
  launcher = Calabash::Cucumber::Launcher.new
  if launcher.simulator_target?
    launcher.simulator_launcher.stop unless launcher.calabash_no_stop?
  end
end
```

I don't know what's going on, my APP_BUNDLE_PATH seems to not work for iOS7 simulator, but why, i set my i386 and succeded to launch by console but UIAutomation even using Bundler is still not working...
What am I missing ? Does someone have an idea ?

**Comment by jmoody** [comment]
+1 for the detailed bug report.

> fsrep is relative ('build/iOS/PagesJaunes.app') parentPath must not be nil but it is.

Can you try an absolute path to your app?  We have observed that some versions of Xcode + iOS require an absolute path, but we haven't been able to come up with any hard rules.

From your script:

```
CONFIGURATION_BUILD_DIR=$(PWD)/iOS/
```

That looks suspicious.  I would have expected:

```
CONFIGURATION_BUILD_DIR=$(PWD)/build/iOS/
```

**Comment by RichardStoff** [comment]
No, I didn't try an absolute path, and obviously I should have try it 'caus it works thanks.

for information my CONFIGURATION_BUILD_DIR is fine even if It's a bit odd. this is my calabash dir architecture
* build/ i have my build.sh in it which make a iOS/myapplication.app
* config/ cucumber.yml
* features/ everything about _steps.rb and .feature
* src/ iOS and Android submodules

Anyway, my problem is solve thanks :) 

Now I have another problem about accepting geolocation system alertView on iOS7 :/ I may open another issue (just looking for answer first).

**Comment by jmoody** [comment]
I am going to close this.

You might want to add these two flags to your script:

```
   -SYMROOT="${CAL_BUILD_DIR}" \
    -derivedDataPath "${CAL_BUILD_DIR}"
```

This will confine _all_ build products to the ./build directory.

I don't know what the behavior of CONFIGURATION_BUILD_DIR is.
