### ISSUE TITLE
Xcode 7/iOS 9 - Playback file not found for rotation

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash-ios#837]
### Reproduce

CalSmokeApp on iOS Simulator

cucumber features/rotation.feature:20 # Scenario: Controller does not respond to orientation changes
cucumber features/rotation.feature:25 # Scenario: Controller does respond to orientation changes

```
  Given I see the special tab                            
    And I try to rotate the home button so it is on the right
    Then the home button should be on the right     
```

### Expected

A device rotation.

### Found

```
  And I try to rotate the home button so it is on the right
  Playback file not found for: 'rotate_left_home_down'
    searched for => 
      * 'rotate_left_home_down_ios9_F24BE4F9-36C5-4842-84A4-1EA2614B8A3E.base64'
      * 'rotate_left_home_down_ios8_F24BE4F9-36C5-4842-84A4-1EA2614B8A3E.base64'
      * 'rotate_left_home_down_ios7_F24BE4F9-36C5-4842-84A4-1EA2614B8A3E.base64'
      * 'rotate_left_home_down_ios6_F24BE4F9-36C5-4842-84A4-1EA2614B8A3E.base64'
      * 'rotate_left_home_down_ios5_F24BE4F9-36C5-4842-84A4-1EA2614B8A3E.base64'
    in directories =>
      * '/Users/moody/git/calabash/ios-smoke-test-app/CalSmokeApp/features/playback'
      * '/Users/moody/git/calabash/ios-smoke-test-app/CalSmokeApp'
      * '/Users/moody/git/calabash/ios-smoke-test-app/CalSmokeApp/features'
      * '/Users/moody/git/calabash/calabash-ios/calabash-cucumber/lib/calabash-cucumber/resources/'
   (RuntimeError)
  /Users/moody/git/calabash/calabash-ios/calabash-cucumber/lib/calabash-cucumber/playback_helpers.rb:92:in `load_playback_data'
  /Users/moody/git/calabash/calabash-ios/calabash-cucumber/lib/calabash-cucumber/playback_helpers.rb:123:in `playback'
  /Users/moody/git/calabash/calabash-ios/calabash-cucumber/lib/calabash-cucumber/rotation_helpers.rb:89:in `block in rotate_home_button_to'
  /Users/moody/git/calabash/calabash-ios/calabash-cucumber/lib/calabash-cucumber/rotation_helpers.rb:85:in `each'
  /Users/moody/git/calabash/calabash-ios/calabash-cucumber/lib/calabash-cucumber/rotation_helpers.rb:85:in `rotate_home_button_to'
  ./features/step_definitions/rotation_steps.rb:3:in `/^I try to rotate the home button so it is on the (left|right)$/'
  features/rotation.feature:27:in `And I try to rotate the home button so it is on the right'
```

### Notes

Has something to do with how we are creating the device name.  Possibly a bug in run-loop, but more likely a problem with how we are using run-loop.

**Comment by jmoody** [comment]
The problem is that particular shell defined a `DEVICE` env var as a simulator UDID which caused this line:

```ruby
device = options['DEVICE'] || ENV['DEVICE'] || 'iphone'
```

to incorrectly create the recording name.

In my analysis, I discovered that we've been using iPhone records for iPad rotations for a very long time now with no ill consequences.

**Comment by jmoody** [comment]
Fixed.
