### ISSUE TITLE
0.16.2 reset_app_sandbox is failing for iOS 9 devices: "Could not find a simulator that matches"

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash-ios#852]
```
$ cd calabash-cucumber/test/cucumber
$ be cucumber -t @user_defaults @reset_app_btw_scenarios @reset_app_before_hook

 @user_defaults @reset_app_btw_scenarios @reset_app_before_hook
  Scenario: 22 The switch should be off because I did reset the app before this Scenario
 Could not find a simulator that matches 'iPhone 5s (9.0)' (RuntimeError)
 /Users/moody/git/calabash/calabash-ios/calabash-cucumber/lib/calabash-cucumber/launcher.rb:293:in `reset_app_sandbox'
 /Users/moody/git/calabash/calabash-ios/calabash-cucumber/lib/calabash-cucumber/launcher.rb:597:in `relaunch'
 /Users/moody/git/calabash/calabash-ios/calabash-cucumber/test/cucumber/features/support/01_launch.rb:40:in `Before'
    Then I should not see the files I put in the sandbox
    Then I should see the switch is off
```

**Comment by agileseph** [comment]
@jmoody 
As I see code, one place was not patched for xcode7 from calabash-cucumber gem in reset_app_sandbox method. After patch it works.
hotfix for launcher:281
```
   if sim_control.xcode_version_gte_6?
      postfix = sim_control.xcode_version_gte_7? ? '' : ' Simulator'
      default_sim = RunLoop::Core.default_simulator(xcode)
      name_or_udid = merged_opts[:udid] || ENV['DEVICE_TARGET'] || default_sim

      target_simulator = nil
      sim_control.simulators.each do |device|
        instruments_launch_name = "#{device.name} (#{device.version.to_s}#{postfix})"

```

**Comment by agileseph** [comment]
@jmoody 
I made the pull request for this bug. Please check it.
