### ISSUE TITLE
'xcrun instruments -s devices' always hangs

### ISSUE THREAD

**Issue by kennethjiang** [calabash/calabash-ios#857]
When I run "cucumber" it always failed with:
```
...
Sending 'TERM' to xcrun instruments -s devices process '10396'
Waiting for xcrun instruments -s devices '10396' to terminate
Waited for 0.103321 seconds for xcrun instruments -s devices with '10396' to terminate
  execution expired (RunLoop::Xcrun::XcrunError)
  /Users/kenneth/.rvm/gems/ruby-2.2.0/gems/run_loop-1.5.4/lib/run_loop/xcrun.rb:59:in `rescue in exec'
  /Users/kenneth/.rvm/gems/ruby-2.2.0/gems/run_loop-1.5.4/lib/run_loop/xcrun.rb:76:in `exec'
...
```
The root cause of this problem is, ```xcrun instruments -s devices``` returns 3000 lines (most of them are Apple Watch - xxx). The amount of output fills buffer in Open3 used in ```run_loop/xcrun.rb:37``` and causes  ```run_loop/xcrun.rb:40``` to block until timeout.

**Comment by kennethjiang** [comment]
I'm running Xcode 7.

**Comment by kennethjiang** [comment]
Duplicate with https://github.com/calabash/run_loop/issues/257
