### ISSUE TITLE
unable to reset simulator on xcode7 ios9

### ISSUE THREAD

**Issue by tejasv02** [calabash/calabash-ios#858]
##### I feel Its due to def simulator_target? in launcher.rb returning xcode 7 simulator as device

```

DEBUG=1 DEVICE_TARGET="iPhone 6s" APP_BUNDLE_PATH="./build/ios/xxx-cal.app" calabash-ios console
Running irb...
irb(main):001:0> start_test_server_in_background
irb(main):005:0* @launcher ||= Calabash::Cucumber::Launcher.new
Calabash::Cucumber::Launcher: Launch Method 
irb(main):006:0> @launcher.reset_simulator
RuntimeError: Calling 'reset_simulator' when targeting a device is not allowed
	from /Users/tejasv2/.rvm/gems/ruby-2.1.0/gems/calabash-cucumber-0.16.2/lib/calabash-cucumber/launcher.rb:334:in `reset_simulator'
	from (irb):6
	from /Users/tejasv2/.rvm/rubies/ruby-2.1.0/bin/irb:11:in `<main>'
```

but below methods can reset simulator 
```
irb(main):007:0>     RunLoop::SimControl.new.reset_sim_content_and_settings
false
irb(main):008:0> 
irb(main):009:0* @launcher.launch_simulator
```

**Comment by jmoody** [comment]
Please update to Calabash 0.16.3.

https://github.com/calabash/calabash-ios/issues/852

**Comment by tejasv02** [comment]
I still see same error:
```
@launcher.reset_simulator
RuntimeError: Calling 'reset_simulator' when targeting a device is not allowed
	from /Users/xx/.rvm/gems/ruby-2.1.0/gems/calabash-cucumber-0.16.3/lib/calabash-cucumber/launcher.rb:334:in `reset_simulator'
	from (irb):5
	from /Users/xx/.rvm/rubies/ruby-2.1.0/bin/irb:11:in `<main>'


{
                  "device_family" => "iPhone",
                        "outcome" => "SUCCESS",
                    "server_port" => 37265,
               "simulator_device" => "iPhone",
                      "simulator" => "CoreSimulator 179 - Device: iPhone 6s - Runtime: iOS 9.0 (13A340) - DeviceType: iPhone 6s",
                       "app_name" => "xxx-cal",
                    "app_version" => "8.0.0",
              "screen_dimensions" => {
        "sample" => 1,
        "height" => 1334,
         "width" => 750,
         "scale" => 2
    },
                            "git" => {
             "revision" => "9b81cb7",
        "remote_origin" => "git@github.com:calabash/calabash-ios-server.git",
               "branch" => "master"
    },
                    "device_name" => "iPhone Simulator",
                          "4inch" => false,
                         "app_id" => "tv.xx.xx-cal",
                    "form_factor" => "iphone 6",
                         "system" => "x86_64",
                        "version" => "0.16.2",
                    "iOS_version" => "9.0",
           "short_version_string" => "8.0.0",
                    "ios_version" => "9.0",
    "iphone_app_emulated_on_ipad" => false,
               "model_identifier" => "iPhone8,1",
                   "app_base_sdk" => "iphonesimulator9.0"
}
```

**Comment by tejasv02** [comment]
When I run below command they don't contain 'simulator' in simulator name anymore, 
ex: xcode 6.4 simulator has name  `iPhone 6 (8.4 Simulator)`, but xcode 7 simulators dont have that.
```
xcrun instruments -s

Known Devices:
iPad 2 (9.0) [E0EECA5D-7BE2-4322-B025-D7C199AE3F7F]
iPad Air (9.0) [E775BDAE-6927-4C9B-A61A-B27CACDBACFE]
iPhone 6 (9.0) [DEDBA975-0F52-4085-A3AF-10976553B2FB]
```

**Comment by jmoody** [comment]
Using just the simulator name is not allowed:  "iPhone 6s"

Use the name + the version number (as seen in instruments output):

```
DEVICE_TARGET="iPhone 6s (9.1)"
```

or the simulator UDID: 

```
DEVICE_TARGET="E0EECA5D-7BE2-4322-B025-D7C199AE3F7F"
```

**Comment by jmoody** [comment]
Is it possible that you have device connected whose name is "iPhone 6s"?

**Comment by tejasv02** [comment]
DEVICE_TARGET="iPhone 6s (9.0)" works fine.

Thanks for the help
