### ISSUE TITLE
start_test_server_in_background command fails to start the server

### ISSUE THREAD

**Issue by kei-ito** [calabash/calabash-ios#866]
**Environment**

- MacBook Air
  - OS X 10.10.5
  - Xcode 7.0.1, /Applications/Xcode.app/Contents/Developer
  - calabash-ios 0.16.3
  - cucumber 1.3.20
- iPhone 5s
  - iOS 9.0.2
- ios-sample.app
  - [https://github.com/kei-ito/ios-sample](https://github.com/kei-ito/ios-sample)

**Description**

`start_test_server_in_background` command fails to start the server.

**Steps to reproduce**

1: Start a console with some options.

```
$ APP_BUNDLE_PATH=/path/to/ios-sample.app DEVICE_TARGET=udid-of-my-iPhone DEBUG=1 calabash-ios console
Running irb...
irb(main):001:0>
```

2: Try to start the server.

```
irb(main):001:0> start_test_server_in_background
```

**Console output**

```
itok:ios-sample 13:54:04$ APP_BUNDLE_PATH=/Users/itok/workspace/ios-sample/build/ios-sample.app DEVICE_TARGET=udid-of-my-iPhone DEBUG=1 calabash-ios console
Running irb...
^[[Airb(main):001:0> start_test_server_in_background

INFO: Using uia strategy: 'host'
2015-10-02 13:54:14 +0900 [RunLoop:debug]: 
{
                        :app => "/Users/itok/workspace/ios-sample/build/ios-sample.app",
                       :args => [],
    :bundle_dir_or_bundle_id => "com.example.ios-sample",
                  :bundle_id => "com.example.ios-sample",
                     :device => "iphone",
              :device_target => "udid-of-my-iPhone",
                :instruments => #<Instruments 7.0.1>,
              :launch_method => :instruments,
             :launch_retries => 5,
                   :log_file => "/var/folders/sr/dfhq6hz51ddgrrwb4klj919m0000gn/T/run_loop20151002-56190-xhk7m3/run_loop.out",
                  :no_launch => false,
                    :no_stop => false,
         :relaunch_simulator => true,
                      :reset => false,
                :results_dir => "/var/folders/sr/dfhq6hz51ddgrrwb4klj919m0000gn/T/run_loop20151002-56190-xhk7m3",
          :results_dir_trace => "/var/folders/sr/dfhq6hz51ddgrrwb4klj919m0000gn/T/run_loop20151002-56190-xhk7m3/trace",
                     :script => "/var/folders/sr/dfhq6hz51ddgrrwb4klj919m0000gn/T/run_loop20151002-56190-xhk7m3/_run_loop.js",
                :sdk_version => nil,
                       :udid => "udid-of-my-iPhone",
               :uia_strategy => :host,
                      :xcode => "7.0.1",
                 :xcode_path => "/Applications/Xcode.app/Contents/Developer"
}
EXEC: xcrun instruments -s templates

### Starting on udid-of-my-iPhone App: com.example.ios-sample ###
2015-10-02 13:54:15 +0900 [RunLoop:debug]: xcrun instruments -w udid-of-my-iPhone -D /var/folders/sr/dfhq6hz51ddgrrwb4klj919m0000gn/T/run_loop20151002-56190-xhk7m3/trace -t Automation com.example.ios-sample -e UIARESULTSPATH /var/folders/sr/dfhq6hz51ddgrrwb4klj919m0000gn/T/run_loop20151002-56190-xhk7m3 -e UIASCRIPT /var/folders/sr/dfhq6hz51ddgrrwb4klj919m0000gn/T/run_loop20151002-56190-xhk7m3/_run_loop.js >& /var/folders/sr/dfhq6hz51ddgrrwb4klj919m0000gn/T/run_loop20151002-56190-xhk7m3/run_loop.out
2015-10-02 13:54:15 +0900 [RunLoop:debug]: Preparation took 1.127761 seconds
2015-10-02 13:54:20 +0900 [RunLoop:debug]: Launching took 5.185041 seconds
DEBUG: It took 6.313092 seconds to launch the app
#<RuntimeError: Timed out connecting to Calabash server after 10 retries. Make sure it is linked and App isn't crashing>
RuntimeError: Unable to make connection to Calabash Server at http://localhost:37265/
Make sure you don't have a firewall blocking traffic to http://localhost:37265/.

	from /Users/itok/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.16.3/lib/calabash-cucumber/launcher.rb:823:in `rescue in ensure_connectivity'
	from /Users/itok/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.16.3/lib/calabash-cucumber/launcher.rb:783:in `ensure_connectivity'
	from /Users/itok/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.16.3/lib

/calabash-cucumber/launcher.rb:646:in `relaunch'
	from /Users/itok/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/calabash-cucumber-0.16.3/lib/calabash-cucumber/core.rb:921:in `start_test_server_in_background'
	from (irb):1
	from /Users/itok/.rbenv/versions/2.0.0-p247/bin/irb:12:in `<main>'
irb(main):002:0> exit
```

**/Applications/Utilities/Console.app output**
```
2015/10/02 13:54:06.428	airport[56187]	Error: Apple8211Get(rssiDict) failed
2015/10/02 13:54:14.444	com.apple.xpc.launchd[1]	(com.apple.StreamingUnzipService) The _DirtyJetsamPriority key is not available on this platform.
2015/10/02 13:54:14.444	com.apple.xpc.launchd[1]	(com.apple.StreamingUnzipService) The _DirtyJetsamMemoryLimit key is not available on this platform.
2015/10/02 13:54:14.444	com.apple.xpc.launchd[1]	(com.apple.imfoundation.IMRemoteURLConnectionAgent) The _DirtyJetsamMemoryLimit key is not available on this platform.
2015/10/02 13:54:14.513	com.apple.xpc.launchd[1]	(com.apple.StreamingUnzipService) The _DirtyJetsamPriority key is not available on this platform.
2015/10/02 13:54:14.513	com.apple.xpc.launchd[1]	(com.apple.StreamingUnzipService) The _DirtyJetsamMemoryLimit key is not available on this platform.
2015/10/02 13:54:14.554	com.apple.SecurityServer[82]	Session 102743 created
2015/10/02 13:54:14.555	com.apple.SecurityServer[82]	Killing auth hosts
2015/10/02 13:54:14.555	com.apple.SecurityServer[82]	Session 102742 destroyed
2015/10/02 13:54:14.565	instruments[56240]	DTServiceHubClient: connected to server (singleton pid: 56241, initial pid: 56241)
2015/10/02 13:54:15.418	com.apple.xpc.launchd[1]	(com.apple.StreamingUnzipService) The _DirtyJetsamPriority key is not available on this platform.
2015/10/02 13:54:15.418	com.apple.xpc.launchd[1]	(com.apple.StreamingUnzipService) The _DirtyJetsamMemoryLimit key is not available on this platform.
2015/10/02 13:54:15.418	com.apple.xpc.launchd[1]	(com.apple.imfoundation.IMRemoteURLConnectionAgent) The _DirtyJetsamMemoryLimit key is not available on this platform.
2015/10/02 13:54:15.496	com.apple.xpc.launchd[1]	(com.apple.StreamingUnzipService) The _DirtyJetsamPriority key is not available on this platform.
2015/10/02 13:54:15.496	com.apple.xpc.launchd[1]	(com.apple.StreamingUnzipService) The _DirtyJetsamMemoryLimit key is not available on this platform.
2015/10/02 13:54:15.536	com.apple.SecurityServer[82]	Session 102744 created
2015/10/02 13:54:15.540	com.apple.SecurityServer[82]	Killing auth hosts
2015/10/02 13:54:15.540	com.apple.SecurityServer[82]	Session 102743 destroyed
2015/10/02 13:54:15.547	instruments[56244]	DTServiceHubClient: connected to server (singleton pid: 56245, initial pid: 56245)
2015/10/02 13:54:16.064	instruments[56244]	enumerate proxied devices: true
2015/10/02 13:54:16.070	instruments[56244]	AMDeviceStartSession (thread 0x7fff7c06f300): Could not start session with device udid-of-my-iPhone: kAMDNotConnectedError
2015/10/02 13:54:16.623	instruments[56244]	WebKit Threading Violation - initial use of WebKit from a secondary thread.
2015/10/02 13:54:17.017	airport[56247]	Error: Apple8211Get(rssiDict) failed
2015/10/02 13:54:17.282	instruments[56244]	AMDeviceStartSession (thread 0x7fff7c06f300): Could not start session with device udid-of-my-iPhone: kAMDNotConnectedError
2015/10/02 13:54:19.017	instruments[56244]	AMDeviceStartSession (thread 0x7fff7c06f300): Could not start session with device udid-of-my-iPhone: kAMDSessionActiveError
2015/10/02 13:54:27.587	airport[56328]	Error: Apple8211Get(rssiDict) failed
2015/10/02 13:54:38.104	airport[56429]	Error: Apple8211Get(rssiDict) failed
2015/10/02 13:54:48.582	airport[56529]	Error: Apple8211Get(rssiDict) failed
2015/10/02 13:54:59.142	airport[56636]	Error: Apple8211Get(rssiDict) failed
2015/10/02 13:55:09.611	airport[56732]	Error: Apple8211Get(rssiDict) failed
```

**Comment by jmoody** [comment]
You are missing the DEVICE_ENDPOINT variable:

http://calabashapi.xamarin.com/ios/file.ENVIRONMENT_VARIABLES.html#label-DEVICE_ENDPOINT

Thank you for the code formatting and the details.
