### ISSUE TITLE
RESET_APP_BETWEEN_SCENARIOS is still resetting the simulator not just the app sandbox

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash-ios#878]

**Comment by jmoody** [comment]
```
 Expected 'Shutdown but found 'Booted' after waiting. (RuntimeError)
  /Users/moody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/run_loop-1.5.6/lib/run_loop/core_simulator.rb:384:in `wait_for_device_state'
  /Users/moody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/run_loop-1.5.6/lib/run_loop/core_simulator.rb:257:in `reset_app_sandbox'
  /Users/moody/git/calabash/ios-smoke-test-app/CalSmokeApp/features/support/01_launch.rb:54:in `Before'
```

**Comment by jmoody** [comment]
We won't be able to all three behaviors into the 0.17.0 release, but we can fix behavior of reset_app_sandbox.
