### ISSUE TITLE
"no visible keyboard (RuntimeError)" error seen in logs after successful test run when Cucumber 2.1.0 is installed

### ISSUE THREAD

**Issue by TeresaP** [calabash/calabash-ios#976]
We see this in the logs after a successful test is completed (preventing the test from actually succeeding):
```
no visible keyboard (RuntimeError)
/Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.17.0/lib/calabash-cucumber/failure_helpers.rb:70:in `screenshot_and_raise'
/Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.17.0/lib/calabash-cucumber/keyboard_helpers.rb:246:in `_ensure_can_enter_text'
/Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.17.0/lib/calabash-cucumber/keyboard_helpers.rb:308:in `keyboard_enter_char'
/Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.17.0/lib/calabash-cucumber/keyboard_helpers.rb:445:in `tap_keyboard_action_key'
/Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.17.0/lib/calabash-cucumber/keyboard_helpers.rb:467:in `done'
/Library/Ruby/Gems/2.0.0/gems/cucumber-2.1.0/lib/cucumber/formatter/fanout.rb:16:in `block in method_missing'
/Library/Ruby/Gems/2.0.0/gems/cucumber-2.1.0/lib/cucumber/formatter/fanout.rb:15:in `each'
/Library/Ruby/Gems/2.0.0/gems/cucumber-2.1.0/lib/cucumber/formatter/fanout.rb:15:in `method_missing'
/Library/Ruby/Gems/2.0.0/gems/cucumber-core-1.3.0/lib/cucumber/core/test/runner.rb:40:in `done'
/Library/Ruby/Gems/2.0.0/gems/cucumber-core-1.3.0/lib/cucumber/core/filter.rb:61:in `done'
/Library/Ruby/Gems/2.0.0/gems/cucumber-core-1.3.0/lib/cucumber/core/filter.rb:61:in `done'
/Library/Ruby/Gems/2.0.0/gems/cucumber-core-1.3.0/lib/cucumber/core/filter.rb:61:in `done'
/Library/Ruby/Gems/2.0.0/gems/cucumber-core-1.3.0/lib/cucumber/core/filter.rb:61:in `done'
/Library/Ruby/Gems/2.0.0/gems/cucumber-core-1.3.0/lib/cucumber/core/filter.rb:61:in `done'
/Library/Ruby/Gems/2.0.0/gems/cucumber-core-1.3.0/lib/cucumber/core/filter.rb:61:in `done'
/Library/Ruby/Gems/2.0.0/gems/cucumber-2.1.0/lib/cucumber/filters/quit.rb:17:in `done'
/Library/Ruby/Gems/2.0.0/gems/cucumber-core-1.3.0/lib/cucumber/core/test/filters/locations_filter.rb:19:in `done'
/Library/Ruby/Gems/2.0.0/gems/cucumber-core-1.3.0/lib/cucumber/core/filter.rb:61:in `done'
/Library/Ruby/Gems/2.0.0/gems/cucumber-core-1.3.0/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
/Library/Ruby/Gems/2.0.0/gems/cucumber-core-1.3.0/lib/cucumber/core/compiler.rb:23:in `done'
/Library/Ruby/Gems/2.0.0/gems/cucumber-core-1.3.0/lib/cucumber/core/gherkin/parser.rb:39:in `done'
/Library/Ruby/Gems/2.0.0/gems/cucumber-core-1.3.0/lib/cucumber/core.rb:29:in `parse'
/Library/Ruby/Gems/2.0.0/gems/cucumber-core-1.3.0/lib/cucumber/core.rb:18:in `compile'
/Library/Ruby/Gems/2.0.0/gems/cucumber-2.1.0/lib/cucumber/runtime.rb:70:in `run!'
/Library/Ruby/Gems/2.0.0/gems/cucumber-2.1.0/lib/cucumber/cli/main.rb:32:in `execute!'
/Library/Ruby/Gems/2.0.0/gems/cucumber-2.1.0/bin/cucumber:8:in `<top (required)>'
/usr/bin/cucumber:23:in `load'
/usr/bin/cucumber:23:in `<top (required)>'
-e:1:in `load'
-e:1:in `<main>'
```
Solution: roll back to Cucumber 1.3.20 in your Gemfile.

**Comment by jmoody** [comment]
Is this an async test by any chance?

This is using a Page Object?  I wonder if our `method_missing` is causing us to overwrite a cucumber method.

@TeresaP Can you contact me off channel? Maybe through a private gitter chat?  I would like to see if I can reproduce locally.

**Comment by jmoody** [comment]
ATTN @krukow I might need to spend some time debugging this.

**Comment by TeresaP** [comment]
I can't remember how much we ended up talking offline. This is just a normal test, not using a page object.

**Comment by TeresaP** [comment]
FYI in case it helps, we use 
```
--format pretty
--format junit
--format json
--format Calabash::Formatters::Html
```

**Comment by TeresaP** [comment]
Thanks a lot for your help @jmoody! 

Turns out there was a conflict with the Done method in KeyboardHelpers.  Adding this to our support code unblocked us from upgrading past Cucumber 1.3.20:

```
Calabash::Cucumber::KeyboardHelpers.send(:remove_method, :done) if Calabash::Cucumber::KeyboardHelpers.method_defined?(:done)
```
